<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-03-31">
  <title>Sociology 106 – Week 11</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="slides.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 11</h1>
  <p class="subtitle">Sociology 106: Quantitative Sociological Methods</p>

<div class="quarto-title-authors">
</div>

  <p class="date">March 31, 2026</p>
</section>
<section id="agenda" class="slide level2 smaller">
<h2>Agenda</h2>
<p><strong>Housekeeping:</strong></p>
<ul>
<li>HW #8, HW #9, Revised Proposal with Outline</li>
</ul>
<p><strong>Statistical content — four parts:</strong></p>
<ul>
<li><strong>Part 1</strong>: Outcome variables and key predictors — what are we trying to explain?</li>
<li><strong>Part 2</strong>: From correlation to regression — estimating the magnitude of a linear relationship</li>
<li><strong>Part 3</strong>: Regression with categorical predictors — dummy variables and baseline categories</li>
<li><strong>Part 4</strong>: OLS assumptions and multiple regression</li>
</ul>
<p><strong>In-class lab:</strong></p>
<ul>
<li>Applying OLS regression to GSS data</li>
</ul>
</section>
<section id="housekeeping" class="slide level2 smaller">
<h2>Housekeeping</h2>
<p><strong>Weekly Assignment #8</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 2</span> — hypothesis testing from Week 9</li>
</ul>
<p><strong>Weekly Assignment #9</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 9</span></li>
<li>Run an OLS regression on your research dataset — today’s lecture covers everything you need</li>
<li>Uses <code>modelsummary()</code> for a clean regression table (covered today)</li>
<li>If using a categorical predictor, use <code>fct_relevel()</code> to set a baseline category (covered today)</li>
</ul>
<p><strong>Revised Proposal with Outline</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 16</span></li>
<li>Should now describe the statistical techniques you plan to use — including regression!</li>
<li>Come to office hours if you need help connecting your research question to a regression model</li>
</ul>
</section>
<section id="where-we-are-in-the-course" class="slide level2 smaller">
<h2>Where We Are in the Course</h2>
<ul>
<li><strong>Week 9:</strong> Hypothesis testing — is there a relationship, or is it just chance?</li>
<li><strong>This week (Week 11):</strong> Linear regression — how <em>strong</em> is the relationship, and in what direction?</li>
<li><strong>Week 12:</strong> Logistic regression — predicting binary outcomes</li>
<li><strong>Week 13:</strong> Extensions — multiple controls, more complex models</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The big picture: from “yes or no” to “how much?”</strong></p>
</div>
<div class="callout-content">
<p>Last week we answered: <em>“Is there a statistically significant relationship?”</em> Today’s tool — regression — gives a quantitative answer: <em>“For every one-unit increase in X, how much does Y change on average?”</em></p>
</div>
</div>
</div>
</section>
<section>
<section id="part-1-outcome-variables-and-key-predictors" class="title-slide slide level1 center">
<h1>Part 1: Outcome Variables and Key Predictors</h1>
<p>What are we trying to explain, and with what?</p>
</section>
<section id="two-variables-two-roles" class="slide level2 smaller">
<h2>Two Variables, Two Roles</h2>
<p>Every regression analysis has variables playing two distinct roles:</p>
<div class="fragment fade-up">
<p><strong>The outcome variable</strong> — what you are trying to explain or predict</p>
<ul>
<li>Also called: dependent variable (DV), response variable, <strong>Y</strong></li>
<li>This is the phenomenon your research question is about – <strong>the thing that is effected</strong></li>
</ul>
</div>
<div class="fragment fade-up">
<p><strong>The predictor</strong> — what you are using to explain the outcome</p>
<ul>
<li>Also called: key independent variable (key IV), explanatory variable, <strong>X</strong></li>
<li>This is the main theoretical variable your hypothesis is about – <strong>the thing that does the affecting</strong></li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>These labels reflect your theory, not your data:</strong></p>
</div>
<div class="callout-content">
<p>Calling one variable the “outcome” and another the “predictor” encodes your theoretical argument about which variable explains which. Regression is a tool for formalizing that argument quantitatively.</p>
</div>
</div>
</div>
</div>
</section>
<section id="language-matters" class="slide level2 smaller">
<h2>Language Matters</h2>
<p>You’ll encounter many terms for the same concept — here’s a cheat sheet:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>What it means</th>
<th>Also called</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Outcome variable</strong></td>
<td>What you are trying to explain</td>
<td>Dependent variable (DV), Y, response variable</td>
</tr>
<tr class="even">
<td><strong>Key predictor</strong></td>
<td>Your main explanatory variable</td>
<td>Key IV, key independent variable, X</td>
</tr>
<tr class="odd">
<td><strong>Control variable</strong></td>
<td>Additional IV included to rule out alternatives</td>
<td>Covariate</td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="fragment fade-up">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>In your research paper:</strong></p>
</div>
<div class="callout-content">
<p>Your paper proposal asked you to identify your <strong>key independent</strong> and <strong>dependent variables</strong>. These map directly onto <strong>key predictor</strong> and <strong>outcome variable</strong> in regression. Today you learn to formally estimate the relationship between them.</p>
</div>
</div>
</div>
</div>
</section>
<section id="setting-up-your-research-question" class="slide level2 smaller">
<h2>Setting Up Your Research Question</h2>
<p>Before running any regression, be explicit about your variables and expectations:</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Step 1 — Research Question</a></li><li><a href="#tabset-1-2">Step 2 — Hypothesis</a></li><li><a href="#tabset-1-3">Step 3 — Visualize First</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>Your research question should name both roles:</p>
<blockquote>
<p><em>“How does occupational prestige impact household income?”</em></p>
</blockquote>
<ul>
<li><strong>Outcome variable (Y):</strong> <code>income91</code> — household income, in dollars — <em>what we’re explaining</em></li>
<li><strong>Key predictor (X):</strong> <code>prestg80</code> — occupational prestige score — <em>our main theoretical variable</em></li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why income as the outcome?</strong></p>
</div>
<div class="callout-content">
<p>We have theoretical reasons to believe occupational status drives income (not the reverse). The direction of influence determines which variable goes on which side of the regression equation.</p>
</div>
</div>
</div>
</div>
<div id="tabset-1-2">
<p>Write out your hypothesis before looking at the data:</p>
<p><span class="math display">\[H_0: \beta_{\text{prestige}} = 0 \quad \text{(prestige has no effect on income)}\]</span></p>
<p><span class="math display">\[H_1: \beta_{\text{prestige}} &gt; 0 \quad \text{(higher prestige → higher income)}\]</span></p>
<p>This is a <strong>one-tailed test</strong> — theory strongly predicts the direction (positive).</p>
<p>In most cases, we’ll default to <strong>two-tailed</strong> unless we have strong prior theoretical reason for directionality.</p>
</div>
<div id="tabset-1-3">
<p>Always plot your variables before running a regression:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">ggplot</span>(attain_reg, <span class="fu">aes</span>(<span class="at">x =</span> prestg80, <span class="at">y =</span> income91)) <span class="sc">+</span></span>
<span id="cb1-2"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">color =</span> <span class="st">"gray50"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb1-3"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#4E79A7"</span>,</span>
<span id="cb1-4"><a></a>              <span class="at">fill =</span> <span class="st">"#4E79A7"</span>, <span class="at">alpha =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb1-5"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb1-6"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Occupational Prestige and Household Income (GSS, 1991)"</span>,</span>
<span id="cb1-7"><a></a>       <span class="at">x =</span> <span class="st">"Occupational Prestige Score (Key Predictor)"</span>,</span>
<span id="cb1-8"><a></a>       <span class="at">y =</span> <span class="st">"Household Income — $ (Outcome)"</span>) <span class="sc">+</span></span>
<span id="cb1-9"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-2-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-2-from-correlation-to-regression" class="title-slide slide level1 center">
<h1>Part 2: From Correlation to Regression</h1>
<p>From “is there a relationship?” to “how strong is it?”</p>
</section>
<section id="what-correlation-tells-us-and-what-it-doesnt" class="slide level2 smaller">
<h2>What Correlation Tells Us — and What It Doesn’t</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>A <strong>correlation coefficient</strong> (r) describes direction and strength:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>r</th>
<th>Strength</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>r ≈ 0.3</td>
<td>Weak</td>
</tr>
<tr class="even">
<td>r ≈ 0.5</td>
<td>Moderate</td>
</tr>
<tr class="odd">
<td>r ≈ 0.8</td>
<td>Strong</td>
</tr>
</tbody>
</table>
<p><strong>But correlation cannot answer:</strong></p>
<ul>
<li>How many dollars does income increase per one-point gain in occupational prestige?</li>
<li>What is the predicted income for someone with a prestige score of 50?</li>
<li>Is this relationship significant after controlling for sex?</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The key limitation:</strong></p>
</div>
<div class="callout-content">
<p>Two datasets can have the same correlation (r = 0.82) but completely different <em>slopes</em> — different magnitudes, different units, different practical meanings.</p>
<p><strong>Regression gives us the slope</strong> — the actual quantitative size of the relationship in the units of Y per unit of X.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-linear-regression-model" class="slide level2 smaller">
<h2>The Linear Regression Model</h2>
<p>For any value <span class="math inline">\(x\)</span> of the key predictor, the <strong>expected value</strong> of the outcome is:</p>
<p><span class="math display">\[E[Y \mid x] = \alpha + \beta x\]</span></p>
<div class="fragment fade-up">
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Name</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(E[Y \mid x]\)</span></td>
<td>Conditional mean</td>
<td>Expected (average) value of outcome <span class="math inline">\(Y\)</span> when <span class="math inline">\(X = x\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\alpha\)</span></td>
<td>Intercept</td>
<td>Predicted value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X = 0\)</span> — the baseline anchor</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta\)</span></td>
<td>Slope</td>
<td>Average change in <span class="math inline">\(Y\)</span> for a <strong>one-unit increase</strong> in <span class="math inline">\(X\)</span></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment fade-up">
<p><strong>In practice</strong>, we estimate from sample data:</p>
<p><span class="math display">\[y_i = a + bx_i + e_i\]</span></p>
<ul>
<li><span class="math inline">\(a\)</span> = estimated intercept (sample estimate of <span class="math inline">\(\alpha\)</span>)</li>
<li><span class="math inline">\(b\)</span> = estimated slope (sample estimate of <span class="math inline">\(\beta\)</span>) — <strong>this is the key number</strong></li>
<li><span class="math inline">\(e_i\)</span> = residual for observation <span class="math inline">\(i\)</span> — the gap between observed <span class="math inline">\(y_i\)</span> and predicted <span class="math inline">\(\hat{y}_i\)</span></li>
</ul>
</div>
<div class="fragment fade-up">
<p><strong>OLS (ordinary least squares)</strong> chooses <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> to minimize:</p>
<p><span class="math display">\[\text{RSS} = \sum_{i=1}^{n} e_i^2 = \sum_{i=1}^{n} (y_i - a - bx_i)^2\]</span></p>
<p>Why square? Prevents cancellation, penalizes large misses, and produces a unique closed-form solution.</p>
</div>
</section>
<section id="observed-vs.-predicted-values" class="slide level2 smaller">
<h2>Observed vs.&nbsp;Predicted Values</h2>

<img data-src="week11_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Residual</strong> <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span>: how far each observation is from the line. OLS <strong>minimizes the sum of squared residuals</strong> — hence “ordinary least squares.”</p>
</div>
</div>
</div>
</section>
<section id="running-ols-in-r" class="slide level2 smaller scrollable">
<h2>Running OLS in R</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Setup</a></li><li><a href="#tabset-2-2"><code>summary()</code> Output</a></li><li><a href="#tabset-2-3"><code>modelsummary()</code></a></li><li><a href="#tabset-2-4">Reading the Output</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p><strong>The <code>lm()</code> function</strong> runs OLS regression:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">lm</span>(outcome <span class="sc">~</span> key_predictor, <span class="at">data =</span> your_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>The variable on the <strong>left</strong> of <code>~</code> is always the <strong>outcome (Y)</strong></li>
<li>The variable on the <strong>right</strong> is the <strong>key predictor (X)</strong></li>
</ul>
<p><strong>Our example:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Filter to complete cases</span></span>
<span id="cb3-2"><a></a>attain_reg <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(prestg80), <span class="sc">!</span><span class="fu">is.na</span>(income91))</span>
<span id="cb3-3"><a></a></span>
<span id="cb3-4"><a></a><span class="co"># Fit the OLS model — outcome ~ key_predictor</span></span>
<span id="cb3-5"><a></a>model_biv <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> prestg80, <span class="at">data =</span> attain_reg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">summary</span>(model_biv)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income91 ~ prestg80, data = attain_reg)

Residuals:
   Min     1Q Median     3Q    Max 
-53305 -24664 -10902  12726 390467 

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept) 21273.31    2134.09   9.968 &lt;0.0000000000000002 ***
prestg80      472.13      45.94  10.277 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 37680 on 2525 degrees of freedom
Multiple R-squared:  0.04015,   Adjusted R-squared:  0.03977 
F-statistic: 105.6 on 1 and 2525 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
</div>
<div id="tabset-2-3">
<p><code>modelsummary()</code> from the <a href="https://modelsummary.com"><code>modelsummary</code></a> package produces a cleaner, publication-ready table — use this in hw9:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">modelsummary</span>(model_biv,</span>
<span id="cb6-2"><a></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span> <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb6-3"><a></a>                             <span class="st">"prestg80"</span>    <span class="ot">=</span> <span class="st">"Prestige Score"</span>),</span>
<span id="cb6-4"><a></a>             <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-5"><a></a>             <span class="at">title   =</span> <span class="st">"OLS: Household Income ~ Occupational Prestige"</span>,</span>
<span id="cb6-6"><a></a>             <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>, <span class="st">"adj.r.squared"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>OLS: Household Income ~ Occupational Prestige</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">21273.309***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(2134.090)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prestige Score</td>
<td style="text-align: center;">472.133***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(45.943)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2527</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.040</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.040</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<div id="tabset-2-4">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What each row means:</strong></p>
</div>
<div class="callout-content">
<p><strong><code>Intercept</code>:</strong> Predicted income when prestige = 0. Not substantively meaningful for prestige (no one has a prestige score of 0) — just the mathematical anchor for the line.</p>
<p><strong><code>Prestige Score</code> (slope):</strong> For each additional point in occupational prestige, household income is predicted to be about <strong>$472 higher</strong>, on average. <strong>This is your key result.</strong></p>
<p><strong>Standard error:</strong> How precisely we’ve estimated the slope. Smaller SE → more confidence.</p>
<p><strong>Stars / p-value:</strong> Is the slope significantly different from zero? Here, <span class="math inline">\(p &lt; 0.001\)</span> — we strongly reject <span class="math inline">\(H_0: \beta = 0\)</span>.</p>
<p><strong>R²:</strong> Occupational prestige explains about <strong>4%</strong> of the variation in household income. Report and interpret this in hw9.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="coefficients-and-hypothesis-tests" class="slide level2 smaller">
<h2>Coefficients and Hypothesis Tests</h2>
<p>Every OLS coefficient has its own built-in hypothesis test:</p>
<p><span class="math display">\[t = \frac{b}{SE(b)}, \quad \text{compared to } t\text{-distribution with } df = n - k - 1\]</span></p>
<div class="fragment fade-up">
<p>This is identical to Week 9’s t-test logic — the only thing new is <em>what</em> we’re testing</p>
</div>
<div class="fragment fade-up">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="co"># Each column has a precise meaning:</span></span>
<span id="cb7-2"><a></a><span class="co">#   Estimate    = the coefficient (b)</span></span>
<span id="cb7-3"><a></a><span class="co">#   Std. Error  = SE(b) — precision of the estimate</span></span>
<span id="cb7-4"><a></a><span class="co">#   t value     = Estimate / Std. Error  ← same t-test from Week 9!</span></span>
<span id="cb7-5"><a></a><span class="co">#   Pr(&gt;|t|)    = two-tailed p-value for H0: beta = 0</span></span>
<span id="cb7-6"><a></a><span class="fu">summary</span>(model_biv)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value                        Pr(&gt;|t|)
(Intercept) 21273.3090 2134.08993  9.968328 0.00000000000000000000005543108
prestg80      472.1334   45.94284 10.276539 0.00000000000000000000000268663</code></pre>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Connection to Week 9:</strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">\(p &lt; 0.05\)</span> for a coefficient, we reject <span class="math inline">\(H_0: \beta = 0\)</span> — evidence that the predictor has a real effect on the outcome. The coefficient tells us the <em>direction</em> and <em>magnitude</em> of that effect; the p-value tells us whether we can trust it isn’t due to chance.</p>
<p><strong>In this example:</strong> <span class="math inline">\(p &lt; 0.001\)</span> for the prestige coefficient, so we <strong>reject</strong> <span class="math inline">\(H_0: \beta_{\text{prestige}} = 0\)</span> — occupational prestige has a statistically significant effect on household income.</p>
</div>
</div>
</div>
</div>
</section>
<section id="interpreting-coefficients" class="slide level2 smaller">
<h2>Interpreting Coefficients</h2>
<p>The estimated regression equation:</p>
<p><span class="math display">\[\widehat{\text{income}} = 21,273  + 472 \times \text{prestige}\]</span></p>
<div class="fragment fade-up">
<p><strong>The slope (<span class="math inline">\(b = 472\)</span>):</strong></p>
<ul>
<li>For every one unit increase in occupational prestige, predicted household income increases by <strong>$472</strong></li>
<li>So, a person who moves from a prestige score of 30 to 60 (+30 points) is predicted to earn <strong>$14160 more</strong> per year</li>
<li>The positive sign confirms a <strong>positive relationship</strong> — higher prestige = higher income</li>
</ul>
</div>
<div class="fragment fade-up">
<p><strong>The intercept (<span class="math inline">\(a = 21,273\)</span>):</strong></p>
<ul>
<li>Predicted income when prestige = 0 is <strong>$21,273</strong> — not really meaningful (prestige scores are well above 0)</li>
<li>This is just a mathematical anchor. We almost never interpret it substantively.</li>
<li>The intercept matters for drawing the line; the <strong>slope</strong> is the theoretically meaningful number.</li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Always report magnitude, not just significance:</strong></p>
</div>
<div class="callout-content">
<p>A p-value tells you whether <span class="math inline">\(b \neq 0\)</span>. <strong>The coefficient itself</strong> tells you how large and meaningful the relationship is. Report both.</p>
</div>
</div>
</div>
</div>
</section>
<section id="what-is-r²" class="slide level2 smaller">
<h2>What Is R²?</h2>
<p><strong>R²</strong> (R-squared) is the <strong>coefficient of determination</strong> — the proportion of variation in the outcome that is explained by the model:</p>
<div class="fragment fade-up">
<p><span class="math display">\[R^2 = \frac{\text{variation in } Y \text{ explained by model}}{\text{total variation in } Y} \in [0, 1]\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>R² value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R² = 0.00</td>
<td>The model explains <em>none</em> of the variation in Y</td>
</tr>
<tr class="even">
<td>R² = 0.04</td>
<td>Prestige explains <strong>~4%</strong> of the variation in income</td>
</tr>
<tr class="odd">
<td>R² = 0.25</td>
<td>The model accounts for 25% of variation — strong for social science</td>
</tr>
<tr class="even">
<td>R² = 1.00</td>
<td>The model perfectly predicts Y (never in real social science data)</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What counts as a “good” R²?</strong></p>
</div>
<div class="callout-content">
<p>It depends entirely on context. In social science, R² of 0.05–0.30 is common and meaningful. A low R² does not mean your predictor is unimportant — it means many other factors also shape the outcome. <strong>Always discuss what R² implies about how much your key predictor explains vs.&nbsp;how much remains unexplained.</strong></p>
</div>
</div>
</div>
</div>
</section>
<section id="visualizing-regression-results" class="slide level2 smaller">
<h2>Visualizing Regression Results</h2>
<p>Two visualizations worth including in hw9:</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Scatter + Regression Line</a></li><li><a href="#tabset-3-2">Coefficient Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>Use <code>geom_smooth(method = "lm")</code> to overlay the regression line on a scatterplot:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">ggplot</span>(attain_reg, <span class="fu">aes</span>(<span class="at">x =</span> prestg80, <span class="at">y =</span> income91)) <span class="sc">+</span></span>
<span id="cb9-2"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">color =</span> <span class="st">"gray50"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-4"><a></a>              <span class="at">color =</span> <span class="st">"#4E79A7"</span>, <span class="at">fill =</span> <span class="st">"#4E79A7"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">dollar_format</span>()) <span class="sc">+</span></span>
<span id="cb9-6"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Effect of Occupational Prestige on Household Income"</span>,</span>
<span id="cb9-7"><a></a>       <span class="at">x =</span> <span class="st">"Occupational Prestige Score"</span>, <span class="at">y =</span> <span class="st">"Household Income ($)"</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-8-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2">
<p><code>modelplot()</code> from <code>modelsummary</code> shows coefficients with 95% confidence intervals. If the CI does not cross 0, the coefficient is significant at <span class="math inline">\(\alpha = 0.05\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">modelplot</span>(model_biv, <span class="at">coef_omit =</span> <span class="st">"Intercept"</span>) <span class="sc">+</span></span>
<span id="cb10-2"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"#E15759"</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"OLS Coefficient: Effect of Prestige on Income"</span>,</span>
<span id="cb10-4"><a></a>       <span class="at">x =</span> <span class="st">"Estimated Coefficient ($ per prestige point)"</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-9-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions-1" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-3-regression-with-categorical-predictors" class="title-slide slide level1 center">
<h1>Part 3: Regression with Categorical Predictors</h1>
<p>When your key predictor has categories</p>
</section>
<section id="categorical-variables-the-challenge" class="slide level2 smaller">
<h2>Categorical Variables: The Challenge</h2>
<p>So far our key predictor has been <strong>continuous</strong> (occupational prestige). What if the key predictor is <strong>categorical</strong> — like educational degree, sex, or race?</p>
<div class="fragment fade-up">
<p><strong>The challenge:</strong> We can’t multiply a category label by a number. Regression needs numbers.</p>
<p><strong>The solution:</strong> Replace a categorical variable with a set of <strong>dummy (indicator) variables</strong> — one for each category except the baseline.</p>
</div>
<div class="fragment fade-up">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-10-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<p><em>We can see groups differ — but how much? And is the difference significant? Regression tells us.</em></p>
</div>
</section>
<section id="dummy-variables-and-baseline-categories" class="slide level2 smaller">
<h2>Dummy Variables and Baseline Categories</h2>
<p>For a categorical variable with <strong>k</strong> categories, we create <strong>k − 1</strong> dummy variables. The omitted category is the <strong>baseline (reference) group</strong> — all comparisons are made against it.</p>
<div class="fragment fade-up">
<p><strong>Example:</strong> Degree (5 categories) → 4 dummies (baseline = <em>lt high</em> [less than high school]):</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 50%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Degree</th>
<th>Dummy variable R creates</th>
<th>Predicted income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>lt high (baseline)</strong></td>
<td><em>(omitted — absorbed into intercept)</em></td>
<td><span class="math inline">\(\alpha\)</span></td>
</tr>
<tr class="even">
<td>High School</td>
<td><code>degree_fhigh sch</code> = 1, all others = 0</td>
<td><span class="math inline">\(\alpha + b_1\)</span></td>
</tr>
<tr class="odd">
<td>Junior College</td>
<td><code>degree_fjunior c</code> = 1, all others = 0</td>
<td><span class="math inline">\(\alpha + b_2\)</span></td>
</tr>
<tr class="even">
<td>Bachelor’s</td>
<td><code>degree_fbachelor</code> = 1, all others = 0</td>
<td><span class="math inline">\(\alpha + b_3\)</span></td>
</tr>
<tr class="odd">
<td>Graduate</td>
<td><code>degree_fgraduate</code> = 1, all others = 0</td>
<td><span class="math inline">\(\alpha + b_4\)</span></td>
</tr>
</tbody>
</table>
<p>Each coefficient (<span class="math inline">\(b_1, b_2, \ldots\)</span>) = predicted income <strong>above or below</strong> the baseline group.</p>
</div>
<div class="fragment fade-up">
<p>The baseline’s predicted income = the <strong>intercept</strong> α. Every other coefficient = income <em>above or below</em> that baseline.</p>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Choosing the baseline:</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Pick the category that makes theoretical sense as a reference point</li>
<li>Common choices: lowest category, largest group, or the “control” condition</li>
<li>In R: <code>fct_relevel(var, "category_name")</code> (from <code>forcats</code>, loaded with <code>tidyverse</code>)</li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="setting-up-categorical-ivs-in-r" class="slide level2 smaller scrollable">
<h2>Setting Up Categorical IVs in R</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Step 1: Check Levels</a></li><li><a href="#tabset-4-2">Step 2: fct_relevel</a></li><li><a href="#tabset-4-3">Step 3: Run + Display</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p>Before setting a baseline, see what categories exist:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="co"># What categories does degree have?</span></span>
<span id="cb11-2"><a></a><span class="fu">table</span>(attain<span class="sc">$</span>degree)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
bachelor graduate high sch junior c  lt high 
     497      216     1586      176      507 </code></pre>
</div>
</div>
<p>The first value alphabetically becomes the default baseline — we usually want to choose explicitly.</p>
</div>
<div id="tabset-4-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>attain_cat <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(degree), <span class="sc">!</span><span class="fu">is.na</span>(income91)) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-4"><a></a>    <span class="co"># Specify all levels in educational order (lowest → highest)</span></span>
<span id="cb13-5"><a></a>    <span class="at">degree_f =</span> <span class="fu">fct_relevel</span>(degree, <span class="st">"lt high"</span>, <span class="st">"high sch"</span>, <span class="st">"junior c"</span>, <span class="st">"bachelor"</span>, <span class="st">"graduate"</span>)</span>
<span id="cb13-6"><a></a>  )</span>
<span id="cb13-7"><a></a></span>
<span id="cb13-8"><a></a><span class="co"># Verify: levels listed in educational order, first = baseline</span></span>
<span id="cb13-9"><a></a><span class="fu">levels</span>(attain_cat<span class="sc">$</span>degree_f)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "lt high"  "high sch" "junior c" "bachelor" "graduate"</code></pre>
</div>
</div>
<p><strong>Choosing the baseline category:</strong></p>
<ul>
<li>Always choose a category that makes <strong>theoretical sense</strong> as a reference point</li>
<li>Common strategy: use the group that represents “no treatment” or the lowest level — e.g., <em>less than high school</em> when testing whether higher degrees predict income</li>
<li>Avoid making the smallest group the baseline — comparisons to a tiny group are imprecise</li>
<li>Example: if your hypothesis is about the <strong>disadvantage of not having a college degree</strong>, set <code>"bachelor"</code> as the baseline so coefficients show penalty for <em>each lower</em> degree level</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Baseline in our example:</strong></p>
</div>
<div class="callout-content">
<p><code>"lt high"</code> (less than high school) is the baseline. Every other coefficient shows how much more income people with that degree earn <em>compared to respondents without a high school diploma</em>.</p>
</div>
</div>
</div>
</div>
<div id="tabset-4-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>model_cat <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> degree_f, <span class="at">data =</span> attain_cat)</span>
<span id="cb15-2"><a></a></span>
<span id="cb15-3"><a></a><span class="fu">modelsummary</span>(model_cat,</span>
<span id="cb15-4"><a></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>        <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb15-5"><a></a>                             <span class="st">"degree_fhigh sch"</span>   <span class="ot">=</span> <span class="st">"High School"</span>,</span>
<span id="cb15-6"><a></a>                             <span class="st">"degree_fjunior c"</span>   <span class="ot">=</span> <span class="st">"Junior College"</span>,</span>
<span id="cb15-7"><a></a>                             <span class="st">"degree_fbachelor"</span>   <span class="ot">=</span> <span class="st">"Bachelor's Degree"</span>,</span>
<span id="cb15-8"><a></a>                             <span class="st">"degree_fgraduate"</span>   <span class="ot">=</span> <span class="st">"Graduate Degree"</span>),</span>
<span id="cb15-9"><a></a>             <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-10"><a></a>             <span class="at">title   =</span> <span class="st">"OLS: Income ~ Degree (baseline = lt high)"</span>,</span>
<span id="cb15-11"><a></a>             <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>OLS: Income ~ Degree (baseline = lt high)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">23181.028***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1765.437)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">High School</td>
<td style="text-align: center;">14360.115***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(2014.784)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Junior College</td>
<td style="text-align: center;">24106.743***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(3357.712)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bachelor's Degree</td>
<td style="text-align: center;">34134.344***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(2459.053)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Graduate Degree</td>
<td style="text-align: center;">40821.525***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(3156.575)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2632</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.099</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="interpreting-categorical-coefficients" class="slide level2 smaller scrollable">
<h2>Interpreting Categorical Coefficients</h2>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">The Equation</a></li><li><a href="#tabset-5-2">How to Read</a></li><li><a href="#tabset-5-3">Predicted Values</a></li><li><a href="#tabset-5-4">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<p>With degree as the key predictor (baseline = <em>lt high</em> [less than HS]):</p>
<p><span class="math display">\[\widehat{\text{income}} = \alpha + b_{\text{hs}} X_{\text{hs}} + b_{\text{jc}} X_{\text{jc}} + b_{\text{ba}} X_{\text{ba}} + b_{\text{grad}} X_{\text{grad}}\]</span></p>
<p>Each <span class="math inline">\(X\)</span> is a <strong>dummy variable</strong> (0/1) for that degree level; each coefficient = the <strong>income difference</strong> relative to the baseline group.</p>
</div>
<div id="tabset-5-2">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading categorical coefficients:</strong></p>
</div>
<div class="callout-content">
<p><strong>Intercept (<span class="math inline">\(\alpha\)</span>):</strong> Predicted income for someone with <em>less than a high school degree</em> (the baseline). This <em>is</em> interpretable — it’s the baseline group’s average income.</p>
<p><strong>Coefficient on <code>High School</code> (<span class="math inline">\(b_{\text{hs}}\)</span>):</strong> On average, having a high school diploma (vs.&nbsp;less than HS) is associated with <strong>$X more</strong> in household income.</p>
<p><strong>Coefficient on <code>Graduate Degree</code> (<span class="math inline">\(b_{\text{grad}}\)</span>):</strong> On average, having a graduate degree (vs.&nbsp;less than HS) is associated with <strong>$Y more</strong> in household income.</p>
<p><strong>Key insight:</strong> Regression with a categorical IV is equivalent to comparing group means — but regression gives us p-values for each comparison and allows us to control for other variables.</p>
</div>
</div>
</div>
</div>
<div id="tabset-5-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="co"># Predicted income for each degree level — ordered lowest to highest</span></span>
<span id="cb16-2"><a></a><span class="fu">tibble</span>(</span>
<span id="cb16-3"><a></a>  <span class="at">Degree   =</span> <span class="fu">c</span>(<span class="st">"Less than HS (baseline)"</span>, <span class="st">"High School"</span>, <span class="st">"Junior College"</span>,</span>
<span id="cb16-4"><a></a>               <span class="st">"Bachelor's Degree"</span>, <span class="st">"Graduate Degree"</span>),</span>
<span id="cb16-5"><a></a>  <span class="at">degree_f =</span> <span class="fu">factor</span>(</span>
<span id="cb16-6"><a></a>    <span class="fu">c</span>(<span class="st">"lt high"</span>, <span class="st">"high sch"</span>, <span class="st">"junior c"</span>, <span class="st">"bachelor"</span>, <span class="st">"graduate"</span>),</span>
<span id="cb16-7"><a></a>    <span class="at">levels =</span> <span class="fu">levels</span>(attain_cat<span class="sc">$</span>degree_f)</span>
<span id="cb16-8"><a></a>  )</span>
<span id="cb16-9"><a></a>) <span class="sc">|&gt;</span></span>
<span id="cb16-10"><a></a>  <span class="fu">mutate</span>(<span class="at">Predicted_Income =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(</span>
<span id="cb16-11"><a></a>    <span class="fu">round</span>(<span class="fu">predict</span>(model_cat, <span class="at">newdata =</span> <span class="fu">pick</span>(degree_f)), <span class="dv">0</span>)</span>
<span id="cb16-12"><a></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb16-13"><a></a>  <span class="fu">select</span>(Degree, Predicted_Income)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Degree                  Predicted_Income
  &lt;chr&gt;                   &lt;chr&gt;           
1 Less than HS (baseline) $23,181         
2 High School             $37,541         
3 Junior College          $47,288         
4 Bachelor's Degree       $57,315         
5 Graduate Degree         $64,003         </code></pre>
</div>
</div>
</div>
<div id="tabset-5-4">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="co"># Rename and reverse order so lowest degree appears at top (matching table above)</span></span>
<span id="cb18-2"><a></a><span class="fu">modelplot</span>(</span>
<span id="cb18-3"><a></a>  model_cat,</span>
<span id="cb18-4"><a></a>  <span class="at">coef_omit =</span> <span class="st">"Intercept"</span>,</span>
<span id="cb18-5"><a></a>  <span class="at">coef_rename =</span> <span class="fu">c</span>(</span>
<span id="cb18-6"><a></a>    <span class="st">"degree_fhigh sch"</span> <span class="ot">=</span> <span class="st">"High School"</span>,</span>
<span id="cb18-7"><a></a>    <span class="st">"degree_fjunior c"</span> <span class="ot">=</span> <span class="st">"Junior College"</span>,</span>
<span id="cb18-8"><a></a>    <span class="st">"degree_fbachelor"</span> <span class="ot">=</span> <span class="st">"Bachelor's Degree"</span>,</span>
<span id="cb18-9"><a></a>    <span class="st">"degree_fgraduate"</span> <span class="ot">=</span> <span class="st">"Graduate Degree"</span></span>
<span id="cb18-10"><a></a>  )</span>
<span id="cb18-11"><a></a>) <span class="sc">+</span></span>
<span id="cb18-12"><a></a>  <span class="fu">scale_y_discrete</span>(<span class="at">limits =</span> rev) <span class="sc">+</span>   <span class="co"># lowest degree (HS) at top</span></span>
<span id="cb18-13"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"#E15759"</span>) <span class="sc">+</span></span>
<span id="cb18-14"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb18-15"><a></a>    <span class="at">title =</span> <span class="st">"Income Gaps by Degree (vs. Less Than HS baseline)"</span>,</span>
<span id="cb18-16"><a></a>    <span class="at">x =</span> <span class="st">"Estimated Income Difference ($)"</span></span>
<span id="cb18-17"><a></a>  ) <span class="sc">+</span></span>
<span id="cb18-18"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-15-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions-2" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-4-ols-assumptions" class="title-slide slide level1 center">
<h1>Part 4: OLS Assumptions</h1>
<p>When can we trust our estimates?</p>
</section>
<section id="the-four-ols-assumptions" class="slide level2 smaller scrollable">
<h2>The Four OLS Assumptions</h2>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">1. Independence</a></li><li><a href="#tabset-6-2">2. Linearity</a></li><li><a href="#tabset-6-3">3. Normal Errors</a></li><li><a href="#tabset-6-4">4. Homoskedasticity</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p><strong>Observations are independent</strong> — typically satisfied by random sampling.</p>
<ul>
<li>Violated when observations are clustered (e.g., students within schools)</li>
<li>Fix: include survey weights or use clustered standard errors</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="co"># If your data have survey weights:</span></span>
<span id="cb19-2"><a></a><span class="fu">lm</span>(outcome <span class="sc">~</span> predictor, <span class="at">data =</span> data, <span class="at">weights =</span> wt_var)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-6-2">
<p><strong>There is a linear relationship</strong> between the continuous IV and the outcome.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-16-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<p><em>Always check this with a scatter plot of Y vs X before running the regression.</em></p>
</div>
<div id="tabset-6-3">
<p><strong>The errors are approximately normally distributed</strong> — most important in small samples. In large samples, violations are usually not a big problem (Central Limit Theorem applies).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-17-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What we did in this class:</strong></p>
</div>
<div class="callout-content">
<p>The raw <code>income91</code> variable is right-skewed (common with income data), which produces non-normal residuals in the bottom-left panel. Running <code>log(income91)</code> as the outcome — <code>model_log</code> above — produces the more symmetric residuals in the bottom-right panel. This is a standard fix: when your outcome is right-skewed, <strong>log-transforming it often corrects the non-normality of errors</strong>.</p>
</div>
</div>
</div>
</div>
<div id="tabset-6-4">
<p><strong>The spread of residuals is constant</strong> across all values of X (equal variance).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-18-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<p><em>Violations bias standard errors — important for t-tests. Fix: robust standard errors.</em></p>
</div>
</div>
</div>
</section>
<section id="checking-assumptions-visually" class="slide level2 smaller">
<h2>Checking Assumptions Visually</h2>
<p>A <strong>residuals vs.&nbsp;fitted plot</strong> diagnoses both linearity and homoskedasticity at once:</p>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week11_files/figure-revealjs/unnamed-chunk-19-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What to look for — and what our model shows:</strong></p>
</div>
<div class="callout-content">
<p><strong>Linearity:</strong> Is the blue loess line approximately flat (horizontal)? <em>In our model: mostly flat with slight curvature — no major concern.</em></p>
<p><strong>Homoskedasticity:</strong> Is the vertical spread of points roughly constant across the x-axis? <em>In our model: the spread is roughly similar across fitted values, though slightly wider at high incomes — common with income data.</em></p>
<p>Overall, our prestige → income model does not show dramatic assumption violations, but some heteroskedasticity is plausible. Using <code>vcov = "HC1"</code> robust SEs (shown next) is a most common precaution used.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="robust-standard-errors" class="slide level2 smaller">
<h2>Robust Standard Errors</h2>
<p>If you suspect heteroskedasticity, use <strong>robust standard errors</strong> — they correct the SEs without changing the coefficient estimates:</p>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">The Problem</a></li><li><a href="#tabset-7-2">In R: modelsummary</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<ul>
<li>Violations of normality and homoskedasticity <strong>do not bias</strong> coefficient estimates (<span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>)</li>
<li>But they <strong>do bias the standard errors</strong> — which affects t-statistics and p-values</li>
<li>Robust SEs account for these violations with a conservative adjustment</li>
</ul>
</div>
<div id="tabset-7-2">
<p>The easiest approach is to compare standard vs.&nbsp;robust SEs side-by-side using <code>modelsummary()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">modelsummary</span>(</span>
<span id="cb20-2"><a></a>  <span class="fu">list</span>(<span class="st">"Standard SEs"</span> <span class="ot">=</span> model_biv, <span class="st">"Robust (HC1) SEs"</span> <span class="ot">=</span> model_biv),</span>
<span id="cb20-3"><a></a>  <span class="at">vcov =</span> <span class="fu">list</span>(<span class="st">"classical"</span>, <span class="st">"HC1"</span>),</span>
<span id="cb20-4"><a></a>  <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span> <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb20-5"><a></a>                  <span class="st">"prestg80"</span>    <span class="ot">=</span> <span class="st">"Prestige Score"</span>),</span>
<span id="cb20-6"><a></a>  <span class="at">stars =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-7"><a></a>  <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>),</span>
<span id="cb20-8"><a></a>  <span class="at">title =</span> <span class="st">"Standard vs. Robust Standard Errors"</span></span>
<span id="cb20-9"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Standard vs. Robust Standard Errors</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Standard SEs</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Robust (HC1) SEs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">21273.309***</td>
<td style="text-align: center;">21273.309***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(2134.090)</td>
<td style="text-align: center;">(1947.377)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prestige Score</td>
<td style="text-align: center;">472.133***</td>
<td style="text-align: center;">472.133***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(45.943)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(44.781)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2527</td>
<td style="text-align: center;">2527</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.040</td>
<td style="text-align: center;">0.040</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="what-do-control-variables-do" class="slide level2 smaller">
<h2>What Do Control Variables Do?</h2>
<p>When we add a control variable to a regression, we are <strong>partitioning the variation</strong> in the outcome:</p>
<div class="fragment fade-up">
<p><strong>Without a control:</strong></p>
<p><span class="math display">\[\text{income} = a + b_1{\text{prestige}} + e\]</span></p>
<p>The coefficient <span class="math inline">\(b_1\)</span> captures <em>all</em> the ways prestige is associated with income — including variation that is really due to sex (because men and women differ in both prestige and income).</p>
</div>
<div class="fragment fade-up">
<p><strong>With a control for sex:</strong></p>
<p><span class="math display">\[\text{income} = a + b_1\text{prestige} + b_2\text{sex} + e\]</span></p>
<p>Now <span class="math inline">\(b_1\)</span> captures the association between prestige and income <em>after filtering out</em> any variation that could be due to sex differences. We are comparing people who are <strong>identical on the control variable</strong> (same sex) and asking: does prestige still predict income?</p>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The key intuition:</strong></p>
</div>
<div class="callout-content">
<p>A control variable “filters away” variation in the outcome that is explained by that control. The coefficient on the key predictor then reflects <strong>only the variation that can’t be explained by the control variables</strong>. This is what “holding constant” means statistically.</p>
</div>
</div>
</div>
</div>
</section>
<section id="multiple-regression" class="slide level2 smaller scrollable">
<h2>Multiple Regression</h2>
<p>We can include multiple predictors — this is <strong>multiple regression</strong>. We’ll cover this in depth in Week 13.</p>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">R Code</a></li><li><a href="#tabset-8-2">Comparing Models</a></li><li><a href="#tabset-8-3">Interpretation</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>attain_multi <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(prestg80), <span class="sc">!</span><span class="fu">is.na</span>(income91), <span class="sc">!</span><span class="fu">is.na</span>(sex)) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a></a>  <span class="fu">mutate</span>(<span class="at">sex_f =</span> <span class="fu">fct_relevel</span>(sex, <span class="st">"male"</span>))</span>
<span id="cb21-4"><a></a></span>
<span id="cb21-5"><a></a>model_biv2   <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> prestg80,          <span class="at">data =</span> attain_multi)</span>
<span id="cb21-6"><a></a>model_multi  <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> prestg80 <span class="sc">+</span> sex_f,   <span class="at">data =</span> attain_multi)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div id="tabset-8-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">modelsummary</span>(</span>
<span id="cb22-2"><a></a>  <span class="fu">list</span>(<span class="st">"Bivariate"</span> <span class="ot">=</span> model_biv2, <span class="st">"Multiple"</span> <span class="ot">=</span> model_multi),</span>
<span id="cb22-3"><a></a>  <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span> <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb22-4"><a></a>                  <span class="st">"prestg80"</span>    <span class="ot">=</span> <span class="st">"Prestige Score"</span>,</span>
<span id="cb22-5"><a></a>                  <span class="st">"sex_ffemale"</span> <span class="ot">=</span> <span class="st">"Female"</span>),</span>
<span id="cb22-6"><a></a>  <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-7"><a></a>  <span class="at">title   =</span> <span class="st">"Prestige and Income: Bivariate vs. Multiple"</span>,</span>
<span id="cb22-8"><a></a>  <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>)</span>
<span id="cb22-9"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Prestige and Income: Bivariate vs. Multiple</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Bivariate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Multiple</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">21273.309***</td>
<td style="text-align: center;">23949.643***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(2134.090)</td>
<td style="text-align: center;">(2295.876)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prestige Score</td>
<td style="text-align: center;">472.133***</td>
<td style="text-align: center;">469.766***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(45.943)</td>
<td style="text-align: center;">(45.869)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−4702.028**</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(1503.645)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2527</td>
<td style="text-align: center;">2527</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.040</td>
<td style="text-align: center;">0.044</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<div id="tabset-8-3">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the multiple regression table:</strong></p>
</div>
<div class="callout-content">
<p><strong>Coefficient on <code>Prestige Score</code> (bivariate → multiple):</strong> $472 → $470 per prestige point. After controlling for sex, the prestige slope changes slightly — this shift tells us how much of the bivariate prestige effect was actually due to sex differences in prestige.</p>
<p><strong>Coefficient on <code>Female</code>:</strong> $-4702 — women earn about $4702 less per year than men <em>at the same prestige level</em>. This is the gender income gap net of occupational status.</p>
<p><strong>R² increase:</strong> 4% (bivariate) → 4.4% (multiple regression). Adding sex explains additional variation in income beyond prestige alone — but most variation in income remains unexplained by these two predictors.</p>
<p><strong>In Week 13</strong>, we’ll cover how to decide which controls to include, and what changes in coefficients across models mean theoretically.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="reading-research-thompson-keith-2001" class="title-slide slide level1 center">
<h1>Reading Research: Thompson &amp; Keith (2001)</h1>
<p>Seeing today’s tools published in a classical sociological study</p>
</section>
<section id="the-blacker-the-berry-overview" class="slide level2 smaller">
<h2>“The Blacker the Berry” — Overview</h2>
<p><strong>Thompson, M.S. &amp; Keith, V.M. (2001).</strong> <em>The Blacker the Berry: Gender, Skin Tone, Self-Esteem, and Self-Efficacy.</em> <strong>Gender &amp; Society, 15</strong>(3), 336–357.</p>
<div class="fragment fade-up">
<p><strong>Research question:</strong> Does skin tone predict psychological well-being — specifically self-esteem and self-efficacy — for Black Americans? And does this relationship differ by gender?</p>
<ul>
<li>Motivated by <strong>colorism</strong>: the documented pattern in which lighter-skinned Black individuals receive preferential treatment in U.S. society</li>
<li>“The blacker the berry, the sweeter the juice” is a common idiom that celebrates dark skin tones in Black individuals — serving as a counter-narrative to colorism. The authors ask whether this affirmation holds for Black Americans’ own self-perception</li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why this paper?</strong></p>
</div>
<div class="callout-content">
<p>This is a model of how to use OLS regression to answer a sociological question. The authors carefully choose their outcome variable, identify a clear key predictor, include theoretically motivated controls, and interpret the substantive meaning of their coefficients.</p>
</div>
</div>
</div>
</div>
</section>
<section id="research-design" class="slide level2 smaller scrollable">
<h2>Research Design</h2>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Data &amp; Sample</a></li><li><a href="#tabset-9-2">Variables</a></li><li><a href="#tabset-9-3">Regression Model</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<ul>
<li><strong>Data:</strong> National Survey of Black Americans (NSBA), 1979–1980</li>
<li><strong>Sample:</strong> 2,107 Black American adults; analyses conducted separately for <strong>men</strong> (n ≈ 581) and <strong>women</strong> (n ≈ 1,035) who are employed</li>
<li><strong>Why separate models?</strong> The authors hypothesize that the relationship between skin tone and self-esteem <em>differs by gender</em>. Running separate regressions for men and women is similar in spirit to including an interaction term (which we’ll cover in Week 13), but the authors chose this approach for simplicity — because they test multiple interactions across several controls, splitting the sample is more tractable than modeling every interaction explicitly</li>
</ul>
</div>
<div id="tabset-9-2">
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Variable</th>
<th>Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Outcome (DV) 1</strong></td>
<td>Self-esteem</td>
<td>Rosenberg 10-item scale (1–4; higher = more positive)</td>
</tr>
<tr class="even">
<td><strong>Outcome (DV) 2</strong></td>
<td>Self-efficacy</td>
<td>Personal efficacy scale (1–4; higher = more control)</td>
</tr>
<tr class="odd">
<td><strong>Key predictor</strong></td>
<td>Skin tone</td>
<td>Interviewer-rated 5-point scale: 1 = very dark to 5 = very light brown</td>
</tr>
<tr class="even">
<td><strong>Controls</strong></td>
<td>Education, income, employment, age, marital status, family origin</td>
<td>Standard socioeconomic controls</td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Self-esteem vs.&nbsp;self-efficacy — what’s the difference?</strong></p>
</div>
<div class="callout-content">
<p><strong>Self-esteem</strong> is a person’s overall sense of their own value or worth — <em>“Do I feel good about myself?”</em> It reflects how positively someone regards themselves as a person.</p>
<p><strong>Self-efficacy</strong> is a person’s belief in their ability to control outcomes in their own life — <em>“Can I make things happen?”</em> It reflects how much agency or personal power someone feels they have.</p>
<p>These are related but distinct psychological constructs. The authors study both because colorism may affect not just how you feel about yourself (self-esteem) but also your sense of whether your efforts can shape your future (self-efficacy).</p>
</div>
</div>
</div>
</div>
<div id="tabset-9-3">
<p>The authors estimate (separately for men and women):</p>
<p><span class="math display">\[\widehat{\text{self-esteem}} = \alpha + \beta_1\text{skin tone} + \beta_2\text{educ} + \beta_3\text{income} + \cdots + e\]</span></p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Connecting to today:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Outcome variable:</strong> self-esteem or self-efficacy (continuous DV)</li>
<li><strong>Key predictor:</strong> skin tone (treated as continuous — 5-point scale)</li>
<li><strong>Controls:</strong> education, income, age, etc. — “filtered away” so the skin tone coefficient reflects prestige net of SES differences</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="key-results" class="slide level2 smaller">
<h2>Key Results</h2>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Table from Paper</a></li><li><a href="#tabset-10-2">For Women</a></li><li><a href="#tabset-10-3">For Men</a></li><li><a href="#tabset-10-4">The Big Finding</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p>Simplified version of Tables 2 &amp; 3 from Thompson &amp; Keith (2001). <strong>Skin tone scale: 1 = very dark, 5 = very light</strong> — a higher score means lighter skin, so a positive coefficient indicates lighter skin → higher outcome.</p>
<table style="font-size:0.85em; width:100%; border-collapse:collapse;">
<thead>
<tr>
<th style="border-bottom:2px solid #888; text-align:left; padding:4px 8px;">
</th>
<th colspan="2" style="background-color:#4E79A7; color:white; text-align:center; padding:4px 8px; border-radius:4px 4px 0 0;">
Women
</th>
<th colspan="2" style="background-color:#F28E2B; color:white; text-align:center; padding:4px 8px; border-radius:4px 4px 0 0;">
Men
</th>
</tr>
<tr>
<th style="border-bottom:1px solid #ccc; text-align:left; padding:4px 8px;">
Variable
</th>
<th style="background-color:#d0e4f5; text-align:center; padding:4px 8px;">
Self-Esteem
</th>
<th style="background-color:#d0e4f5; text-align:center; padding:4px 8px;">
Self-Efficacy
</th>
<th style="background-color:#fde8c8; text-align:center; padding:4px 8px;">
Self-Esteem
</th>
<th style="background-color:#fde8c8; text-align:center; padding:4px 8px;">
Self-Efficacy
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:4px 8px;">
<strong>Skin tone</strong>
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.187*
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.029
</td>
<td style="background-color:#fde8c8; text-align:center;">
.088
</td>
<td style="background-color:#fde8c8; text-align:center;">
.208†
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Education
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.053†
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.127***
</td>
<td style="background-color:#fde8c8; text-align:center;">
.036
</td>
<td style="background-color:#fde8c8; text-align:center;">
.126***
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Income
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.025
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.054***
</td>
<td style="background-color:#fde8c8; text-align:center;">
.019
</td>
<td style="background-color:#fde8c8; text-align:center;">
.014
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Age
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.034***
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.033***
</td>
<td style="background-color:#fde8c8; text-align:center;">
.019**
</td>
<td style="background-color:#fde8c8; text-align:center;">
.030***
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Employed
</td>
<td style="background-color:#d0e4f5; text-align:center;">
.292
</td>
<td style="background-color:#d0e4f5; text-align:center;">
−.093
</td>
<td style="background-color:#fde8c8; text-align:center;">
.449†
</td>
<td style="background-color:#fde8c8; text-align:center;">
−.378
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
N
</td>
<td style="background-color:#d0e4f5; text-align:center;">
1,036
</td>
<td style="background-color:#d0e4f5; text-align:center;">
1,036
</td>
<td style="background-color:#fde8c8; text-align:center;">
647
</td>
<td style="background-color:#fde8c8; text-align:center;">
647
</td>
</tr>
<tr>
<td style="padding:4px 8px; border-top:1px solid #ccc;">
R²
</td>
<td style="background-color:#d0e4f5; text-align:center; border-top:1px solid #ccc;">
.092
</td>
<td style="background-color:#d0e4f5; text-align:center; border-top:1px solid #ccc;">
.096
</td>
<td style="background-color:#fde8c8; text-align:center; border-top:1px solid #ccc;">
.072
</td>
<td style="background-color:#fde8c8; text-align:center; border-top:1px solid #ccc;">
.093
</td>
</tr>
</tbody>
</table>
<p><small>†p ≤ .10. <em>p ≤ .05. <strong>p ≤ .01. </strong></em>p ≤ .001. Coefficients are unstandardized OLS estimates from fully adjusted models (Model 4). Adapted from Thompson &amp; Keith (2001), Tables 2 &amp; 3.</small></p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The key result:</strong></p>
</div>
<div class="callout-content">
<p>Lighter skin tone (higher score) significantly predicts <strong>higher self-esteem for Black women</strong> (.187*), but not for men, and not for self-efficacy once SES is controlled — colorism operates through gender and is outcome-specific.</p>
</div>
</div>
</div>
</div>
<div id="tabset-10-2">
<p>The skin tone coefficient tells a <strong>split story</strong> across the two outcomes:</p>
<ul>
<li><strong>Self-esteem:</strong> coefficient = .187* (<span class="math inline">\(p &lt; 0.05\)</span>) — lighter skin (higher score) → <strong>higher</strong> self-esteem. A Black woman rated 4 (lighter) is predicted to have meaningfully higher self-esteem than a Black woman rated 2 (darker), <em>even after controlling for education, income, and other SES factors</em></li>
<li><strong>Self-efficacy:</strong> coefficient = .029 (not significant) — once SES is controlled, skin tone does <strong>not</strong> significantly predict self-efficacy for women</li>
</ul>
<p><strong>Interpretation:</strong> Colorism shapes how Black women feel about their <em>worth</em> (self-esteem) but not their sense of personal <em>agency</em> (self-efficacy) in the fully adjusted model.</p>
</div>
<div id="tabset-10-3">
<p>The skin tone coefficients are weaker and largely non-significant for men:</p>
<ul>
<li><strong>Self-esteem:</strong> coefficient = .088 (not significant) — skin tone does not predict self-esteem for Black men</li>
<li><strong>Self-efficacy:</strong> coefficient = .208† (<span class="math inline">\(p ≤ .10\)</span>, borderline) — a marginal suggestion that lighter skin is associated with higher self-efficacy, but this falls short of conventional significance</li>
</ul>
<p><strong>Why the difference?</strong> The authors argue that beauty ideals — which prize lighter skin — operate much more strongly as a social evaluation system for women than for men. For men, occupational and economic status matter more than appearance-based judgments.</p>
</div>
<div id="tabset-10-4">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Colorism operates through gender — and is outcome-specific:</strong></p>
</div>
<div class="callout-content">
<p>For Black women, <strong>lighter skin predicts higher self-esteem</strong> (.187*) even after controlling for SES — but skin tone does not significantly predict self-efficacy. For Black men, skin tone has no significant effect on self-esteem, and only a marginal effect on self-efficacy (.208†). This finding demonstrates that colorism is not just about race — it is deeply shaped by gender, and its psychological effects depend on <em>which</em> dimension of self-evaluation we examine.</p>
</div>
</div>
</div>
<p>The <strong>magnitude</strong> matters here: the authors don’t just report that the relationship is significant — they discuss whether the coefficient size is large enough to be practically meaningful. This is exactly the “statistical vs.&nbsp;substantive significance” distinction we covered today.</p>
</div>
</div>
</div>
</section>
<section id="connecting-thompson-keith-to-today" class="slide level2 smaller">
<h2>Connecting Thompson &amp; Keith to Today</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Today’s concept</th>
<th>In Thompson &amp; Keith</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Outcome variable</strong></td>
<td>Self-esteem, self-efficacy</td>
</tr>
<tr class="even">
<td><strong>Key predictor</strong></td>
<td>Skin tone (the main theoretical variable)</td>
</tr>
<tr class="odd">
<td><strong>Control variables</strong></td>
<td>Education, income, age — “filtered away”</td>
</tr>
<tr class="even">
<td><strong>OLS regression</strong></td>
<td><code>lm(selfesteem ~ skintone + educ + income + ...)</code></td>
</tr>
<tr class="odd">
<td><strong>Coefficient interpretation</strong></td>
<td>Each skin tone point → X-unit change in self-esteem</td>
</tr>
<tr class="even">
<td><strong>Statistical vs.&nbsp;substantive significance</strong></td>
<td>Is the effect real AND meaningful?</td>
</tr>
<tr class="odd">
<td><strong>Separate models by group</strong></td>
<td>Week 13 — interaction terms capture this more formally</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>For your research paper:</strong></p>
</div>
<div class="callout-content">
<p>Thompson &amp; Keith is a model for how to write up regression results in a paper. Notice: they state the research question clearly, justify their variable choices, report coefficients with standard errors, discuss magnitude, and connect the statistical results back to the sociological theory.</p>
</div>
</div>
</div>
</section>
<section id="questions-3" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="key-takeaways" class="slide level2 smaller">
<h2>Key Takeaways</h2>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">Part 1 — Variables &amp; OLS</a></li><li><a href="#tabset-11-2">Part 2 — Categorical IVs &amp; Assumptions</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<ul>
<li>The <strong>outcome variable (Y)</strong> is what you are trying to explain — also called the dependent variable</li>
<li>The <strong>key predictor (X)</strong> is the main theoretical variable — also called the key independent variable</li>
<li>OLS estimates the slope (<span class="math inline">\(b\)</span>): average change in outcome per one-unit increase in the predictor</li>
<li>OLS minimizes the sum of squared residuals — that’s where “least squares” comes from</li>
<li>Every coefficient has its own <strong>t-test</strong>: <span class="math inline">\(t = b / SE(b)\)</span>, same logic as Week 9</li>
<li><strong>R²</strong> is the proportion of variation in Y explained by the model — always report and interpret it</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Connection to Week 9:</strong></p>
</div>
<div class="callout-content">
<p>Each regression coefficient has its own null hypothesis (<span class="math inline">\(H_0: \beta = 0\)</span>) and its own t-test and p-value. The inference logic from Week 9 applies directly — the only thing new is the shape of the model.</p>
</div>
</div>
</div>
</div>
<div id="tabset-11-2">
<ul>
<li>Use <code>fct_relevel(var, "baseline")</code> to set the comparison group</li>
<li>Each dummy variable coefficient = difference from the baseline in the outcome variable</li>
<li>The <strong>intercept</strong> = predicted outcome for the baseline group (interpretable!)</li>
<li><strong>Always state your baseline category</strong> when reporting results</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Assumption</th>
<th>How to check</th>
<th>Fix if violated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Independence</td>
<td>Study design</td>
<td>Survey weights, clustered SEs</td>
</tr>
<tr class="even">
<td>Linearity</td>
<td>Scatter plot Y vs X</td>
<td>Transform variables (e.g., log)</td>
</tr>
<tr class="odd">
<td>Normal errors</td>
<td>Histogram of residuals</td>
<td>Usually OK in large samples</td>
</tr>
<tr class="even">
<td>Homoskedasticity</td>
<td>Residuals vs.&nbsp;fitted plot</td>
<td>Robust standard errors (<code>vcov = "HC1"</code>)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="why-this-matters-for-your-research-paper" class="slide level2 smaller scrollable">
<h2>Why This Matters for Your Research Paper</h2>
<ul>
<li><strong>HW #9</strong> asks you to run an OLS regression on your research data — today’s tools are exactly what you need</li>
<li>Your <strong>revised proposal (due 4/16)</strong> should now describe which regression model you plan to use</li>
<li>Your <strong>final paper</strong> will likely use OLS regression as its central analysis</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What HW #9 asks — and what you now know how to do:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Identify your outcome and key predictor</strong> → Part 1 today</li>
<li><strong>Run <code>lm()</code> and display results with <code>modelsummary()</code></strong> → Part 2 today</li>
<li><strong>Set a baseline if using a categorical predictor</strong> → Part 3 today</li>
<li><strong>Interpret the coefficient magnitude, p-value, and R²</strong> → Part 2 today</li>
<li><strong>Visualize</strong> the relationship with a scatter + regression line (continuous IV) or coefficient plot → Part 2 today</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>One thing to add to your thinking for hw9:</strong></p>
</div>
<div class="callout-content">
<p>When interpreting your results, distinguish <strong>statistical significance</strong> (is <span class="math inline">\(p &lt; 0.05\)</span>?) from <strong>substantive significance</strong> (does the size of the coefficient actually matter in the real world?). Both belong in your write-up.</p>
</div>
</div>
</div>
</section>
<section id="questions-4" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="assignments" class="slide level2 smaller scrollable">
<h2>Assignments</h2>
<p><strong>Weekly Assignment #9</strong> — <span class="highlight">Due Thursday, April 9</span></p>
<p>Using your research dataset:</p>
<ol type="1">
<li>State a research question with a <strong>continuous outcome variable</strong> and at least one <strong>key predictor</strong></li>
<li>Write your hypothesis (direction of expected relationship and justification)</li>
<li>Run OLS regression with <code>lm()</code> and display results with <code>modelsummary()</code></li>
<li><strong>If using a categorical predictor</strong>: use <code>fct_relevel(var, "baseline_category")</code> to set a baseline, and state what it is</li>
<li>Interpret the estimated coefficient(s): direction, magnitude, and what they mean</li>
<li>Report and interpret <strong>R²</strong></li>
<li>Visualize: scatter plot with regression line (continuous IV) or coefficient plot</li>
<li>Discuss both <strong>statistical</strong> and <strong>substantive</strong> significance</li>
</ol>
<p><strong>Also due:</strong></p>
<ul>
<li><strong>HW #8</strong> — <span class="highlight">Due Thursday, April 2</span> (hypothesis testing)</li>
<li><strong>Revised Proposal with Outline</strong> — <span class="highlight">Due Thursday, April 16</span></li>
</ul>
<p><strong>In-class lab today:</strong></p>
<ul>
<li>Practice running OLS on your own dataset and interpreting the output</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://www.kaseyzapatka.com/soc106">GitHub course repo</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>