<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-03-10">
  <title>Sociology 106 – Week 8</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="slides.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 8</h1>
  <p class="subtitle">Sociology 106: Quantitative Sociological Methods</p>

<div class="quarto-title-authors">
</div>

  <p class="date">March 10, 2026</p>
</section>
<section id="agenda" class="slide level2 smaller">
<h2>Agenda</h2>
<p><strong>In-class lab:</strong></p>
<ul>
<li>Finish up where we left on last week</li>
</ul>
<p><strong>Housekeeping:</strong></p>
<ul>
<li>Annotated bibliography</li>
<li>Homework #6</li>
<li>Finding academic articles</li>
</ul>
<p><strong>Statistical content — three parts:</strong></p>
<ul>
<li><strong>Part 1</strong>: From sampling to estimation — point estimates, bias, efficiency</li>
<li><strong>Part 2</strong>: Confidence intervals for proportions (z-distribution)</li>
<li><strong>Part 3</strong>: Confidence intervals for means (t-distribution)</li>
</ul>
</section>
<section id="housekeeping" class="slide level2 smaller">
<h2>Housekeeping</h2>
<p><strong>Annotated Bibliography</strong>: <span class="highlight">Due Thursday, March 19</span></p>
<ul>
<li>Example posted on bCourses under the Research Paper folder</li>
<li>Format: <strong>two short paragraphs</strong> per source:
<ol type="1">
<li>Summarize what the source is arguing</li>
<li>Explain how it relates to your research question</li>
</ol></li>
</ul>
<p><strong>Weekly Assignment #7</strong></p>
<ul>
<li><span class="highlight">Due Thursday, March 19</span></li>
<li>Will involve applying confidence intervals from today’s lecture</li>
</ul>
<p><strong>Week 14 lecture:</strong></p>
<ul>
<li>Focus on mediation analysis.</li>
</ul>
</section>
<section id="homework-6-and-paper-proposal" class="slide level2 smaller scrollable">
<h2>Homework #6 and Paper Proposal</h2>
<p><strong>Homework #6:</strong></p>
<ul>
<li>Great job!</li>
<li>Remember to subtract 1 from the lower value when trying to calculate probabilities between.
<ul>
<li>Since <code>pbinom(x) = P(X ≤ x)</code> and includes <code>x</code>, you subtract 1 from the lower bound: <code>pbinom(6) - pbinom(3)</code> gives <code>P(4 ≤ X ≤ 6)</code> because pbinom(3) already includes 3, removing it from the range.</li>
</ul></li>
</ul>
<p><strong>Paper proposal:</strong></p>
<ul>
<li><strong>Walk through specific scenarios to identify mechanisms:</strong> imagine a specific individual and think through their experiences</li>
<li><strong>Research design</strong>: How can you construct variables of interest?</li>
<li><strong>What has already been written in the literature:</strong> some topics have been studied a lot, which is a good! What can you add, what new angle can you take?</li>
<li><strong>Mediation vs moderation</strong>:
<ul>
<li><strong>Mediation:</strong> X causes X, which then causes Y (X &gt; Z &gt; Y)</li>
<li><strong>Moderation:</strong> The effect of X on Y is bigger/smaller/different depending on Z</li>
</ul></li>
</ul>
</section>
<section id="annotated-bibliography" class="slide level2 smaller">
<h2>Annotated Bibliography</h2>
<p><span class="highlight">Due March 19</span></p>
<p>Identify <strong>ten scholarly sources</strong> related to your research question</p>
<p>For each source: in <strong>two short paragraphs</strong>:</p>
<ol type="1">
<li>summarize what the source is arguing</li>
<li>explain how it relates to your research question</li>
</ol>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Good sources</a></li><li><a href="#tabset-1-2">Bad sources</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<ul>
<li>Articles in academic journals</li>
<li>Academic books</li>
<li>Book chapters from edited volumes</li>
<li>Non-political reports from research centers / government agencies</li>
</ul>
</div>
<div id="tabset-1-2">
<ul>
<li>Blogs, internet / newspaper articles</li>
<li>Wikipedia pages</li>
<li>Political reports from research centers / govt</li>
</ul>
</div>
</div>
</div>
<p>Here is a <a href="https://www.kaseyzapatka.com/soc106/assignments/paper/02_bibliography.html">link to an example</a> of one source: you will need 10.</p>
</section>
<section id="strategies-to-find-academic-articles" class="slide level2 smaller">
<h2>Strategies to Find Academic Articles</h2>
<ol type="1">
<li><strong>Search on Google Scholar or JSTOR:</strong> take your independent and dependent variables and searching for:</li>
</ol>
<blockquote>
<p>“effect of <em>independent variable</em> on <em>dependent variable</em>”</p>
</blockquote>
<p>May need to use a <a href="https://search.library.berkeley.edu/discovery/search?vid=01UCS_BER:UCB">UC Berkeley Library proxy</a> to access some academic articles. This is a <a href="https://guides.lib.berkeley.edu/ezproxy/home">helpful webpage</a> for using the proxy server and here is a <a href="https://ucberkeley.libanswers.com/faq/302000">link to make a virtual appointment</a> for research help.</p>
<ol start="2" type="1">
<li>Find one good citation on google scholar and <strong>see who cites them</strong>: see the <code>cited by</code> icon under the citation</li>
<li>Find a relevant article, <strong>mine useful citations</strong> from the literature review</li>
</ol>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Don’t use AI for this:</strong></p>
</div>
<div class="callout-content">
<p>AI will hallucinate citations more often than not, so don’t use it for this. Google Scholar is probably your best bet here!</p>
</div>
</div>
</div>
</section>
<section id="how-to-read-academic-articles" class="slide level2 smaller">
<h2>How to Read Academic Articles</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>What to look for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Abstract</strong></td>
<td>Overview: research question, data, main result — read first</td>
</tr>
<tr class="even">
<td><strong>Introduction</strong></td>
<td>Slightly more detailed than abstract; same format</td>
</tr>
<tr class="odd">
<td><strong>Conclusion</strong></td>
<td>Results, alternative explanations, limitations — and <strong>future research topics</strong></td>
</tr>
<tr class="even">
<td><strong>Background / Lit review</strong></td>
<td>Previous research; a <strong>good source of additional citations</strong></td>
</tr>
<tr class="odd">
<td><strong>Data section</strong></td>
<td>How the sample was constructed; what data sources researchers use</td>
</tr>
<tr class="even">
<td><strong>Methods</strong></td>
<td>Don’t worry about this too much yet!</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Order of operations:</strong></p>
</div>
<div class="callout-content">
<p>Start with abstract → conclusion → introduction. Only go deeper if the paper is clearly relevant.</p>
</div>
</div>
</div>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
</section>
<section>
<section id="part-1-from-sampling-to-estimation" class="title-slide slide level1 center">
<h1>Part 1: From Sampling to Estimation</h1>
<p>Using what we know about sampling distributions to make inferences</p>
</section>
<section id="where-we-are-in-the-course" class="slide level2 smaller">
<h2>Where We Are in the Course</h2>
<ul>
<li><strong>Weeks 5–6:</strong> rules of probability + probability models (Bernoulli, Binomial, Normal)</li>
<li><strong>Week 7:</strong> sampling distributions and the Central Limit Theorem</li>
<li><strong>This week (Week 8):</strong> confidence intervals — using sample data to estimate population parameters</li>
<li><strong>Next week (Week 9):</strong> hypothesis testing</li>
</ul>
<p><strong>Main idea:</strong> Last week, we knew population parameters and built sampling distributions. Today we flip the problem: we use a <em>single sample</em> to make inferences about population parameters we cannot directly observe.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The chain of inference:</strong></p>
</div>
<div class="callout-content">
<p><strong>Week 7:</strong> Population → Sample → Statistic → Sampling distribution</p>
<p><strong>Week 8:</strong> Sample → Statistic → Sampling distribution → Confidence interval → Inference</p>
</div>
</div>
</div>
</section>
<section id="last-week-recap" class="slide level2 smaller">
<h2>Last Week: Recap</h2>
<p><strong>What we learned:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Key idea</th>
<th>Philadelphia example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sampling</strong></td>
<td>A (approximately) random subset of a population</td>
<td>262 police stops recorded</td>
</tr>
<tr class="even">
<td><strong>Sampling distributions</strong></td>
<td>How a statistic varies across repeated samples</td>
<td>Distribution of <span class="math inline">\(\hat{p}\)</span> if stops were random</td>
</tr>
<tr class="odd">
<td><strong>CLT</strong></td>
<td>For large <span class="math inline">\(n\)</span>, sample means are approximately Normal</td>
<td>Even skewed distributions → Normal sample mean</td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The key from last week:</strong></p>
</div>
<div class="callout-content">
<p>We could construct sampling distributions because we <strong>knew</strong> the population parameters (<span class="math inline">\(\pi = 0.422\)</span>, <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma\)</span>). Today we drop that assumption — in the real world, we almost never know these.</p>
</div>
</div>
</div>
</section>
<section id="flipping-the-problem" class="slide level2 smaller">
<h2>Flipping the Problem</h2>
<p><strong>Last week</strong>: Known population parameters → Build a sampling distribution</p>
<p><span class="math display">\[\text{If } \pi = 0.422 \text{ and } n = 262, \text{ then } \hat{p} \sim N\!\left(0.422,\, 0.030\right)\]</span></p>
<div class="fragment fade-up">
<p><strong>This week</strong>: Observed sample data → Estimate unknown population parameters</p>
<p><span class="math display">\[\text{We observe } \hat{p} = 0.449 \text{ from } n = 1154 \;\longrightarrow\; \text{what can we say about } \pi?\]</span></p>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The fundamental shift:</strong></p>
</div>
<div class="callout-content">
<p>We stop pretending we know the population. Instead, we use a sample statistic to construct a <strong>range of plausible values</strong> for the parameter — a <strong>confidence interval</strong>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="key-concepts" class="slide level2 smaller">
<h2>Key Concepts</h2>
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Population</strong></th>
<th><strong>Sample</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Concept</strong></td>
<td>The whole universe a study aspires to generalize to</td>
<td>The subset of the population we actually observe</td>
</tr>
<tr class="even">
<td><strong>Quantity</strong></td>
<td><strong>Parameter</strong> — a number describing the population (usually unknown)</td>
<td><strong>Statistic</strong> — a number computed from the data</td>
</tr>
<tr class="odd">
<td><strong>Notation</strong></td>
<td><span class="math inline">\(\mu\)</span> (mean), <span class="math inline">\(\pi\)</span> (proportion), <span class="math inline">\(\sigma\)</span> (std dev)</td>
<td><span class="math inline">\(\bar{x}\)</span> (mean), <span class="math inline">\(\hat{p}\)</span> (proportion), <span class="math inline">\(s\)</span> (std dev)</td>
</tr>
<tr class="even">
<td><strong>Example</strong></td>
<td>True proportion of Americans supporting env. protection: <span class="math inline">\(\pi = ?\)</span></td>
<td>GSS sample proportion: <span class="math inline">\(\hat{p} = 0.449\)</span></td>
</tr>
</tbody>
</table>
<p><br> <span class="highlight"><strong>The goal of statistical inference</strong></span>: use a sample <em>statistic</em> to learn about a population <em>parameter</em></p>
</section>
<section id="estimators" class="slide level2 smaller">
<h2>Estimators</h2>
<p>An <strong>estimator</strong> is a rule for making inferences about a population parameter using sample data. The value of an estimator is called an <strong>estimate</strong>.</p>
<div class="fragment fade-up">
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Point Estimators</a></li><li><a href="#tabset-2-2">Interval Estimators</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>A <strong>point estimator</strong> gives a <em>single value</em> as our best guess for the population parameter</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Sample statistic</th>
<th>Estimates</th>
<th>Population parameter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample mean <span class="math inline">\(\bar{x}\)</span></td>
<td>→</td>
<td>Population mean <span class="math inline">\(\mu\)</span></td>
</tr>
<tr class="even">
<td>Sample proportion <span class="math inline">\(\hat{p}\)</span></td>
<td>→</td>
<td>Population proportion <span class="math inline">\(\pi\)</span></td>
</tr>
<tr class="odd">
<td>Sample std dev <span class="math inline">\(s\)</span></td>
<td>→</td>
<td>Population std dev <span class="math inline">\(\sigma\)</span></td>
</tr>
<tr class="even">
<td>Regression coefficient <span class="math inline">\(\hat{\beta}\)</span></td>
<td>→</td>
<td>Population coefficient <span class="math inline">\(\beta\)</span></td>
</tr>
</tbody>
</table>
<p>(We’ll use <span class="math inline">\(\hat{\beta}\)</span> in weeks 11–13 — but it works exactly the same way)</p>
</div>
<div id="tabset-2-2">
<p>An <strong>interval estimator</strong> gives a <em>range of values</em> predicted to contain the parameter</p>
<ul>
<li>The <strong>confidence level</strong> is the probability that the interval contains the true parameter</li>
<li>Most common: <strong>95%</strong> — wider intervals are more confident; narrower intervals are more precise</li>
</ul>
<p><strong>Example:</strong> A 95% CI for <span class="math inline">\(\pi\)</span> based on <span class="math inline">\(\hat{p} = 0.449\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="properties-of-point-estimators" class="slide level2 smaller">
<h2>Properties of Point Estimators</h2>
<p>A point estimator has two important properties:</p>
<div class="fragment fade-up">
<p><strong>1. Bias</strong>: The difference between the expected value of the estimator and the population parameter</p>
<ul>
<li>The estimator is <strong>unbiased</strong> if the difference is zero</li>
<li>In a single sample, lack of bias = <strong>accuracy</strong> (hitting the target on average)</li>
</ul>
</div>
<div class="fragment fade-up">
<p><strong>2. Efficiency</strong>: The sampling variability of the estimator</p>
<ul>
<li>An estimator is <strong>efficient</strong> if its sampling variability (spread) is lowest among alternatives</li>
<li>In a single sample, efficiency = <strong>precision</strong> (tight clustering of estimates)</li>
</ul>
</div>
</section>
<section id="visualizing-bias-and-efficiency" class="slide level2 smaller">
<h2>Visualizing Bias and Efficiency</h2>

<img data-src="images/week8/bias_vs_accuracy.png" style="width:100.0%" class="r-stretch quarto-figure-center"><p class="caption">Remember: bias relates to accuracy, efficiency relates to precision</p></section></section>
<section>
<section id="part-2-confidence-intervals-for-proportions" class="title-slide slide level1 center">
<h1>Part 2: Confidence Intervals for Proportions</h1>
<p>From point estimates to ranges of plausible values</p>
</section>
<section id="confidence-intervals-the-big-idea" class="slide level2 smaller">
<h2>Confidence Intervals: The Big Idea</h2>
<p>To construct a <strong>confidence interval</strong>, we use the sampling distribution of the point estimator.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The logic:</strong></p>
</div>
<div class="callout-content">
<p>The sampling distribution tells us <em>how far</em> a statistic is likely to fall from the true parameter. We reverse this: given where our <em>statistic</em> fell, how far is the true parameter likely to be?</p>
</div>
</div>
</div>
<p><strong>Key ingredients:</strong></p>
<ol type="1">
<li>A <strong>point estimate</strong>: our best single guess (e.g., <span class="math inline">\(\hat{p}\)</span>)</li>
<li>A <strong>standard error</strong>: how uncertain is that estimate <span class="math inline">\((SE(\hat{p}))\)</span> ?</li>
<li>A <strong>critical value</strong> (<span class="math inline">\(z^*\)</span>): how many SEs do we need to cover 95% of outcomes?</li>
</ol>
<p><span class="math display">\[\text{Confidence Interval} = \underbrace{\hat{p}}_{\text{point estimate}} \pm \underbrace{z^* \times SE(\hat{p})}_{\text{margin of error}}\]</span></p>
</section>
<section id="confidence-level-and-margin-of-error" class="slide level2 smaller">
<h2>Confidence Level and Margin of Error</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Confidence Level</a></li><li><a href="#tabset-3-2">Margin of Error</a></li><li><a href="#tabset-3-3">CI Formula</a></li><li><a href="#tabset-3-4">Common <span class="math inline">\(z^*\)</span> Values</a></li><li><a href="#tabset-3-5">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p><strong>The confidence level</strong> is the probability that a confidence interval contains the true population parameter</p>
<ul>
<li>Most common: <strong>95%</strong> — if we repeated this study 100 times, 95 of our intervals would contain the true <span class="math inline">\(\pi\)</span></li>
<li>Also used: 90%, 99%, 99.9%</li>
</ul>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Common misconception:</strong></p>
</div>
<div class="callout-content">
<p>It is tempting to say “there’s a 95% chance the true value is in this interval” — but this is wrong. The true parameter <span class="math inline">\(\pi\)</span> is a fixed (unknown) number; it doesn’t have a probability of being anywhere. <strong>Rather</strong>, it is the <em>interval itself</em> that varies from sample to sample.</p>
<p><strong>The correct interpretation:</strong> if we repeated this study 100 times and built a CI each time, 95 of those intervals would contain the true <span class="math inline">\(\pi\)</span>. Any single interval either contains it or doesn’t.</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-2">
<p><strong>The margin of error</strong> is how far the CI extends in each direction from the point estimate:</p>
<p><span class="math display">\[\text{Margin of Error} = z^* \times SE(\hat{p})\]</span></p>
<ul>
<li>Expressed as <span class="math inline">\(\pm\)</span> around the point estimate</li>
<li><strong>Example from the news</strong>: Candidate A is expected to receive <strong>41% ± 3%</strong> of the vote — the margin of error is ±3 percentage points</li>
</ul>
</div>
<div id="tabset-3-3">
<p><span class="math display">\[\hat{p} \pm \underbrace{z^* \times SE(\hat{p})}_{\text{margin of error}} = \left[\hat{p} - z^* \cdot SE,\;\; \hat{p} + z^* \cdot SE\right]\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Piece</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat{p}\)</span></td>
<td>Point estimate — center of the interval</td>
</tr>
<tr class="even">
<td><span class="math inline">\(z^*\)</span></td>
<td>Critical value — from the standard Normal for our confidence level</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(SE(\hat{p})\)</span></td>
<td>Standard error — how uncertain is <span class="math inline">\(\hat{p}\)</span>?</td>
</tr>
<tr class="even">
<td><span class="math inline">\(z^* \times SE\)</span></td>
<td>Margin of error — how wide is each side?</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-3-4">
<p>The critical value <span class="math inline">\(z^*\)</span> depends on the confidence level. These are the ones you’ll use most often:</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Confidence level</th>
<th><span class="math inline">\(\alpha\)</span> (= 1 − conf.)</th>
<th><span class="math inline">\(\alpha/2\)</span> (each tail)</th>
<th><span class="math inline">\(z^*\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90%</td>
<td>0.10</td>
<td>0.05</td>
<td><strong>1.645</strong></td>
</tr>
<tr class="even">
<td>95%</td>
<td>0.05</td>
<td>0.025</td>
<td><strong>1.960</strong></td>
</tr>
<tr class="odd">
<td>97%</td>
<td>0.03</td>
<td>0.015</td>
<td><strong>2.170</strong></td>
</tr>
<tr class="even">
<td>99%</td>
<td>0.01</td>
<td>0.005</td>
<td><strong>2.576</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why 1.96 for 95%?</strong></p>
</div>
<div class="callout-content">
<p>A 95% CI leaves 5% outside the interval — split equally as 2.5% in each tail. The z-score that cuts off the upper 2.5% of the standard Normal is exactly 1.96.</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-5">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="ci-interactive-demo" class="slide level2" data-background-iframe="https://seeing-theory.brown.edu/frequentist-inference/index.html#section2" data-background-interactive="true">
<h2>CI: Interactive Demo</h2>
</section>
<section id="confidence-interval-for-a-proportion" class="slide level2 smaller scrollable">
<h2>Confidence Interval for a Proportion</h2>
<p>The sample proportion <span class="math inline">\(\hat{p}\)</span> is an <strong>unbiased estimator</strong> of the population proportion <span class="math inline">\(\pi\)</span></p>
<p>The exact standard error is <span class="math inline">\(\sqrt{\frac{\pi(1-\pi)}{n}}\)</span> — but we don’t know <span class="math inline">\(\pi\)</span>, so we estimate it:</p>
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p><strong>The 95% confidence interval formula:</strong></p>
<p><span class="math display">\[\hat{p} \pm \underbrace{z^*}_{=\,1.96} \times SE(\hat{p}) = \hat{p} \pm 1.96 \times \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p>Here <span class="math inline">\(z^* = 1.96\)</span> is the <strong>critical value for a 95% confidence interval</strong> — the z-score that cuts off 2.5% in each tail of the standard Normal. (See the “Common <span class="math inline">\(z^*\)</span> Values” tab from the previous slide for other levels.)</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>When can we use this?</strong></p>
</div>
<div class="callout-content">
<p>We need at least <strong>15 successes and 15 failures</strong> for the Normal approximation to be valid. For <span class="math inline">\(n = 1154, \hat{p} = 0.449\)</span>: we have 518 successes and 636 failures — both well above 15. ✓</p>
</div>
</div>
</div>
</section>
<section id="your-turn" class="slide level2 smaller">
<h2>Your Turn</h2>
<p>A campus poll finds <strong>74 of 120 students</strong> support extending library hours.</p>
<p><strong>Calculate the 95% confidence interval for the true proportion of students in favor.</strong></p>
<div class="fragment fade-up">
<p><strong>Step 1 — What is the sample proportion <span class="math inline">\(\hat{p}\)</span>?</strong></p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[\hat{p} = \frac{74}{120} = 0.617\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Step 2 — What is the standard error <span class="math inline">\(SE(\hat{p})\)</span>?</strong></p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{0.617 \times 0.383}{120}} = \sqrt{0.00197} = 0.044\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Step 3 — What is the 95% CI?</strong> (<span class="math inline">\(z^* = 1.96\)</span>)</p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[0.617 \pm 1.96 \times 0.044 = 0.617 \pm 0.086 = [0.531,\; 0.703]\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Interpretation</strong>: We are 95% confident that between 53.1% and 70.3% of students support extending library hours.</p>
</div>
</section>
<section id="worked-example-gss-environmental-survey" class="slide level2 smaller scrollable">
<h2>Worked Example: GSS Environmental Survey</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Setup</a></li><li><a href="#tabset-4-2">95% CI</a></li><li><a href="#tabset-4-3">99% CI</a></li><li><a href="#tabset-4-4">Comparing CIs</a></li><li><a href="#tabset-4-5">Interpretation</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p><strong>Research Question:</strong> In 2000, the GSS asked adult Americans: <em>“Are you willing to pay much higher prices in order to protect the environment?”</em></p>
<ul>
<li><strong>518</strong> said yes; <strong>636</strong> said no → total <span class="math inline">\(n = 1154\)</span></li>
</ul>
<p><strong>Goal:</strong> Estimate the 95% confidence interval for the proportion of adult Americans willing to pay higher prices to protect the environment (ignoring sample weights for now)</p>
</div>
<div id="tabset-4-2">
<div class="fragment fade-up">
<p><strong>Step 1</strong> — Sample proportion:</p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[\hat{p} = \frac{518}{1154} = 0.449\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Step 2</strong> — Standard error:</p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{0.449 \times 0.551}{1154}} = 0.0146\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Step 3</strong> — 95% CI (<span class="math inline">\(z^* = 1.96\)</span>):</p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[0.449 \pm 1.96 \times 0.0146 = 0.449 \pm 0.029 = [0.420, 0.478]\]</span></p>
</div>
</div>
<div id="tabset-4-3">
<p>Same steps, but with <span class="math inline">\(z^* = 2.576\)</span> for 99% confidence:</p>
<div class="fragment fade-up">
<p><strong>Step 1</strong> — Sample proportion:</p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[\hat{p} = \frac{518}{1154} = 0.449\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Step 2</strong> — Standard error:</p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{0.449 \times 0.551}{1154}} = 0.0146\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Step 3</strong> — 99% CI (<span class="math inline">\(z^* = 2.576\)</span>):</p>
</div>
<div class="fragment fade-up">
<p><span class="math display">\[0.449 \pm 2.576 \times 0.0146 = 0.449 \pm 0.038 = [0.411, 0.487]\]</span></p>
</div>
</div>
<div id="tabset-4-4">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>95% CI</th>
<th>99% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Critical value <span class="math inline">\(z^*\)</span></td>
<td>1.96</td>
<td>2.576</td>
</tr>
<tr class="even">
<td>Margin of error</td>
<td>±0.029</td>
<td>±0.038</td>
</tr>
<tr class="odd">
<td>Interval</td>
<td>[0.420, 0.478]</td>
<td>[0.411, 0.487]</td>
</tr>
<tr class="even">
<td>Width</td>
<td>0.058</td>
<td>0.076</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Notice</strong>: The 99% CI is wider — to be more confident our interval contains the true parameter, we must accept more uncertainty about exactly <em>where</em> it falls</p>
</blockquote>
</div>
<div id="tabset-4-5">
<p><strong>Correct interpretation:</strong></p>
<blockquote>
<p>“We are 95% confident that between 42.0% and 47.8% of adult Americans were willing to pay higher prices to protect the environment in 2000.”</p>
</blockquote>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>How to interpret:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Not</strong>: “There is a 95% probability the true value is in this range”</li>
<li><strong>Yes</strong>: “95% of intervals constructed this way would contain the true population proportion”</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="spot-the-error" class="slide level2 smaller">
<h2>Spot the Error</h2>
<p>A newspaper article reports:</p>
<blockquote>
<p><em>“Our poll shows 45% of voters support Measure A, with a margin of error of ±3 percentage points. <strong>There is a 95% probability the true support is between 42% and 48%</strong>.”</em></p>
</blockquote>
<p><strong>What’s wrong with this statement?</strong> <em>(Take 30 seconds, then turn to your neighbor)</em></p>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The error:</strong></p>
</div>
<div class="callout-content">
<p>The article treats the population proportion <span class="math inline">\(\pi\)</span> as if it were a random variable with a 95% chance of landing in a range — but <span class="math inline">\(\pi\)</span> is a fixed (unknown) number. It doesn’t have a probability of being anywhere. <strong>Rather</strong>, it is the <em>interval</em> that is random: if we repeated this poll many times, 95% of the resulting intervals would contain the true <span class="math inline">\(\pi\)</span>. This particular interval either does or doesn’t — we just don’t know which.</p>
<p>The correct statement: <em>“We are 95% confident the true support is between 42% and 48%.”</em></p>
</div>
</div>
</div>
</div>
</section>
<section id="finding-critical-values-in-r" class="slide level2 smaller">
<h2>Finding Critical Values in R</h2>
<p>To build a CI, we need <span class="math inline">\(z^*\)</span> — the number of standard errors to extend in each direction so the interval captures the central X% of the Normal distribution. We find <span class="math inline">\(z^*\)</span> using <code>qnorm()</code>, which returns the z-score that cuts off a given tail probability.</p>
<p><strong>The logic</strong>: for a 95% CI, we want 2.5% in each tail → we ask for the z that satisfies <span class="math inline">\(P(Z &gt; z) = 0.025\)</span>:</p>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">90% CI</a></li><li><a href="#tabset-5-2">95% CI</a></li><li><a href="#tabset-5-3">97% CI</a></li><li><a href="#tabset-5-4">99% CI</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">qnorm</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.90</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># z* = 1.645</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644854</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">qnorm</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># z* = 1.960</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-7-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">qnorm</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.97</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># z* = 2.170</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.17009</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-9-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-4">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">qnorm</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.99</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)  <span class="co"># z* = 2.576</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.575829</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="one-vs.-two-tailed-tests" class="slide level2 smaller">
<h2>One vs.&nbsp;Two-Tailed Tests</h2>
<p>When we test for differences, we can test in one or both directions:</p>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">One-Tailed</a></li><li><a href="#tabset-6-2">Two-Tailed</a></li><li><a href="#tabset-6-3">Visualized</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>A <strong>one-tailed test</strong> checks for a significant effect in one specific direction (greater than <em>or</em> less than)</p>
<ul>
<li>Use when theory predicts the <em>direction</em> of the effect</li>
<li>All 5% significance is concentrated in one tail — easier to reject</li>
</ul>
<p><strong>Example:</strong> Is the proportion of Americans willing to pay for the environment <em>greater than</em> 40%?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="co"># One-tailed: P(Z &gt; z) = 0.05 → critical value</span></span>
<span id="cb9-2"><a></a><span class="fu">qnorm</span>(<span class="fl">0.05</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644854</code></pre>
</div>
</div>
</div>
<div id="tabset-6-2">
<p>A <strong>two-tailed test</strong> looks for any significant difference in <em>either</em> direction</p>
<ul>
<li>Use when theory does not predict the direction</li>
<li>5% significance split equally: 2.5% in each tail — more conservative</li>
<li><strong>More common</strong> in social science research</li>
</ul>
<p><strong>Example:</strong> Is the proportion of Americans willing to pay for the environment <em>different from</em> 40%?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="co"># Two-tailed: P(|Z| &gt; z) = 0.05 → critical value (2.5% in each tail)</span></span>
<span id="cb11-2"><a></a><span class="fu">qnorm</span>(<span class="fl">0.025</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
</div>
<div id="tabset-6-3">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week8/1_vs_2tailed_test.png" class="quarto-figure quarto-figure-center" style="width:55.0%"></p>
</figure>
</div>
<ul>
<li><strong>One-tailed</strong>: rejection region entirely on one side</li>
<li><strong>Two-tailed</strong>: rejection region split equally — requires a larger test statistic to reject</li>
</ul>
</div>
</div>
</div>
</section>
<section id="trade-offs-in-confidence-intervals" class="slide level2 smaller">
<h2>Trade-offs in Confidence Intervals</h2>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Confidence ↑</a></li><li><a href="#tabset-7-2">Sample Size ↑</a></li><li><a href="#tabset-7-3">The Trade-off</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p><strong>As confidence level increases</strong> → margin of error increases</p>
<ul>
<li>More confidence requires a larger <span class="math inline">\(z^*\)</span></li>
<li>Wider interval → we “catch” the parameter more often, but learn less about exactly where it is</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Confidence level</th>
<th><span class="math inline">\(z^*\)</span></th>
<th>Margin of error (GSS example)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90%</td>
<td>1.645</td>
<td>±0.024</td>
</tr>
<tr class="even">
<td>95%</td>
<td>1.960</td>
<td>±0.029</td>
</tr>
<tr class="odd">
<td>99%</td>
<td>2.576</td>
<td>±0.038</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-7-2">
<p><strong>As sample size increases</strong> → margin of error decreases</p>
<p><span class="math display">\[ME = z^* \times \sqrt{\frac{\hat{p}(1-\hat{p})}{n}} \quad \longrightarrow \quad \text{larger } n \Rightarrow \text{ smaller } ME\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sample size <span class="math inline">\(n\)</span></th>
<th>SE</th>
<th>Margin of error (95%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>100</td>
<td>0.050</td>
<td>±0.098</td>
</tr>
<tr class="even">
<td>500</td>
<td>0.022</td>
<td>±0.044</td>
</tr>
<tr class="odd">
<td>1154</td>
<td>0.015</td>
<td>±0.029</td>
</tr>
</tbody>
</table>
<p>Quadrupling the sample size <em>halves</em> the margin of error</p>
</div>
<div id="tabset-7-3">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-14-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions-1" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-3-confidence-intervals-for-means" class="title-slide slide level1 center">
<h1>Part 3: Confidence Intervals for Means</h1>
<p>When we don’t know the population standard deviation</p>
</section>
<section id="from-proportions-to-means" class="slide level2 smaller scrollable">
<h2>From Proportions to Means</h2>
<p><strong>The same logic applies</strong> — but there’s a complication</p>
<p>For <strong>proportions</strong>: <span class="math inline">\(SE(\hat{p}) = \sqrt{\hat{p}(1-\hat{p})/n}\)</span> — we only need <span class="math inline">\(\hat{p}\)</span> (which we have)</p>
<p>For <strong>means</strong>: the true SE is <span class="math inline">\(\sigma/\sqrt{n}\)</span> — but we <strong>don’t know <span class="math inline">\(\sigma\)</span>!</strong></p>
<div class="fragment fade-up">
<p><strong>Solution</strong>: Estimate <span class="math inline">\(\sigma\)</span> with the sample standard deviation <span class="math inline">\(s\)</span>:</p>
<p><span class="math display">\[SE(\bar{x}) = \frac{s}{\sqrt{n}}\]</span></p>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1"><span class="math inline">\(\bar{x}\)</span> — sample mean</a></li><li><a href="#tabset-8-2"><span class="math inline">\(s\)</span> — sample std dev</a></li><li><a href="#tabset-8-3"><span class="math inline">\(n\)</span> — sample size</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<ul>
<li>Our point estimate for <span class="math inline">\(\mu\)</span></li>
<li>The center of our confidence interval</li>
</ul>
</div>
<div id="tabset-8-2">
<p><span class="math display">\[s = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2}\]</span></p>
<ul>
<li>How spread out individual observations are</li>
<li>More variability → more uncertainty → wider interval</li>
</ul>
</div>
<div id="tabset-8-3">
<ul>
<li>Averaging more observations reduces randomness</li>
<li>Larger <span class="math inline">\(n\)</span> → smaller <span class="math inline">\(SE\)</span> → tighter interval</li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="the-t-distribution" class="slide level2 smaller">
<h2>The t-Distribution</h2>
<p><strong>Problem</strong>: Using <span class="math inline">\(s\)</span> instead of <span class="math inline">\(\sigma\)</span> introduces extra uncertainty — especially in small samples</p>
<div class="fragment fade-up">
<p><strong>Solution</strong>: Replace <span class="math inline">\(z^*\)</span> with a slightly larger <strong><span class="math inline">\(t^*\)</span> critical value</strong> from the <strong>t-distribution</strong></p>
</div>
<div class="fragment fade-up">
<p>The t-distribution is:</p>
<ul>
<li>Bell-shaped and symmetric around zero — like the Normal</li>
<li>But with <strong>heavier tails</strong> — more probability in the extremes</li>
<li>Governed by <strong>degrees of freedom</strong>: <span class="math inline">\(df = n - 1\)</span></li>
<li>As <span class="math inline">\(df \to \infty\)</span>, the t-distribution converges to the standard Normal <span class="math inline">\(N(0,1)\)</span></li>
</ul>
</div>
</section>
<section id="properties-of-the-t-distribution" class="slide level2 smaller">
<h2>Properties of the t-Distribution</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Key properties:</strong></p>
<ul>
<li>With small df (small samples): <strong>much fatter tails</strong> than Normal</li>
<li>With df &gt; 100: practically indistinguishable from <span class="math inline">\(N(0,1)\)</span></li>
<li>For small samples, the variable must be approximately Normal in the population</li>
</ul>
<p><strong>Consequence for CIs:</strong></p>
<ul>
<li>The t-critical value <span class="math inline">\(t^*\)</span> is always ≥ <span class="math inline">\(z^*\)</span></li>
<li>Small samples → larger <span class="math inline">\(t^*\)</span> → wider CI (reflecting genuine extra uncertainty)</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week8/t_distribution.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="formula-for-ci-of-a-mean" class="slide level2 smaller">
<h2>Formula for CI of a Mean</h2>
<p>When the population standard deviation is unknown:</p>
<p><span class="math display">\[\bar{x} \pm t^* \times \frac{s}{\sqrt{n}}\]</span></p>
<p>where <span class="math inline">\(t^*\)</span> comes from the <strong>t-distribution with <span class="math inline">\(df = n - 1\)</span></strong></p>
<p><strong>Finding <span class="math inline">\(t^*\)</span> in R:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="co"># General formula</span></span>
<span id="cb13-2"><a></a><span class="fu">qt</span>((<span class="dv">1</span> <span class="sc">-</span> conf_level) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="worked-example-heights" class="slide level2 smaller scrollable">
<h2>Worked Example: Heights</h2>
<p><strong>Study</strong>: 7 American adults from a simple random sample. Average height: 67.2 in, SD: 3.9 in. What is the 95% CI for the average height of all American adults?</p>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Step 1: Inputs</a></li><li><a href="#tabset-9-2">Step 2: Find <span class="math inline">\(t^*\)</span></a></li><li><a href="#tabset-9-3">Step 3: SE</a></li><li><a href="#tabset-9-4">Step 4: CI</a></li><li><a href="#tabset-9-5">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p><strong>Identify the values:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample mean <span class="math inline">\(\bar{x}\)</span></td>
<td>67.2 inches</td>
</tr>
<tr class="even">
<td>Sample std dev <span class="math inline">\(s\)</span></td>
<td>3.9 inches</td>
</tr>
<tr class="odd">
<td>Sample size <span class="math inline">\(n\)</span></td>
<td>7</td>
</tr>
<tr class="even">
<td>Degrees of freedom</td>
<td><span class="math inline">\(df = n - 1 = 6\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-9-2">
<p><strong>Find the critical t-value</strong> for a 95% CI with <span class="math inline">\(df = 6\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">qt</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> <span class="dv">6</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.446912</code></pre>
</div>
</div>
<p>Compare to <span class="math inline">\(z^* = 1.960\)</span> — noticeably larger with a small sample. This is why we use the t-distribution: with only 7 observations, we need a wider interval to achieve true 95% coverage.</p>
</div>
<div id="tabset-9-3">
<p><strong>Calculate the standard error:</strong></p>
<p><span class="math display">\[SE(\bar{x}) = \frac{s}{\sqrt{n}} = \frac{3.9}{\sqrt{7}} = \frac{3.9}{2.646} = 1.474 \text{ inches}\]</span></p>
</div>
<div id="tabset-9-4">
<p><strong>Compute and interpret the confidence interval:</strong></p>
<p><span class="math display">\[\bar{x} \pm t^* \times SE = 67.2 \pm 2.447 \times 1.474 = 67.2 \pm 3.6 = [63.6,\; 70.8]\]</span></p>
<p><strong>Interpretation</strong>: We are 95% confident the average height of all American adults is between 63.6 and 70.8 inches</p>
</div>
<div id="tabset-9-5">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-17-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="comparing-z-and-t" class="slide level2 smaller">
<h2>Comparing <code>z</code> and <code>t</code></h2>
<p>For this small sample (<span class="math inline">\(n = 7\)</span>, <span class="math inline">\(df = 6\)</span>):</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Distribution</th>
<th>Critical value</th>
<th>95% CI</th>
<th>Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>t</strong> (correct)</td>
<td><span class="math inline">\(t^* = 2.447\)</span></td>
<td>[63.6, 70.8]</td>
<td>7.2 in</td>
</tr>
<tr class="even">
<td><strong>z</strong> (incorrect for small <span class="math inline">\(n\)</span>)</td>
<td><span class="math inline">\(z^* = 1.960\)</span></td>
<td>[64.3, 70.1]</td>
<td>5.8 in</td>
</tr>
</tbody>
</table>
<p>The z-based interval is <strong>too narrow</strong> — it would not achieve true 95% coverage. The difference shrinks as <span class="math inline">\(n\)</span> grows.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Rule of thumb:</strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">\(n &gt; 100\)</span>, <span class="math inline">\(t^* \approx z^*\)</span> and the distinction rarely matters in practice.</p>
</div>
</div>
</div>
</section>
<section id="when-to-use-z-vs-t" class="slide level2 smaller scrollable">
<h2>When to use <code>z</code> vs <code>t</code></h2>
<p><strong>The decision starts with what you’re estimating:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Estimating a <strong>proportion</strong></th>
<th>Estimating a <strong>mean</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Use</strong></td>
<td>z-distribution</td>
<td>t-distribution</td>
</tr>
<tr class="even">
<td><strong>Why</strong></td>
<td>SE only depends on <span class="math inline">\(\hat{p}\)</span> — no unknown <span class="math inline">\(\sigma\)</span> to estimate</td>
<td>We estimate <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span>, adding uncertainty the t accounts for</td>
</tr>
<tr class="odd">
<td><strong>Formula</strong></td>
<td><span class="math inline">\(\hat{p} \pm z^* \sqrt{\hat{p}(1-\hat{p})/n}\)</span></td>
<td><span class="math inline">\(\bar{x} \pm t^* (s/\sqrt{n})\)</span></td>
</tr>
<tr class="even">
<td><strong>Critical value</strong></td>
<td><code>qnorm()</code></td>
<td><code>qt(df = n - 1)</code></td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Practical caveat — sample size:</strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">\(n &gt; 100\)</span>, <span class="math inline">\(t^* \approx z^*\)</span> and the distinction rarely matters. But for means, always use <code>qt()</code> — it automatically converges to the Normal for large <span class="math inline">\(n\)</span>.</p>
</div>
</div>
</div>
<p><strong>Finding critical values in R:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="co"># Proportion CI — z* from the Normal</span></span>
<span id="cb16-2"><a></a><span class="fu">qnorm</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="co"># Mean CI (small n = 7, df = 6) — t* noticeably larger than z*</span></span>
<span id="cb18-2"><a></a><span class="fu">qt</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> <span class="dv">6</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.446912</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="co"># Mean CI (large n = 100, df = 99) — t* converges to z*</span></span>
<span id="cb20-2"><a></a><span class="fu">qt</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> <span class="dv">99</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.984217</code></pre>
</div>
</div>
</section>
<section id="using-cis-to-compare-groups" class="slide level2 smaller">
<h2>Using CIs to Compare Groups</h2>
<p>The same CI logic applies separately to <strong>subgroups</strong> — useful when your research question involves comparing populations:</p>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">The Idea</a></li><li><a href="#tabset-10-2">Example</a></li><li><a href="#tabset-10-3">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p>Calculate a CI for each group independently, then compare:</p>
<ul>
<li>If the intervals <strong>do not overlap</strong> → preliminary evidence of a real difference between the group means</li>
<li>If they <strong>do overlap</strong> → the observed difference may just be sampling variability</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Preview of Week 9:</strong></p>
</div>
<div class="callout-content">
<p>This is an informal first look at <strong>hypothesis testing</strong>. Next week we’ll formalize exactly how far apart two groups need to be before we conclude the difference is real.</p>
</div>
</div>
</div>
</div>
<div id="tabset-10-2">
<p><strong>Do childhood and adult arrivals differ in years spent in the U.S.?</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th><span class="math inline">\(n\)</span></th>
<th><span class="math inline">\(\bar{x}\)</span></th>
<th><span class="math inline">\(s\)</span></th>
<th>95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Childhood arrivals (arrived &lt; 18)</td>
<td>20</td>
<td>11.4</td>
<td>3.6</td>
<td>[9.7, 13.1]</td>
</tr>
<tr class="even">
<td>Adult arrivals (arrived ≥ 18)</td>
<td>15</td>
<td>5.2</td>
<td>4.0</td>
<td>[3.0, 7.4]</td>
</tr>
</tbody>
</table>
<p>The intervals <strong>do not overlap</strong> → childhood arrivals have spent meaningfully more time in the U.S.</p>
</div>
<div id="tabset-10-3">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week8_files/figure-revealjs/unnamed-chunk-19-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2 smaller">
<h2>Key Takeaways</h2>
<ul>
<li><strong>Estimation</strong> uses sample statistics to learn about unknown population parameters</li>
<li><strong>Bias</strong> (accuracy) and <strong>efficiency</strong> (precision) are the two properties of good estimators</li>
<li>A <strong>confidence interval</strong> = point estimate ± margin of error</li>
<li>The <strong>margin of error</strong> = critical value × standard error</li>
<li>For <strong>proportions</strong>: use the z-distribution; for <strong>means</strong>: use the t-distribution</li>
<li>Wider intervals = more confidence; narrower intervals = larger sample size</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Key takeaway:</strong></p>
</div>
<div class="callout-content">
<p>Confidence intervals quantify what we know <em>and</em> what we don’t know. A wide interval means we’re uncertain; a narrow interval means our sample was large enough to pin down the parameter closely.</p>
</div>
</div>
</div>
</section>
<section id="why-this-matters-for-the-rest-of-the-course" class="slide level2 smaller">
<h2>Why This Matters for the Rest of the Course</h2>
<ul>
<li><strong>Next week (Week 9):</strong> Hypothesis testing flips the logic again — instead of building an interval, we ask “is our estimate far enough from a specific null value to doubt it?”</li>
<li><strong>Weeks 11–13 (Regression):</strong> Every regression coefficient comes with a confidence interval — built on exactly the t-distribution logic we developed today</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Key takeaway:</strong></p>
</div>
<div class="callout-content">
<p>The tools we built today — standard errors, critical values, confidence intervals — are not just Week 8 material. They are the backbone of every inferential result we’ll encounter for the rest of the course.</p>
</div>
</div>
</div>
</section>
<section id="questions-2" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="assignments" class="slide level2 smaller">
<h2>Assignments</h2>
<p><strong>Weekly Assignment #7</strong></p>
<ul>
<li><span class="highlight">Due Thursday, March 19</span> by 11:59 PM</li>
<li>Using your research project dataset:
<ol type="1">
<li>Calculate a 95% CI for the mean of a proportion (from an indicator variable)</li>
<li>Calculate a 95% CI for the mean of a continuous variable</li>
<li>Calculate a 95% CI for a continuous variable across groups of an indicator variable</li>
</ol></li>
</ul>
<p><strong>Annotated Bibliography</strong></p>
<ul>
<li><span class="highlight">Due Thursday, March 19</span></li>
<li>Finding 10 relevant papers takes time — start early!</li>
<li>Happy to help during office hours</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://www.kaseyzapatka.com/soc106">GitHub course repo</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>