<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-04-07">
  <title>Sociology 106 – Week 12</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="slides.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 12</h1>
  <p class="subtitle">Sociology 106: Quantitative Sociological Methods</p>

<div class="quarto-title-authors">
</div>

  <p class="date">April 7, 2026</p>
</section>
<section id="agenda" class="slide level2 smaller">
<h2>Agenda</h2>
<p><strong>Housekeeping:</strong></p>
<ul>
<li>HW #9, HW #10, Revised Proposal with Outline</li>
</ul>
<p><strong>Statistical content — four parts:</strong></p>
<ul>
<li><strong>Part 1</strong>: Why not OLS? — the limits of linear models for binary outcomes</li>
<li><strong>Part 2</strong>: The logistic regression model — odds, log-odds, and the sigmoid function</li>
<li><strong>Part 3</strong>: Interpreting logistic regression — log-odds, odds ratios, and <code>modelsummary()</code></li>
<li><strong>Part 4</strong>: Predicted probabilities and margins plots — making results intuitive</li>
</ul>
<p><strong>Reading discussion:</strong></p>
<ul>
<li>Freeman &amp; Braconi (2004) — logistic regression in practice</li>
</ul>
<p><strong>In-class lab:</strong></p>
<ul>
<li>Running and interpreting logistic regression on your research data</li>
</ul>
</section>
<section id="housekeeping" class="slide level2 smaller">
<h2>Housekeeping</h2>
<p><strong>Weekly Assignment #8</strong></p>
<ul>
<li><strong>Feedback:</strong> Remember if your confidence interval incldues infinitiy (∞) then you probabally forgot to drop NAs fro your analysis</li>
</ul>
<p><strong>Weekly Assignment #9</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 9</span> — OLS regression from Week 11</li>
<li>Use <code>modelsummary()</code> for a clean table; interpret the slope, R², and statistical significance</li>
</ul>
<p><strong>Weekly Assignment #10</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 16</span></li>
<li>Run a logistic regression on a binary outcome from your research dataset — today’s lecture covers everything you need</li>
<li>Report the odds ratio for your key predictor; compute predicted probabilities at two or more values</li>
</ul>
<p><strong>Revised Proposal with Outline</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 16</span></li>
<li>Should now describe whether your final analysis uses OLS or logistic regression — and why</li>
</ul>
</section>
<section id="where-we-are-in-the-course" class="slide level2 smaller">
<h2>Where We Are in the Course</h2>
<ul>
<li><strong>Week 11:</strong> OLS regression — how <em>strong</em> is the linear relationship?</li>
<li><strong>This week (Week 12):</strong> Logistic regression — predicting <em>binary</em> outcomes</li>
<li><strong>Week 13:</strong> Multiple regression extensions — controlling for confounders</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The big picture: from “how much?” to “what are the odds?”</strong></p>
</div>
<div class="callout-content">
<p>Last week, OLS answered: <em>“For every additional unit of X, how much does Y change on average?”</em> That works when Y is continuous. This week, Y is binary (0/1) — and we need a different tool.</p>
</div>
</div>
</div>
</section>
<section>
<section id="part-1-why-not-ols" class="title-slide slide level1 center">
<h1>Part 1: Why Not OLS?</h1>
<p>When the outcome is 0 or 1</p>
</section>
<section id="recap-what-ols-does" class="slide level2 smaller">
<h2>Recap: What OLS Does</h2>
<p>OLS estimates the <strong>expected value</strong> of Y as a linear function of X:</p>
<p><span class="math display">\[E[Y \mid x] = \alpha + \beta x\]</span></p>
<p>When Y is <strong>continuous</strong> (in <code>attain</code> data: income, prestige, hours worked), this works well:</p>
<ul>
<li><span class="math inline">\(\beta\)</span> is the change in Y per one-unit increase in X</li>
<li>Predicted values are on the same continuous scale as Y</li>
<li>Nothing forces predicted values to stay within any bounds</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Now imagine Y is binary</strong></p>
</div>
<div class="callout-content">
<p>What if Y = 1 (union member) or Y = 0 (not)?</p>
<p>For a binary variable, <span class="math inline">\(E[Y] = P(Y = 1)\)</span>, the <strong>probability</strong> of the outcome.</p>
<p>A probability must be between 0 and 1. But nothing stops OLS from predicting 1.4 or −0.2.</p>
</div>
</div>
</div>
</section>
<section id="the-linear-probability-model" class="slide level2 smaller">
<h2>The Linear Probability Model</h2>
<p>When OLS is applied to a binary (0/1) outcome, the result is called a <strong>linear probability model (LPM)</strong>:</p>
<div class="fragment fade-up">
<p><span class="math display">\[E[Y \mid x] = P(Y = 1 \mid x) = \alpha + \beta x\]</span></p>
<p>The coefficient <span class="math inline">\(\beta\)</span> is interpreted as: <em>a one-unit increase in X is associated with a <span class="math inline">\(\beta\)</span>-unit change in the <strong>probability</strong> that Y = 1.</em></p>
<p>This is appealingly simple and directly interpretable.</p>
</div>
<div class="fragment fade-up">
<p><strong>Our running example:</strong></p>
<ul>
<li><strong>Outcome (Y):</strong> <code>union_member</code> — 1 if respondent (or their spouse) is in a union, 0 otherwise</li>
<li><strong>Key predictor (X):</strong> <code>educ</code> — years of education</li>
<li><strong>Research question:</strong> Does educational attainment predict the probability of union membership?</li>
</ul>
<p>About <strong>8.6%</strong> of respondents in our sample are union members.</p>
</div>
<div class="fragment fade-up">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># OLS on a binary outcome = linear probability model</span></span>
<span id="cb1-2"><a></a>model_lpm <span class="ot">&lt;-</span> <span class="fu">lm</span>(union_member <span class="sc">~</span> educ, <span class="at">data =</span> attain_logit)</span>
<span id="cb1-3"><a></a><span class="fu">coef</span>(model_lpm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        educ 
 0.06198181  0.00180732 </code></pre>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpreting the LPM coefficient</strong></p>
</div>
<div class="callout-content">
<p>Each additional year of education is associated with a <strong>0.18 percentage point increase</strong> in the probability of union membership.</p>
</div>
</div>
</div>
</div>
</section>
<section id="problems-with-the-lpm" class="slide level2 smaller scrollable">
<h2>Problems with the LPM</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">The Data</a></li><li><a href="#tabset-1-2">LPM Problem</a></li><li><a href="#tabset-1-3">The Fix: Logit</a></li><li><a href="#tabset-1-4">Middle Range</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>Binary outcomes look like this — the data are 0s and 1s, but the <em>probability</em> of Y = 1 varies smoothly with X:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week12_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The dashed lines mark the valid probability range: <strong>any model must stay between 0 and 1.</strong></p>
</div>
<div id="tabset-1-2">
<p>The OLS line ignores the 0–1 constraint — it will <strong>extend below 0 and above 1</strong> at extreme values of X:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week12_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Two core problems with LPM:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Predicted probabilities can fall outside [0, 1]</strong> — meaningless (you can’t have a −5% chance)</li>
<li><strong>Constant marginal effects</strong> — a one-unit increase in X always changes probability by the same amount, no matter where you are on the scale. But in reality, an extra year of education matters less for someone already near 0% or 100% probability.</li>
</ol>
</div>
</div>
</div>
</div>
<div id="tabset-1-3">
<p>A <strong>logistic (sigmoid) curve</strong> solves both problems — it naturally stays between 0 and 1, and its slope is steepest at intermediate probabilities and flattens near the extremes:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week12_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-4">
<p>Here’s the key practical insight: <strong>when predicted probabilities are between roughly 0.2 and 0.8, both models give very similar answers.</strong> They only diverge at the extremes.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week12_files/figure-revealjs/unnamed-chunk-6-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="a-note-on-disciplinary-conventions" class="slide level2 smaller">
<h2>A Note on Disciplinary Conventions</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Do sociologists and economists disagree?</strong></p>
</div>
<div class="callout-content">
<p><strong>Yes — and it’s a real debate in empirical social science:</strong></p>
<ul>
<li><p><strong>Economists</strong> routinely use the LPM. Reasons: coefficients are directly interpretable as probability changes (no transformation needed); robust standard errors correct for heteroskedasticity; estimates are consistent. Many economists see logit as unnecessarily complex when probabilities are in the middle range.</p></li>
<li><p><strong>Sociologists</strong> have traditionally preferred logistic regression. Reasons: the sigmoid function better matches the theoretical idea of diminishing returns; avoiding out-of-bounds predictions is conceptually important; it’s the discipline’s standard.</p></li>
</ul>
<p><strong>The practical bottom line:</strong> The two models give nearly identical results unless predicted probabilities approach 0 or 1. Your discipline’s convention matters more than the choice per se — but <em>understanding why logit exists</em> is essential for reading and evaluating quantitative research in sociology.</p>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>For this course:</strong></p>
</div>
<div class="callout-content">
<p>We use logistic regression as our standard for binary outcomes — both because it is the sociological convention and because it’s harder of the two options – you can always do the easier one.</p>
</div>
</div>
</div>
</div>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-2-the-logistic-regression-model" class="title-slide slide level1 center">
<h1>Part 2: The Logistic Regression Model</h1>
<p>Odds, log-odds, and the sigmoid</p>
</section>
<section id="from-probabilities-to-odds" class="slide level2 smaller">
<h2>From Probabilities to Odds</h2>
<p>To build logistic regression, we first transform the outcome:</p>
<div class="fragment fade-up">
<p><strong>Step 1: Probability → Odds</strong></p>
<p><span class="math display">\[\text{Probability} = \frac{P(Y = 1)}{P(Y = 0)} = \text{Odds} = \frac{P(Y = 1)}{1 - P(Y = 1)}\]</span></p>
<ul>
<li>Odds &gt; 1: event is <strong>more likely</strong> to happen than not</li>
<li>Odds = 1: event equally likely to happen or not</li>
<li>Odds &lt; 1: event is <strong>less likely</strong> to happen than not</li>
</ul>
<p><em>Example:</em> If 25% of workers are union members, the odds are <span class="math inline">\(0.25 / 0.75 = 0.33\)</span></p>
<p>However, odds give us a number that ranges from <span class="math inline">\(0\)</span> to <span class="math inline">\(+\infty\)</span> — which is not linear and unbounded in one direction – this is not ideal for estimation!</p>
</div>
<div class="fragment fade-up">
<p><strong>Step 2: Odds → Log-odds (Logit)</strong></p>
<p><span class="math display">\[\text{logit}(p) = \log\!\left(\frac{p}{1-p}\right)\]</span></p>
<p>Taking the log of the odds gives us a number that ranges from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span> — now we can use a linear model!</p>
</div>
<div class="fragment fade-up">
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Probability <span class="math inline">\(P(Y=1)\)</span></th>
<th>Odds Ratio <span class="math inline">\(\frac{P}{1-P}\)</span></th>
<th>Log-odds <span class="math inline">\(\log\!\left(\frac{P}{1-P}\right)\)</span></th>
<th>Plain reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.10</td>
<td>0.11</td>
<td>−2.20</td>
<td>9× more likely <em>not</em> to happen</td>
</tr>
<tr class="even">
<td>0.25</td>
<td>0.33</td>
<td>−1.10</td>
<td>3× more likely <em>not</em> to happen</td>
</tr>
<tr class="odd">
<td>0.50</td>
<td>1.00</td>
<td>0.00</td>
<td>equally likely either way</td>
</tr>
<tr class="even">
<td>0.75</td>
<td>3.00</td>
<td>+1.10</td>
<td>3× more likely <em>to</em> happen</td>
</tr>
<tr class="odd">
<td>0.90</td>
<td>9.00</td>
<td>+2.20</td>
<td>9× more likely <em>to</em> happen</td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Odds vs.&nbsp;Odds Ratios — not the same thing!</strong></p>
</div>
<div class="callout-content">
<p>The table above shows the odds ratio (the ratio <span class="math inline">\(P/(1-P)\)</span> for one group or one value of X). An <strong>odds ratio</strong> compares the odds from two groups — it is the <em>ratio of two odds</em>: <span class="math inline">\(OR = \text{Odds}_{\text{group A}} / \text{Odds}_{\text{group B}}\)</span>. Log-odds is simply <span class="math inline">\(\log(\text{Odds})\)</span>, which is the defaul output of the logistic regression model.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-logistic-regression-model" class="slide level2 smaller">
<h2>The Logistic Regression Model</h2>
<p>We model the <strong>log-odds</strong> as a linear function of the predictors:</p>
<p><span class="math display">\[\underbrace{\log\!\left(\frac{P(Y=1)}{P(Y=0)}\right)}_{\text{log-odds (logit)}} = \alpha + \beta x\]</span></p>
<div class="fragment fade-up">
<p>This looks identical to OLS on the <strong>right-hand side</strong> — same <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta x\)</span> structure. Only the <strong>left-hand side</strong> is different: instead of <span class="math inline">\(E[Y]\)</span>, we model the log-odds.</p>
</div>
<div class="fragment fade-up">
<p>Solving for the probability directly gives the <strong>logistic (sigmoid) function</strong>:</p>
<p><span class="math display">\[P(Y = 1 \mid x) = \frac{e^{\alpha + \beta x}}{1 + e^{\alpha + \beta x}}\]</span></p>
<p>This is what produces the S-shaped curve — it mathematically guarantees predictions between 0 and 1.</p>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Estimation: maximum likelihood, not OLS</strong></p>
</div>
<div class="callout-content">
<p>Logistic regression is estimated by <strong>maximum likelihood estimation (MLE)</strong>: we find the values of <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> that make the observed data most probable. When all OLS assumptions hold, MLE and OLS give the same answer for continuous outcomes — but for binary outcomes, MLE is the right approach.</p>
</div>
</div>
</div>
</div>
</section>
<section id="running-logistic-regression-in-r" class="slide level2 smaller scrollable">
<h2>Running Logistic Regression in R</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Syntax</a></li><li><a href="#tabset-2-2"><code>summary()</code> Output</a></li><li><a href="#tabset-2-3"><code>modelsummary()</code></a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>Use <code>glm()</code> (generalized linear model) instead of <code>lm()</code>, with <code>family = binomial</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">glm</span>(outcome <span class="sc">~</span> predictor1 <span class="sc">+</span> predictor2, <span class="at">family =</span> binomial, <span class="at">data =</span> your_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Key difference from <code>lm()</code>:</strong> you must specify <code>family = binomial</code> — this tells R you want logistic regression.</p>
<p><strong>Our example:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="co"># Bivariate logistic regression</span></span>
<span id="cb4-2"><a></a>model_logit_biv <span class="ot">&lt;-</span> <span class="fu">glm</span>(union_member <span class="sc">~</span> educ,</span>
<span id="cb4-3"><a></a>                       <span class="at">family =</span> binomial,</span>
<span id="cb4-4"><a></a>                       <span class="at">data   =</span> attain_logit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The outcome <code>union_member</code> must be <strong>0/1</strong> (or a factor with two levels — R converts it automatically).</p>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">summary</span>(model_logit_biv)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = union_member ~ educ, family = binomial, data = attain_logit)

Coefficients:
            Estimate Std. Error z value            Pr(&gt;|z|)    
(Intercept) -2.67400    0.30255  -8.838 &lt;0.0000000000000002 ***
educ         0.02322    0.02217   1.048               0.295    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1747.0  on 2984  degrees of freedom
Residual deviance: 1745.8  on 2983  degrees of freedom
AIC: 1749.8

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The output looks like OLS — but the coefficients are now <strong>log-odds</strong>, not raw units of Y.</p>
</div>
<div id="tabset-2-3">
<p>Use <code>modelsummary()</code> for a clean table — same package as last week:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">modelsummary</span>(model_logit_biv,</span>
<span id="cb7-2"><a></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span> <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb7-3"><a></a>                             <span class="st">"educ"</span>        <span class="ot">=</span> <span class="st">"Years of Education"</span>),</span>
<span id="cb7-4"><a></a>             <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-5"><a></a>             <span class="at">title   =</span> <span class="st">"Logistic Regression: Union Membership ~ Education"</span>,</span>
<span id="cb7-6"><a></a>             <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"logLik"</span>, <span class="st">"AIC"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_n95434xyr93t7qt2c3c1 = TinyTable.createTableFunctions("tinytable_n95434xyr93t7qt2c3c1");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '6', j: 2 } ], css_id: 'tinytable_css_7r3j09vttyvxvc2cwj3j',}, 
          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_d8zmjj08o1mntm8as14a',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 } ], css_id: 'tinytable_css_k4236ix69vipy2m65oj5',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_jluyfwavil9jl9hxtkrd',}, 
          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_hzwe171bt6iq4tmgh0ci',}, 
          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_vc6dl9pmkr2kivvej3z4',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 } ], css_id: 'tinytable_css_xjpbw0tl5n2b7mfolkaa',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_m4ix312turi4eza1y1qt',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_n95434xyr93t7qt2c3c1.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_7r3j09vttyvxvc2cwj3j, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_7r3j09vttyvxvc2cwj3j {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_d8zmjj08o1mntm8as14a, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_d8zmjj08o1mntm8as14a {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_k4236ix69vipy2m65oj5, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_k4236ix69vipy2m65oj5 { text-align: center }
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_jluyfwavil9jl9hxtkrd, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_jluyfwavil9jl9hxtkrd {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_hzwe171bt6iq4tmgh0ci, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_hzwe171bt6iq4tmgh0ci {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_vc6dl9pmkr2kivvej3z4, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_vc6dl9pmkr2kivvej3z4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_xjpbw0tl5n2b7mfolkaa, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_xjpbw0tl5n2b7mfolkaa { text-align: left }
    #tinytable_n95434xyr93t7qt2c3c1 td.tinytable_css_m4ix312turi4eza1y1qt, #tinytable_n95434xyr93t7qt2c3c1 th.tinytable_css_m4ix312turi4eza1y1qt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_n95434xyr93t7qt2c3c1" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <caption>Logistic Regression: Union Membership ~ Education</caption>
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Intercept</td>
                  <td data-row="1" data-col="2">-2.674***</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.303)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Years of Education</td>
                  <td data-row="3" data-col="2">0.023</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.022)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Num.Obs.</td>
                  <td data-row="5" data-col="2">2985</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1">Log.Lik.</td>
                  <td data-row="6" data-col="2">-872.925</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note on model fit</strong></p>
</div>
<div class="callout-content">
<p>Logistic regression reports <strong>log-likelihood</strong> and <strong>AIC</strong> instead of R². We’ll interpret these as relative model fit metrics (lower AIC = better fit), but they are harder to communicate as percentages. We’ll rely on predicted probabilities to communicate effect sizes substantively.</p>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpreting the output</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Intercept (-2.674):</strong> the predicted log-odds of union membership when education = 0 — not substantively meaningful on its own</li>
<li><strong>Years of Education (0.023):</strong> for each additional year of education, the <strong>log-odds</strong> of union membership change by 0.023 — the negative sign means more education is associated with <em>lower</em> odds of union membership</li>
<li><strong>The p-value</strong> on education tells us whether this association is statistically distinguishable from zero — same logic as OLS</li>
</ul>
<p>Log-odds are hard to interpret directly. In the next section we convert them to <strong>odds ratios</strong> and <strong>predicted probabilities</strong>, which are much more communicable.</p>
</div>
</div>
</div>
</div>
</section>
<section id="assumptions-of-logistic-regression" class="slide level2 smaller">
<h2>Assumptions of Logistic Regression</h2>
<p>The assumptions are similar to OLS but slightly less demanding:</p>
<div class="fragment fade-up">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Assumption</th>
<th>What it means</th>
<th>How to check</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Linearity (in log-odds)</strong></td>
<td>The log-odds of Y is a linear function of each continuous IV</td>
<td>Plot log-odds against IV; Box-Tidwell test</td>
</tr>
<tr class="even">
<td><strong>Independence</strong></td>
<td>Observations are independent (not clustered)</td>
<td>Study design</td>
</tr>
<tr class="odd">
<td><strong>No perfect separation</strong></td>
<td>No value of X perfectly predicts Y = 0 or Y = 1</td>
<td>Model convergence warning in R</td>
</tr>
<tr class="even">
<td><strong>Large enough n</strong></td>
<td>Rule of thumb: ≥ 10 events per predictor</td>
<td>Count: <code>sum(outcome == 1)</code></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="questions-1" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-3-interpreting-logistic-regression" class="title-slide slide level1 center">
<h1>Part 3: Interpreting Logistic Regression</h1>
<p>From log-odds to odds ratios</p>
</section>
<section id="reading-log-odds-coefficients" class="slide level2 smaller">
<h2>Reading Log-Odds Coefficients</h2>
<p>The coefficient <span class="math inline">\(\beta\)</span> in logistic regression is the <strong>change in log-odds</strong> for a one-unit increase in X:</p>
<div class="fragment fade-up">
<p><strong>Our model:</strong> <span class="math inline">\(\text{logit}(\text{union}) = -2.674 + 0.023 \times \text{educ}\)</span></p>
<ul>
<li><strong>Intercept:</strong> log-odds of union membership when education = 0 — not substantively meaningful here</li>
<li><strong>Education coefficient (0.023):</strong> for each additional year of education, the <strong>log-odds</strong> of being a union member change by 0.023</li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The problem with log-odds</strong></p>
</div>
<div class="callout-content">
<p>“The log-odds decrease by 0.023” is technically correct but nearly impossible to communicate to a general audience. We need a better scale.</p>
<p><strong>The sign is always interpretable:</strong> - Positive <span class="math inline">\(\beta\)</span>: higher X → higher probability of Y = 1 - Negative <span class="math inline">\(\beta\)</span>: more education → <strong>lower</strong> probability of union membership</p>
<p>But the magnitude requires transformation. There are two options: odds ratios or predicted probabilities.</p>
</div>
</div>
</div>
</div>
</section>
<section id="from-log-odds-to-odds-ratios" class="slide level2 smaller">
<h2>From Log-Odds to Odds Ratios</h2>
<p>Exponentiating the coefficient converts log-odds to <strong>odds ratios (OR)</strong>:</p>
<p><span class="math display">\[OR = e^{\beta}\]</span></p>
<div class="fragment fade-up">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>OR value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OR &gt; 1</td>
<td>Each unit increase in X is <strong>associated with an increase in the odds</strong> of Y = 1</td>
</tr>
<tr class="even">
<td>OR = 1</td>
<td>No association between X and Y</td>
</tr>
<tr class="odd">
<td>OR &lt; 1</td>
<td>Each unit increase in X is <strong>associated with a decrease in the odds</strong> of Y = 1</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment fade-up">
<p><strong>Our example:</strong> <span class="math display">\[OR_{\text{educ}} = e^{0.023} = 1.023\]</span></p>
<p>Each additional year of education is associated with odds of union membership that are <strong>1.023 times</strong> those of someone with one fewer year — that is, each year is <strong>associated with a 2.3% increase in the odds</strong> of union membership.</p>
</div>
<div class="fragment fade-up">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>How to report an odds ratio</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(OR = e^\beta\)</span>; the percentage change in the odds <span class="math inline">\(= (e^\beta - 1) \times 100\)</span></p>
<p>Our result: <span class="math inline">\((e^{0.023} - 1) \times 100 = 2.3\%\)</span></p>
<p><strong>Academic phrasing:</strong> “Each additional year of education is associated with a 2.3% increase in the odds of union membership.”</p>
</div>
</div>
</div>
</div>
</section>
<section id="odds-ratios-in-modelsummary" class="slide level2 smaller scrollable">
<h2>Odds Ratios in <code>modelsummary()</code></h2>
<p><code>modelsummary()</code> can display both log-odds and odds ratios — use <code>exponentiate = TRUE</code>:</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Side-by-Side Comparison</a></li><li><a href="#tabset-3-2">Reading the Table</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">modelsummary</span>(</span>
<span id="cb8-2"><a></a>  <span class="fu">list</span>(<span class="st">"Log-Odds"</span> <span class="ot">=</span> model_logit_biv, <span class="st">"Odds Ratios"</span> <span class="ot">=</span> model_logit_biv),</span>
<span id="cb8-3"><a></a>  <span class="at">exponentiate =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">TRUE</span>),</span>
<span id="cb8-4"><a></a>  <span class="at">coef_rename  =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span> <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb8-5"><a></a>                   <span class="st">"educ"</span>        <span class="ot">=</span> <span class="st">"Years of Education"</span>),</span>
<span id="cb8-6"><a></a>  <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-7"><a></a>  <span class="at">title   =</span> <span class="st">"Log-Odds vs. Odds Ratios: same model, different scale"</span>,</span>
<span id="cb8-8"><a></a>  <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb8-9"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_47cmqbk5sd0v2udkx86f = TinyTable.createTableFunctions("tinytable_47cmqbk5sd0v2udkx86f");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '5', j: 2 }, { i: '5', j: 3 } ], css_id: 'tinytable_css_m9n2ypxqs3m3vwj437ed',}, 
          { positions: [ { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_ks5z0bwikif20cg8tsl9',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 } ], css_id: 'tinytable_css_r3nymv8vvw96ea0ao0m6',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_s4i94ylzkyfpfnkojoee',}, 
          { positions: [ { i: '5', j: 1 } ], css_id: 'tinytable_css_8cgdfvepc7vs4uiqwfbb',}, 
          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_vhbvkknlq5fhnaboyqlx',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 } ], css_id: 'tinytable_css_ohbr7qcuejqgo816s1sy',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_5if6bvxbwzgqaq95mn5z',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_47cmqbk5sd0v2udkx86f.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_m9n2ypxqs3m3vwj437ed, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_m9n2ypxqs3m3vwj437ed {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_ks5z0bwikif20cg8tsl9, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_ks5z0bwikif20cg8tsl9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_r3nymv8vvw96ea0ao0m6, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_r3nymv8vvw96ea0ao0m6 { text-align: center }
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_s4i94ylzkyfpfnkojoee, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_s4i94ylzkyfpfnkojoee {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_8cgdfvepc7vs4uiqwfbb, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_8cgdfvepc7vs4uiqwfbb {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_vhbvkknlq5fhnaboyqlx, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_vhbvkknlq5fhnaboyqlx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_ohbr7qcuejqgo816s1sy, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_ohbr7qcuejqgo816s1sy { text-align: left }
    #tinytable_47cmqbk5sd0v2udkx86f td.tinytable_css_5if6bvxbwzgqaq95mn5z, #tinytable_47cmqbk5sd0v2udkx86f th.tinytable_css_5if6bvxbwzgqaq95mn5z {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_47cmqbk5sd0v2udkx86f" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <caption>Log-Odds vs. Odds Ratios: same model, different scale</caption>
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Log-Odds</th>
                <th scope="col" data-row="0" data-col="3">Odds Ratios</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="3">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Intercept</td>
                  <td data-row="1" data-col="2">-2.674***</td>
                  <td data-row="1" data-col="3">0.069***</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.303)</td>
                  <td data-row="2" data-col="3">(0.021)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Years of Education</td>
                  <td data-row="3" data-col="2">0.023</td>
                  <td data-row="3" data-col="3">1.023</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.022)</td>
                  <td data-row="4" data-col="3">(0.023)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Num.Obs.</td>
                  <td data-row="5" data-col="2">2985</td>
                  <td data-row="5" data-col="3">2985</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</div>
<div id="tabset-3-2">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>How to read the two columns:</strong></p>
</div>
<div class="callout-content">
<p><strong>Log-Odds column:</strong> Coefficient = 0.023. Sign tells direction; value is the change in log-odds per year of education. Hard to communicate directly.</p>
<p><strong>Odds Ratios column:</strong> OR = 1.023. Values &lt; 1 mean lower odds; values &gt; 1 mean higher odds. An OR of 1.023 per year of education means: each additional year is associated with a <strong>2.3% increase in the odds</strong> of union membership.</p>
<p><strong>Stars / p-value</strong> are identical in both columns — statistical significance does not change when you transform the scale.</p>
<p><strong>For your assignments and final paper:</strong> report odds ratios, not log-odds. Always state what “OR = X” means in a plain-English sentence.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="categorical-predictors-in-logit" class="slide level2 smaller">
<h2>Categorical Predictors in Logit</h2>
<p>Categorical IVs work the same way as in OLS — use <code>fct_relevel()</code> to set the baseline:</p>
<div class="fragment fade-up">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="co"># Categorical IV: degree (baseline = lt high)</span></span>
<span id="cb9-2"><a></a>attain_logit_cat <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(union_member), <span class="sc">!</span><span class="fu">is.na</span>(degree_f))</span>
<span id="cb9-4"><a></a></span>
<span id="cb9-5"><a></a>model_logit_cat <span class="ot">&lt;-</span> <span class="fu">glm</span>(union_member <span class="sc">~</span> degree_f,</span>
<span id="cb9-6"><a></a>                       <span class="at">family =</span> binomial,</span>
<span id="cb9-7"><a></a>                       <span class="at">data   =</span> attain_logit_cat)</span>
<span id="cb9-8"><a></a></span>
<span id="cb9-9"><a></a><span class="fu">modelsummary</span>(model_logit_cat,</span>
<span id="cb9-10"><a></a>             <span class="at">exponentiate =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-11"><a></a>             <span class="at">coef_rename  =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>        <span class="ot">=</span> <span class="st">"Intercept (lt high, baseline)"</span>,</span>
<span id="cb9-12"><a></a>                              <span class="st">"degree_fhigh sch"</span>   <span class="ot">=</span> <span class="st">"High School"</span>,</span>
<span id="cb9-13"><a></a>                              <span class="st">"degree_fjunior c"</span>   <span class="ot">=</span> <span class="st">"Junior College"</span>,</span>
<span id="cb9-14"><a></a>                              <span class="st">"degree_fbachelor"</span>   <span class="ot">=</span> <span class="st">"Bachelor's Degree"</span>,</span>
<span id="cb9-15"><a></a>                              <span class="st">"degree_fgraduate"</span>   <span class="ot">=</span> <span class="st">"Graduate Degree"</span>),</span>
<span id="cb9-16"><a></a>             <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-17"><a></a>             <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"AIC"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_4xngeondpk66509plaea = TinyTable.createTableFunctions("tinytable_4xngeondpk66509plaea");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '11', j: 2 } ], css_id: 'tinytable_css_gj43lbhujxi83qir1ytp',}, 
          { positions: [ { i: '10', j: 2 } ], css_id: 'tinytable_css_fc7gvflfma6zw21p47iz',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 } ], css_id: 'tinytable_css_viunuid12qluiukgip94',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_7t0mx3vsnpy8ihw6jn8i',}, 
          { positions: [ { i: '11', j: 1 } ], css_id: 'tinytable_css_xr7cmllxucjt6z0vdn7r',}, 
          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_n8daj1jtw0fj6aj0tkis',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 } ], css_id: 'tinytable_css_d70kwdhsk4xfkda5kn75',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_l6ftmv7u9jlbq2r98pyp',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_4xngeondpk66509plaea.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_4xngeondpk66509plaea td.tinytable_css_gj43lbhujxi83qir1ytp, #tinytable_4xngeondpk66509plaea th.tinytable_css_gj43lbhujxi83qir1ytp {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_4xngeondpk66509plaea td.tinytable_css_fc7gvflfma6zw21p47iz, #tinytable_4xngeondpk66509plaea th.tinytable_css_fc7gvflfma6zw21p47iz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_4xngeondpk66509plaea td.tinytable_css_viunuid12qluiukgip94, #tinytable_4xngeondpk66509plaea th.tinytable_css_viunuid12qluiukgip94 { text-align: center }
    #tinytable_4xngeondpk66509plaea td.tinytable_css_7t0mx3vsnpy8ihw6jn8i, #tinytable_4xngeondpk66509plaea th.tinytable_css_7t0mx3vsnpy8ihw6jn8i {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_4xngeondpk66509plaea td.tinytable_css_xr7cmllxucjt6z0vdn7r, #tinytable_4xngeondpk66509plaea th.tinytable_css_xr7cmllxucjt6z0vdn7r {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_4xngeondpk66509plaea td.tinytable_css_n8daj1jtw0fj6aj0tkis, #tinytable_4xngeondpk66509plaea th.tinytable_css_n8daj1jtw0fj6aj0tkis {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_4xngeondpk66509plaea td.tinytable_css_d70kwdhsk4xfkda5kn75, #tinytable_4xngeondpk66509plaea th.tinytable_css_d70kwdhsk4xfkda5kn75 { text-align: left }
    #tinytable_4xngeondpk66509plaea td.tinytable_css_l6ftmv7u9jlbq2r98pyp, #tinytable_4xngeondpk66509plaea th.tinytable_css_l6ftmv7u9jlbq2r98pyp {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_4xngeondpk66509plaea" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Intercept (lt high, baseline)</td>
                  <td data-row="1" data-col="2">0.083***</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.014)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">High School</td>
                  <td data-row="3" data-col="2">1.162</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.219)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Junior College</td>
                  <td data-row="5" data-col="2">0.957</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.319)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Bachelor's Degree</td>
                  <td data-row="7" data-col="2">1.137</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.262)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">Graduate Degree</td>
                  <td data-row="9" data-col="2">1.224</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.353)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">Num.Obs.</td>
                  <td data-row="11" data-col="2">2982</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpreting categorical logit coefficients (as ORs):</strong></p>
</div>
<div class="callout-content">
<p>Each OR shows the <strong>odds of union membership</strong> for that degree level <strong>relative to the baseline</strong> (less than high school). OR &gt; 1 = higher odds than baseline; OR &lt; 1 = lower odds.</p>
</div>
</div>
</div>
</div>
</section>
<section id="questions-2" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-4-predicted-probabilities-and-margins" class="title-slide slide level1 center">
<h1>Part 4: Predicted Probabilities and Margins</h1>
<p>Making logit results interpretable</p>
</section>
<section id="why-probabilities-not-just-odds-ratios" class="slide level2 smaller">
<h2>Why Probabilities, Not Just Odds Ratios?</h2>
<p>Odds ratios are better than log-odds, but they have a limitation:</p>
<div class="fragment fade-up">
<p><strong>The non-constant effect problem:</strong> In logistic regression, the change in <em>probability</em> associated with a one-unit increase in X depends on where you start.</p>
<ul>
<li>Going from <code>educ = 7</code> to <code>educ = 8</code> → P(union) goes from 7.5% to 7.7% (Δ = 0.16 pp)</li>
<li>Going from <code>educ = 19</code> to <code>educ = 20</code> → P(union) goes from 9.7% to 9.9% (Δ = 0.21 pp)</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Where you start matters</strong></p>
</div>
<div class="callout-content">
<p>The <strong>odds ratio is a single constant number, but the actual probability change it represents is not constant</strong> — it varies depending on where you are on the sigmoid curve. The odds ratio gives one summary number that averages over this variation.</p>
</div>
</div>
</div>
</div>
<div class="fragment fade-up">
<p>This is best illustrated by showing <strong>predicted probabilities at specific values of X</strong> is often more interpretable and more honest.</p>
<p>Same OR (1.023) at both points — different probability change. The red arrows in the figure show this directly.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week12_files/figure-revealjs/unnamed-chunk-12-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="computing-predicted-probabilities" class="slide level2 smaller scrollable">
<h2>Computing Predicted Probabilities</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Manual Approach</a></li><li><a href="#tabset-4-2">Margins Plot</a></li><li><a href="#tabset-4-3">Margins by Category</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p>Use <code>predict(..., type = "response")</code> to get predicted probabilities directly:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="co"># Predict probability at specific education levels</span></span>
<span id="cb10-2"><a></a>pred_manual <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">educ =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">16</span>, <span class="dv">18</span>)) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-4"><a></a>    <span class="at">log_odds  =</span> <span class="fu">predict</span>(model_logit_biv, <span class="at">newdata =</span> <span class="fu">pick</span>(<span class="fu">everything</span>())),</span>
<span id="cb10-5"><a></a>    <span class="at">prob      =</span> <span class="fu">predict</span>(model_logit_biv, <span class="at">newdata =</span> <span class="fu">pick</span>(<span class="fu">everything</span>()), <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb10-6"><a></a>    <span class="at">prob_pct  =</span> scales<span class="sc">::</span><span class="fu">percent</span>(prob, <span class="at">accuracy =</span> <span class="fl">0.1</span>)</span>
<span id="cb10-7"><a></a>  )</span>
<span id="cb10-8"><a></a></span>
<span id="cb10-9"><a></a>pred_manual <span class="sc">|&gt;</span> <span class="fu">select</span>(educ, prob_pct)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
   educ prob_pct
  &lt;dbl&gt; &lt;chr&gt;   
1     8 7.7%    
2    10 8.0%    
3    12 8.4%    
4    14 8.7%    
5    16 9.1%    
6    18 9.5%    </code></pre>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The formula behind <code>predict(..., type = "response")</code>:</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[P(Y = 1 \mid \text{educ} = x) = \frac{e^{\hat\alpha + \hat\beta \cdot x}}{1 + e^{\hat\alpha + \hat\beta \cdot x}}\]</span> R computes this for you automatically with <code>type = "response"</code>.</p>
</div>
</div>
</div>
</div>
<div id="tabset-4-2">
<p>The <code>ggeffects</code> package creates a <strong>margins plot</strong> — predicted probability across values of X, with a 95% confidence interval:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">ggpredict</span>(model_logit_biv, <span class="at">terms =</span> <span class="st">"educ"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a></a>  <span class="fu">plot</span>() <span class="sc">+</span></span>
<span id="cb12-3"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb12-4"><a></a>    <span class="at">title =</span> <span class="st">"Predicted Probability of Union Membership by Education"</span>,</span>
<span id="cb12-5"><a></a>    <span class="at">x     =</span> <span class="st">"Years of Education"</span>,</span>
<span id="cb12-6"><a></a>    <span class="at">y     =</span> <span class="st">"P(Union Member)"</span></span>
<span id="cb12-7"><a></a>  ) <span class="sc">+</span></span>
<span id="cb12-8"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week12_files/figure-revealjs/unnamed-chunk-14-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the margins plot:</strong></p>
</div>
<div class="callout-content">
<p><strong>The line:</strong> Predicted probability of union membership falls as years of education increase — but the rate of decline is steepest in the middle of the education range and flattens at the extremes (exactly the non-constant effect shown in the previous slide).</p>
<p><strong>The ribbon (95% CI):</strong> Uncertainty around predicted probabilities. Notice it widens at the tails (very low/high education), where fewer respondents fall in the sample. <strong>Overlapping CIs between two values of X are a rough guide only</strong> — the proper test of significance comes from the logit coefficient’s p-value, not by visually comparing ribbon widths.</p>
</div>
</div>
</div>
</div>
<div id="tabset-4-3">
<p>With multiple predictors, plot the key predictor at each level of a categorical control:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="fu">ggpredict</span>(model_logit_multi, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"educ"</span>, <span class="st">"sex_f"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a></a>  <span class="fu">plot</span>() <span class="sc">+</span></span>
<span id="cb13-3"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"male"</span> <span class="ot">=</span> <span class="st">"#4E79A7"</span>, <span class="st">"female"</span> <span class="ot">=</span> <span class="st">"#E15759"</span>),</span>
<span id="cb13-4"><a></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Men"</span>, <span class="st">"Women"</span>)) <span class="sc">+</span></span>
<span id="cb13-5"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values  =</span> <span class="fu">c</span>(<span class="st">"male"</span> <span class="ot">=</span> <span class="st">"#4E79A7"</span>, <span class="st">"female"</span> <span class="ot">=</span> <span class="st">"#E15759"</span>),</span>
<span id="cb13-6"><a></a>                    <span class="at">labels  =</span> <span class="fu">c</span>(<span class="st">"Men"</span>, <span class="st">"Women"</span>)) <span class="sc">+</span></span>
<span id="cb13-7"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb13-8"><a></a>    <span class="at">title  =</span> <span class="st">"Predicted P(Union Member) by Education and Sex"</span>,</span>
<span id="cb13-9"><a></a>    <span class="at">x      =</span> <span class="st">"Years of Education"</span>,</span>
<span id="cb13-10"><a></a>    <span class="at">y      =</span> <span class="st">"Predicted Probability"</span>,</span>
<span id="cb13-11"><a></a>    <span class="at">color  =</span> <span class="st">"Sex"</span>,</span>
<span id="cb13-12"><a></a>    <span class="at">fill   =</span> <span class="st">"Sex"</span></span>
<span id="cb13-13"><a></a>  ) <span class="sc">+</span></span>
<span id="cb13-14"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week12_files/figure-revealjs/unnamed-chunk-15-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the margins by category plot:</strong></p>
</div>
<div class="callout-content">
<p><strong>Two lines:</strong> Each line shows the predicted probability of union membership across education levels — blue for men, red for women. The vertical gap between the curves at any education level reflects the sex coefficient from the multiple regression model.</p>
<p><strong>Overlapping confidence ribbons between curves:</strong> Where the ribbons for men and women overlap, the difference in predicted probability between sexes at that education level is <strong>not statistically distinguishable</strong> — we cannot rule out that the apparent gap is due to sampling variation. Where the ribbons <em>do not</em> overlap, the sex difference is statistically meaningful. This makes the margins plot more informative than a single odds ratio: you can see <em>where</em> and <em>for whom</em> the effect matters.</p>
<p><strong>Key finding:</strong> More educated respondents have lower predicted probability of union membership for both men and women — consistent with the historical pattern that union membership in the early 1990s was concentrated among blue-collar and manufacturing workers.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions-3" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="reading-freeman-braconi-2004" class="title-slide slide level1 center">
<h1>Reading: Freeman &amp; Braconi (2004)</h1>
<p>Logistic regression in an urban sociology classic</p>
</section>
<section id="gentrification-and-displacement-overview" class="slide level2 smaller">
<h2>“Gentrification and Displacement” — Overview</h2>
<p><strong>Freeman, L. &amp; Braconi, F. (2004).</strong> <em>Gentrification and Displacement: New York City in the 1990s.</em> <strong>Journal of the American Planning Association, 70</strong>(1), 39–52.</p>
<div class="fragment fade-up">
<p><strong>Research question:</strong> Does gentrification actually displace lower-income residents? Are lower-income households in gentrifying NYC neighborhoods more likely to move than comparable households in non-gentrifying neighborhoods?</p>
<ul>
<li>Driven by a fundamental debate in urban sociology: gentrification is widely assumed to push poor residents out</li>
<li>The authors bring <strong>quantitative methods</strong> to a debate that had relied largely on anecdote and case studies</li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why this paper for logistic regression week?</strong></p>
</div>
<div class="callout-content">
<p>The outcome of interest — whether a household moves — is <strong>binary</strong> (moved = 1, stayed = 0). OLS cannot sensibly model this. The authors use logistic regression to model this.</p>
</div>
</div>
</div>
</div>
</section>
<section id="research-design" class="slide level2 smaller scrollable">
<h2>Research Design</h2>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Data &amp; Sample</a></li><li><a href="#tabset-5-2">Variables</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<ul>
<li><strong>Data:</strong> New York City Housing and Vacancy Survey (NYCHVS), 1991 and 1999 waves — a panel survey of NYC housing units</li>
<li><strong>Sample:</strong> Lower-income renters tracked across the two survey waves</li>
<li><strong>Strategy:</strong> Compare mobility rates between households in gentrifying vs.&nbsp;non-gentrifying census tracts, after controlling for individual characteristics</li>
</ul>
</div>
<div id="tabset-5-2">
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Variable</th>
<th>Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Outcome (DV)</strong></td>
<td>Moved between surveys</td>
<td>Binary: 1 = household moved, 0 = stayed</td>
</tr>
<tr class="even">
<td><strong>Key predictor</strong></td>
<td>Neighborhood gentrification</td>
<td>Binary: 1 = tract classified as gentrifying, 0 = not</td>
</tr>
<tr class="odd">
<td><strong>Controls</strong></td>
<td>Race, income, education, household size, tenure status, overcrowding</td>
<td>Individual and household characteristics</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Connecting to today:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Outcome variable:</strong> <code>moved</code> (binary 0/1) → requires logistic regression, not OLS</li>
<li><strong>Key predictor:</strong> gentrification status (binary IV, treated as categorical)</li>
<li><strong>Controls:</strong> individual characteristics — “held constant” so the gentrification coefficient reflects neighborhood effect net of who lives there</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="key-results" class="slide level2 smaller">
<h2>Key Results</h2>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">The Counterintuitive Finding</a></li><li><a href="#tabset-6-2">Results Table</a></li><li><a href="#tabset-6-3">The Scholarly Debate</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Surprise: lower-income households in gentrifying neighborhoods were <em>less</em> likely to move</strong></p>
</div>
<div class="callout-content">
<p>After controlling for individual and household characteristics, the odds ratio on the gentrification variable was <strong>less than 1</strong> — meaning lower-income residents in gentrifying neighborhoods were actually <strong>less likely to be displaced</strong> than comparable residents in non-gentrifying neighborhoods.</p>
<p>This directly challenged the dominant narrative that gentrification necessarily causes displacement.</p>
</div>
</div>
</div>
</div>
<div id="tabset-6-2">
<p>Selected results from Freeman &amp; Braconi (2004), Table 3 — poor households model (logistic regression, DV = household moved between NYCHVS waves):</p>
<table style="font-size:0.82em; width:100%; border-collapse:collapse;">
<thead>
<tr>
<th style="border-bottom:2px solid #888; text-align:left; padding:4px 8px;">
</th>
<th colspan="2" style="background-color:#4E79A7; color:white; text-align:center; padding:4px 8px; border-radius:4px 4px 0 0;">
Probability of Moving (logit)
</th>
</tr>
<tr>
<th style="border-bottom:1px solid #ccc; text-align:left; padding:4px 8px; width:55%;">
Variable
</th>
<th style="background-color:#d0e4f5; text-align:center; padding:4px 8px;">
Odds Ratio
</th>
<th style="background-color:#d0e4f5; text-align:center; padding:4px 8px;">
Sig.
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:4px 8px;">
<strong>Gentrifying neighborhood</strong>
</td>
<td style="background-color:#d0e4f5; text-align:center;">
<strong>0.81</strong>
</td>
<td style="background-color:#d0e4f5; text-align:center;">
**
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Monthly rent
</td>
<td style="background-color:#d0e4f5; text-align:center;">
1.01
</td>
<td style="background-color:#d0e4f5; text-align:center;">
***
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Years in current residence
</td>
<td style="background-color:#d0e4f5; text-align:center;">
0.98
</td>
<td style="background-color:#d0e4f5; text-align:center;">
***
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Rent-stabilized unit
</td>
<td style="background-color:#d0e4f5; text-align:center;">
0.94
</td>
<td style="background-color:#d0e4f5; text-align:center;">
<em>ns</em>
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Rent-controlled unit
</td>
<td style="background-color:#d0e4f5; text-align:center;">
1.39
</td>
<td style="background-color:#d0e4f5; text-align:center;">
<em>ns</em>
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Other regulated unit
</td>
<td style="background-color:#d0e4f5; text-align:center;">
0.78
</td>
<td style="background-color:#d0e4f5; text-align:center;">
*
</td>
</tr>
<tr>
<td style="padding:4px 8px;">
Overcrowded unit
</td>
<td style="background-color:#d0e4f5; text-align:center;">
1.37
</td>
<td style="background-color:#d0e4f5; text-align:center;">
**
</td>
</tr>
<tr>
<td style="padding:4px 8px; border-top:1px solid #ccc;">
N
</td>
<td style="background-color:#d0e4f5; text-align:center; border-top:1px solid #ccc;" colspan="2">
3,496 poor renter households
</td>
</tr>
</tbody>
</table>
<p><small><em>p &lt; .10; <strong>p &lt; .05; </strong></em>p &lt; .01. Adapted from Freeman &amp; Braconi (2004), Table 3.</small></p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The key result: OR = 0.81 on gentrifying neighborhood</strong></p>
</div>
<div class="callout-content">
<p>Living in a gentrifying neighborhood is associated with <strong>19% lower odds of moving</strong> (OR = 0.81, p &lt; .05) compared to comparable poor households elsewhere — even after controlling for rent, tenure, housing regulation, and crowding. Race is controlled but not significant. This is the counterintuitive finding that drove the debate.</p>
</div>
</div>
</div>
</div>
<div id="tabset-6-3">
<p>Freeman &amp; Braconi’s finding generated enormous debate:</p>
<ul>
<li><strong>Critics</strong> argued the study underestimated displacement by focusing on <em>who stayed</em> rather than tracking those who left</li>
<li><strong>Methodological objections:</strong> selection bias (only gentrifying areas that didn’t displace residents get classified as gentrifying?); survivorship bias in panel data</li>
<li><strong>Follow-up studies</strong> using different methods found mixed results</li>
</ul>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A lesson about quantitative methods:</strong></p>
</div>
<div class="callout-content">
<p>Even when a study uses the right statistical technique correctly, the <strong>research design</strong> (what data are collected, who is in the sample, how variables are measured) can produce misleading results. Statistics can only answer the question you’ve asked — asking the right question is the harder problem.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="connecting-freeman-braconi-to-today" class="slide level2 smaller">
<h2>Connecting Freeman &amp; Braconi to Today</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Today’s concept</th>
<th>In Freeman &amp; Braconi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Binary outcome</strong></td>
<td>Household moved (1) or stayed (0)</td>
</tr>
<tr class="even">
<td><strong>Logistic regression</strong></td>
<td><code>glm(moved ~ gentrification + controls, family = binomial)</code></td>
</tr>
<tr class="odd">
<td><strong>Key predictor</strong></td>
<td>Neighborhood gentrification status (the main theoretical variable)</td>
</tr>
<tr class="even">
<td><strong>Controls</strong></td>
<td>Race, income, education — “held constant”</td>
</tr>
<tr class="odd">
<td><strong>Odds ratio interpretation</strong></td>
<td>OR &lt; 1 → lower odds of moving in gentrifying areas</td>
</tr>
<tr class="even">
<td><strong>Counterintuitive result</strong></td>
<td>Statistics sometimes challenge common sense — which is why we do quantitative research</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>For your research paper:</strong></p>
</div>
<div class="callout-content">
<p>Freeman &amp; Braconi show how to: (1) justify the choice of logistic regression based on the outcome’s measurement; (2) interpret odds ratios substantively; (3) discuss what controls are doing; (4) acknowledge limitations honestly. These are the same elements your final paper needs.</p>
</div>
</div>
</div>
</section>
<section id="questions-4" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="key-takeaways" class="slide level2 smaller">
<h2>Key Takeaways</h2>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Part 1 — Why Logit</a></li><li><a href="#tabset-7-2">Part 2 — The Model &amp; Coefficients</a></li><li><a href="#tabset-7-3">Part 3 — Predicted Probabilities</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<ul>
<li>When the outcome is <strong>binary (0/1)</strong>, OLS produces a <strong>linear probability model (LPM)</strong> that can predict probabilities outside [0, 1]</li>
<li>LPM also assumes <strong>constant marginal effects</strong> — unrealistic when probabilities are near 0 or 1</li>
<li><strong>Logistic regression</strong> transforms the outcome to <strong>log-odds</strong>, which can range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span> — then the predicted <em>probability</em> is recovered via the sigmoid function, guaranteed to stay within [0, 1]</li>
<li><strong>Practical note:</strong> LPM and logit give similar results in the middle range of probabilities — they diverge at extremes; discipline convention favors logit in sociology</li>
</ul>
</div>
<div id="tabset-7-2">
<ul>
<li>The logistic model: <span class="math inline">\(\log\!\left(\frac{P}{1-P}\right) = \alpha + \beta x\)</span></li>
<li>Fit with <code>glm(y ~ x, family = binomial)</code> — not <code>lm()</code></li>
<li>Coefficient <span class="math inline">\(\beta\)</span> = change in <strong>log-odds</strong> per one-unit increase in X</li>
<li><span class="math inline">\(e^\beta\)</span> = <strong>odds ratio</strong> — how much the odds of Y = 1 multiply per one-unit increase in X</li>
<li><span class="math inline">\((e^\beta - 1) \times 100\)</span> = <strong>percentage change in the odds</strong></li>
<li><code>modelsummary(..., exponentiate = TRUE)</code> converts the table to odds ratios automatically</li>
</ul>
</div>
<div id="tabset-7-3">
<ul>
<li>Odds ratios tell you direction and relative magnitude; <strong>predicted probabilities</strong> make results tangible</li>
<li>Use <code>predict(model, newdata = ..., type = "response")</code> for probabilities at specific values</li>
<li>Use <code>ggpredict(model, terms = "var")</code> from <code>ggeffects</code> for a clean <strong>margins plot</strong>; add a second term for a <strong>margins by category</strong> plot</li>
<li>For multiple regression models: hold other variables at their means/modes and vary the key predictor</li>
<li><strong>Always report predicted probabilities</strong> when presenting logistic regression results to non-technical audiences</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>How to get it</th>
<th>Best for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Log-odds</td>
<td>Direct coefficient</td>
<td>Testing significance</td>
</tr>
<tr class="even">
<td>Odds ratio</td>
<td><code>exp(coef)</code> or <code>exponentiate = TRUE</code></td>
<td>Reporting direction + magnitude</td>
</tr>
<tr class="odd">
<td>Probability</td>
<td><code>predict(..., type = "response")</code> or <code>ggpredict()</code></td>
<td>Communicating to audiences</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="why-this-matters-for-your-research-paper" class="slide level2 smaller scrollable">
<h2>Why This Matters for Your Research Paper</h2>
<ul>
<li><strong>HW #10</strong> asks you to run a logistic regression on a binary outcome from your research data</li>
<li>If your <strong>outcome variable</strong> is binary (0/1, yes/no, has/doesn’t have), logistic regression is the right choice for your <strong>final paper</strong></li>
<li>If your outcome is continuous, stay with OLS — no need to use logit</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What HW #10 asks — and what you now know how to do:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Identify a binary outcome and key predictor</strong> → Part 1 today</li>
<li><strong>Run <code>glm(..., family = binomial)</code> and display odds ratios with <code>modelsummary(..., exponentiate = TRUE)</code></strong> → Part 3 today</li>
<li><strong>Interpret the odds ratio</strong> in plain language: OR, direction, percentage change in odds → Part 3 today</li>
<li><strong>Compute and visualize predicted probabilities</strong> at key values of your predictor → Part 4 today</li>
<li><strong>If using a categorical predictor</strong>: use <code>fct_relevel()</code> to set a baseline → Part 3 today</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>One thing to add to your thinking:</strong></p>
</div>
<div class="callout-content">
<p>Unlike OLS, there is no simple <span class="math inline">\(R^2\)</span> for logistic regression. Focus your discussion on <strong>(1) whether the relationship is significant</strong>, <strong>(2) the odds ratio magnitude</strong>, and <strong>(3) predicted probabilities at substantively interesting values of your predictor</strong>.</p>
</div>
</div>
</div>
</section>
<section id="questions-5" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="assignments" class="slide level2 smaller scrollable">
<h2>Assignments</h2>
<p><strong>Weekly Assignment #10</strong> — <span class="highlight">Due Thursday, April 23</span></p>
<p>Using your research dataset:</p>
<ol type="1">
<li>Identify a <strong>binary outcome variable</strong> — state why this variable is binary and what Y = 1 means</li>
<li>State a research question and directional hypothesis</li>
<li>Run logistic regression with <code>glm(..., family = binomial)</code> and display an odds ratio table using <code>modelsummary(..., exponentiate = TRUE)</code></li>
<li>Interpret your key predictor’s <strong>odds ratio</strong>: direction, magnitude, percentage change in the odds</li>
<li>Compute <strong>predicted probabilities</strong> at two or more meaningful values of your key predictor</li>
<li>Produce a <strong>margins plot</strong> using <code>ggeffects::ggpredict(model, terms = "var")</code> — add a second term for a margins by category breakdown if you have a categorical predictor or control</li>
<li>Briefly discuss whether the pattern is <strong>statistically</strong> and <strong>substantively</strong> significant</li>
</ol>
<p><strong>Also upcoming:</strong></p>
<ul>
<li><strong>Revised Proposal with Outline</strong> — <span class="highlight">Due Thursday, April 16</span>
<ul>
<li>Specify whether your final analysis uses OLS or logistic regression, and why</li>
</ul></li>
<li><strong>Final paper</strong> — details to follow</li>
</ul>
<p><strong>In-class lab today:</strong></p>
<ul>
<li>Apply logistic regression to your own research dataset</li>
<li>Practice converting log-odds to odds ratios and computing predicted probabilities</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://www.kaseyzapatka.com/soc106">GitHub course repo</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>