<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-03-17">
  <title>Sociology 106 – Week 9</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="slides.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 9</h1>
  <p class="subtitle">Sociology 106: Quantitative Sociological Methods</p>

<div class="quarto-title-authors">
</div>

  <p class="date">March 17, 2026</p>
</section>
<section id="agenda" class="slide level2 smaller">
<h2>Agenda</h2>
<p><strong>Housekeeping:</strong></p>
<ul>
<li>Annotated bibliography &amp; Spring Recess</li>
</ul>
<p><strong>Statistical content — three parts:</strong></p>
<ul>
<li><strong>Part 1</strong>: Hypothesis testing — the logic</li>
<li><strong>Part 2</strong>: t-tests for means and group differences (+ proportion z-test)</li>
<li><strong>Part 3</strong>: Chi-squared test — associations between two categorical variables</li>
</ul>
<p><strong>In-class lab:</strong></p>
<ul>
<li>Applying hypothesis tests to your research data</li>
</ul>
</section>
<section id="housekeeping" class="slide level2 smaller">
<h2>Housekeeping</h2>
<p><strong>Annotated Bibliography</strong></p>
<ul>
<li><span class="highlight">Due Thursday, March 19</span></li>
<li>Happy to answer last-minute questions after class!</li>
<li>Example on bCourses under the Research Paper folder</li>
</ul>
<p><strong>Weekly Assignment #8</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 2</span> (after Spring Recess)</li>
<li>Involves applying today’s hypothesis testing tools to your research dataset</li>
</ul>
<p><strong>Spring Recess</strong></p>
<ul>
<li><span class="highlight">March 24 — enjoy the break!</span></li>
<li>Use that time to relax and work on you paper proposal with outline due on 4/16</li>
</ul>
</section>
<section id="where-we-are-in-the-course" class="slide level2 smaller">
<h2>Where We Are in the Course</h2>
<ul>
<li><strong>Week 7:</strong> sampling distributions and the Central Limit Theorem</li>
<li><strong>Week 8:</strong> confidence intervals — estimating population parameters from samples</li>
<li><strong>This week (Week 9):</strong> hypothesis testing + chi-squared tests for associations</li>
<li><strong>Weeks 10–13:</strong> regression analysis (OLS and logistic)</li>
</ul>
<p><strong>Main idea:</strong> Last week we built confidence intervals — a <em>range</em> of plausible values for a parameter. Today we flip the question: given a specific claim about the population, how likely are our sample results if that claim were true?</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The chain of inference so far:</strong></p>
</div>
<div class="callout-content">
<p><strong>Week 7:</strong> Population → Sample → Statistic → Sampling distribution</p>
<p><strong>Week 8:</strong> Sample → Statistic → Confidence interval → Inference</p>
<p><strong>Week 9:</strong> Null hypothesis + Sample statistic → Test statistic → p-value → Decision</p>
</div>
</div>
</div>
</section>
<section id="last-week-recap" class="slide level2 smaller">
<h2>Last Week: Recap</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Key idea</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Point estimate</strong></td>
<td>Best single guess for population parameter</td>
<td><span class="math inline">\(\hat{p} = 0.449\)</span> (GSS env. support)</td>
</tr>
<tr class="even">
<td><strong>Standard error</strong></td>
<td>How uncertain is the estimate?</td>
<td><span class="math inline">\(SE(\hat{p}) = 0.015\)</span></td>
</tr>
<tr class="odd">
<td><strong>Confidence interval</strong></td>
<td>Range likely to contain the true parameter</td>
<td>95% CI: [0.420, 0.478]</td>
</tr>
<tr class="even">
<td><strong>z vs t</strong></td>
<td>Proportions → z; Means → t</td>
<td><span class="math inline">\(z^* = 1.96\)</span>; <span class="math inline">\(t^* = 2.447\)</span> (<span class="math inline">\(df = 6\)</span>)</td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Connection to today:</strong></p>
</div>
<div class="callout-content">
<p>Last week we <em>estimated</em> unknown population parameters and surrounded them with intervals. Today we start from a <em>specific claim</em> about the population — and ask whether our data are consistent with it.</p>
</div>
</div>
</div>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
</section>
<section>
<section id="part-1-hypothesis-testing" class="title-slide slide level1 center">
<h1>Part 1: Hypothesis Testing</h1>
<p>Can we rule out chance as an explanation?</p>
</section>
<section id="what-is-a-hypothesis-test" class="slide level2 smaller">
<h2>What Is a Hypothesis Test?</h2>
<p>A <strong>hypothesis test</strong> is a formal statistical procedure for evaluating whether a finding is likely due to chance.</p>
<div class="fragment fade-up">
<p><strong>The core steps:</strong></p>
<ol type="1">
<li><strong>State a null hypothesis</strong> (<span class="math inline">\(H_0\)</span>): “there is no real effect” — the finding is just chance</li>
<li><strong>Compute a test statistic</strong>: how far is our sample result from what <span class="math inline">\(H_0\)</span> would predict?</li>
<li><strong>Calculate a p-value</strong>: if <span class="math inline">\(H_0\)</span> is true, how likely is a result this extreme?</li>
<li><strong>Decide</strong>: if the p-value is small enough, reject <span class="math inline">\(H_0\)</span></li>
</ol>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The core logic:</strong></p>
</div>
<div class="callout-content">
<p>We don’t prove the null hypothesis wrong — we ask: <em>if it were true, how surprising would our data be?</em> If very surprising, we have grounds to doubt the null.</p>
</div>
</div>
</div>
</div>
</section>
<section id="a-motivating-example-james-bond" class="slide level2 smaller">
<h2>A Motivating Example: James Bond</h2>
<p>James Bond claims he can tell whether a martini is <strong>shaken or stirred</strong> just by tasting it.</p>
<div class="fragment fade-up">
<p><strong>The experiment:</strong> Give him 16 randomly prepared martinis. He correctly identifies <strong>13 out of 16</strong>.</p>
<p><strong>Null hypothesis (<span class="math inline">\(H_0\)</span>):</strong> He’s just guessing — each trial is a 50-50 coin flip (<span class="math inline">\(\pi = 0.5\)</span>)</p>
<p><strong>Alternative hypothesis (<span class="math inline">\(H_1\)</span>):</strong> He can genuinely tell the difference — he performs better than random guessing (<span class="math inline">\(\pi &gt; 0.5\)</span>)</p>
</div>
<div class="fragment fade-up">
<p><strong>The question:</strong> If he were just guessing, how likely is it that he’d get 13 or more right out of 16?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># P(X &gt;= 13) under H0: X ~ Binomial(n = 16, p = 0.5)</span></span>
<span id="cb1-2"><a></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">12</span>, <span class="at">size =</span> <span class="dv">16</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01063538</code></pre>
</div>
</div>
</div>
<div class="fragment fade-up">
<p>Probability ≈ <strong>1.1%</strong> — very unlikely if he were just guessing. We have strong evidence he can actually tell the difference.</p>
</div>
</section>
<section id="p-values" class="slide level2 smaller">
<h2>P-values</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Definition</a></li><li><a href="#tabset-1-2">What p-values tell us</a></li><li><a href="#tabset-1-3">What p-values do NOT tell us</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>A <strong>p-value</strong> is the probability of observing a test statistic <strong>as extreme as (or more extreme than)</strong> the one we got, <em>assuming the null hypothesis is true</em></p>
<ul>
<li><strong>James Bond:</strong> <span class="math inline">\(p = 0.011\)</span> — if guessing randomly, only 1.1% chance of ≥ 13/16 correct</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Critical misconception:</strong></p>
</div>
<div class="callout-content">
<p>The p-value is <strong>NOT</strong> the probability that <span class="math inline">\(H_0\)</span> is true. The null hypothesis is either true or false — it doesn’t have a probability.</p>
<p><strong>What it IS:</strong> The p-value is P(data this extreme | <span class="math inline">\(H_0\)</span> true) — the probability of observing results <em>at least this extreme</em>, assuming the null holds. It answers: <em>“if the null were true, how often would we see data like ours?”</em> — not <em>“how likely is the null to be true?”</em></p>
</div>
</div>
</div>
</div>
<div id="tabset-1-2">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Very small (e.g., 0.001)</td>
<td>Data would be very surprising under <span class="math inline">\(H_0\)</span> → strong evidence against <span class="math inline">\(H_0\)</span></td>
</tr>
<tr class="even">
<td>Small (e.g., 0.03)</td>
<td>Data somewhat unlikely under <span class="math inline">\(H_0\)</span> → moderate evidence against <span class="math inline">\(H_0\)</span></td>
</tr>
<tr class="odd">
<td>Large (e.g., 0.40)</td>
<td>Data consistent with <span class="math inline">\(H_0\)</span> → no reason to doubt <span class="math inline">\(H_0\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-1-3">
<ul>
<li>❌ The probability that <span class="math inline">\(H_0\)</span> is true</li>
<li>❌ The probability that we made an error</li>
<li>❌ How large or important the effect is</li>
<li>❌ Whether the finding matters in practice</li>
</ul>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Statistical ≠ substantive significance:</strong></p>
</div>
<div class="callout-content">
<p>A result can be <strong>statistically significant</strong> (<span class="math inline">\(p &lt; 0.05\)</span>) but <strong>substantively trivial</strong> — the effect is real but tiny. With large samples, even meaningless effects can reach significance. Always report the <em>size</em> of the effect, not just whether it is significant.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="significance-levels" class="slide level2 smaller">
<h2>Significance Levels</h2>
<p><strong>How small does the p-value need to be before we reject <span class="math inline">\(H_0\)</span>?</strong></p>
<p>We set a <strong>significance level</strong> <span class="math inline">\(\alpha\)</span> in advance — the threshold below which we’ll reject:</p>
<div class="fragment fade-up">
<ul>
<li><strong>Most common:</strong> <span class="math inline">\(\alpha = 0.05\)</span> — we use this in this class</li>
<li>Also used: <span class="math inline">\(\alpha = 0.01\)</span>, <span class="math inline">\(\alpha = 0.10\)</span></li>
</ul>
<p><strong>Decision rule:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Result</th>
<th>Decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p &lt; \alpha\)</span></td>
<td><strong>Reject <span class="math inline">\(H_0\)</span></strong> — accept <span class="math inline">\(H_1\)</span>; say the result is “statistically significant”</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p \geq \alpha\)</span></td>
<td><strong>Fail to reject <span class="math inline">\(H_0\)</span></strong> — we do <em>not</em> “accept” <span class="math inline">\(H_0\)</span>, we just lack evidence to reject it</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why “fail to reject” — not “accept”?</strong></p>
</div>
<div class="callout-content">
<p>A negative result doesn’t prove the null is true. A small sample may simply be too underpowered to detect a real effect. We might be failing to reject because the effect doesn’t exist — or because we didn’t have enough data to see it.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-danger-of-weak-tests-an-illustration" class="slide level2 smaller">
<h2>The Danger of Weak Tests: An Illustration</h2>
<p>Suppose a coin has a true probability of heads <span class="math inline">\(\pi = 0.51\)</span>. We flip it 50 times and get 24 heads.</p>
<div class="fragment fade-up">
<p><strong>Test <span class="math inline">\(H_0: \pi = 0.50\)</span></strong> with a two-tailed test:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">pbinom</span>(<span class="dv">24</span>, <span class="dv">50</span>, <span class="fl">0.5</span>) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">25</span>, <span class="dv">50</span>, <span class="fl">0.5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8877248</code></pre>
</div>
</div>
<p><span class="math inline">\(p \approx 0.89\)</span> — we fail to reject the null.</p>
</div>
<div class="fragment fade-up">
<p>But we <strong>know</strong> <span class="math inline">\(H_0\)</span> is false — the true value is <span class="math inline">\(\pi = 0.51\)</span>, not <span class="math inline">\(0.50\)</span>!</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The lesson:</strong></p>
</div>
<div class="callout-content">
<p>Failing to reject <span class="math inline">\(H_0\)</span> does not mean <span class="math inline">\(H_0\)</span> is true. The test just didn’t have enough <strong>statistical power</strong> to detect a very small effect. This is why we say “fail to reject” — not “accept.”</p>
</div>
</div>
</div>
</div>
</section>
<section id="one--and-two-tailed-tests" class="slide level2 smaller">
<h2>One- and Two-Tailed Tests</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">One-Tailed</a></li><li><a href="#tabset-2-2">Two-Tailed</a></li><li><a href="#tabset-2-3">Visualized</a></li><li><a href="#tabset-2-4">When to Use Which</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>A <strong>one-tailed test</strong> checks for a significant effect in <em>one specific direction</em></p>
<ul>
<li><span class="math inline">\(H_0: \pi \leq 0.50\)</span> vs.&nbsp;<span class="math inline">\(H_1: \pi &gt; 0.50\)</span></li>
<li>All of <span class="math inline">\(\alpha\)</span> is in one tail — easier to reject, but only in the predicted direction</li>
</ul>
<p><strong>James Bond (one-tailed):</strong> Did he perform <em>better than</em> random guessing?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="co"># P(X &gt;= 13): all probability in upper tail</span></span>
<span id="cb5-2"><a></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">12</span>, <span class="at">size =</span> <span class="dv">16</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01063538</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2">
<p>A <strong>two-tailed test</strong> checks for a significant effect in <em>either direction</em></p>
<ul>
<li><span class="math inline">\(H_0: \pi = 0.50\)</span> vs.&nbsp;<span class="math inline">\(H_1: \pi \neq 0.50\)</span></li>
<li><span class="math inline">\(\alpha\)</span> is split equally — 2.5% in each tail; <strong>more conservative and more common</strong> in social science</li>
</ul>
<p><strong>James Bond (two-tailed):</strong> Did he perform <em>differently from</em> random guessing?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="co"># Multiply by 2: account for both tails</span></span>
<span id="cb7-2"><a></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">12</span>, <span class="at">size =</span> <span class="dv">16</span>, <span class="at">prob =</span> <span class="fl">0.5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02127075</code></pre>
</div>
</div>
</div>
<div id="tabset-2-3">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week8/1_vs_2tailed_test.png" style="width:55.0%"></p>
<figcaption>One-tailed (top) vs.&nbsp;two-tailed (bottom) tests</figcaption>
</figure>
</div>
<ul>
<li><strong>One-tailed</strong>: rejection region entirely on one side</li>
<li><strong>Two-tailed</strong>: rejection region split — requires a more extreme result to reject</li>
</ul>
</div>
<div id="tabset-2-4">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Scenario</th>
<th>Recommended</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Theory strongly predicts the <em>direction</em></td>
<td>One-tailed (use sparingly!)</td>
</tr>
<tr class="even">
<td>No strong directional prediction</td>
<td><strong>Two-tailed</strong> (default)</td>
</tr>
<tr class="odd">
<td>Exploratory research</td>
<td>Two-tailed</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Default to two-tailed:</strong></p>
</div>
<div class="callout-content">
<p>Unless you have a strong, pre-specified theoretical reason to predict direction, use a two-tailed test. Effects in the “unexpected” direction are often theoretically important!</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="cis-and-hypothesis-tests-are-connected" class="slide level2 smaller scrollable">
<h2>CIs and Hypothesis Tests Are Connected</h2>
<p>Last week’s confidence intervals and today’s hypothesis tests are two sides of the same coin:</p>
<div class="fragment fade-up">
<ul>
<li>If the <strong>95% CI does not contain</strong> the null value <span class="math inline">\(\mu_0\)</span> → <strong>reject <span class="math inline">\(H_0\)</span></strong> at <span class="math inline">\(\alpha = 0.05\)</span></li>
<li>If the <strong>95% CI contains</strong> the null value → <strong>fail to reject <span class="math inline">\(H_0\)</span></strong></li>
</ul>
</div>
<div class="fragment fade-up">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week9_files/figure-revealjs/unnamed-chunk-6-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The equivalence:</strong></p>
</div>
<div class="callout-content">
<p>The 95% CI is precisely the set of null values you would <strong>fail to reject</strong> at <span class="math inline">\(\alpha = 0.05\)</span>. Testing and estimation are equivalent — they just frame the same question differently.</p>
</div>
</div>
</div>
</div>
</section>
<section id="questions-1" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-2-t-tests-for-means-and-group-differences" class="title-slide slide level1 center">
<h1>Part 2: t-Tests for Means and Group Differences</h1>
<p>Testing associations involving a continuous outcome variable</p>
</section>
<section id="three-common-tests" class="slide level2 smaller">
<h2>Three Common Tests</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>When to use</th>
<th>Key statistic</th>
<th>Distribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>One-sample t-test</strong></td>
<td>Continuous variable; test if <span class="math inline">\(\bar{x} = \mu\)</span></td>
<td>t-score</td>
<td>t (<span class="math inline">\(df = n-1\)</span>)</td>
</tr>
<tr class="even">
<td><strong>Two-sample t-test</strong></td>
<td>Compare means of two groups</td>
<td>t-score</td>
<td>t (<span class="math inline">\(df \approx n_1+n_2-2\)</span>)</td>
</tr>
<tr class="odd">
<td><strong>Proportion test</strong></td>
<td>Binary variable; test if <span class="math inline">\(\hat{p} = P\)</span></td>
<td>z-score</td>
<td>Normal</td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>All three tests follow the same steps:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>state <span class="math inline">\(H_0\)</span></li>
<li>compute a test statistic measuring how far the sample result is from <span class="math inline">\(H_0\)</span></li>
<li>find the p-value under the null distribution</li>
<li>decide</li>
</ol>
</div>
</div>
</div>
</section>
<section id="writing-up-results-best-practices" class="slide level2 smaller">
<h2>Writing Up Results: Best Practices</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Every hypothesis test write-up should include:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>The sample statistic</strong> (mean, proportion, or difference) — not just the p-value</li>
<li><strong>The test statistic</strong> and <strong>p-value</strong></li>
<li><strong>Whether you reject or fail to reject <span class="math inline">\(H_0\)</span></strong>, at <span class="math inline">\(\alpha = 0.05\)</span></li>
<li><strong>A plain-language interpretation</strong> connecting the result to your research question</li>
</ol>
<p><strong>One-tailed test caveat:</strong> If you use a one-tailed test (e.g., <span class="math inline">\(H_1: \mu &lt; 40\)</span>) but the sample result goes in the <em>opposite</em> direction, you <strong>still fail to reject</strong> <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Confidence intervals:</strong> A 95% CI alongside your test tells the reader the range of plausible values — pair this with the test whenever you can.</p>
</div>
</div>
</div>
</section>
<section id="test-1-one-sample-t-test-for-a-mean" class="slide level2 smaller scrollable">
<h2>Test 1: One-Sample t-Test for a Mean</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Setup</a></li><li><a href="#tabset-3-2">Formula</a></li><li><a href="#tabset-3-3">R Code</a></li><li><a href="#tabset-3-4">Interpretation</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p><strong>General form of the one-sample t-test:</strong></p>
<p><span class="math display">\[H_0: \mu = \mu_0 \qquad \text{(sample mean equals a specified population value)}\]</span></p>
<p><span class="math inline">\(H_1\)</span> depends on whether the research hypothesis predicts a direction:</p>
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 33%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Alternative</th>
<th>Test type</th>
<th>When to use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_1: \mu \neq \mu_0\)</span></td>
<td><strong>Two-tailed</strong></td>
<td>No predicted direction — default choice</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_1: \mu &gt; \mu_0\)</span></td>
<td>One-tailed (upper)</td>
<td>Theory predicts sample is <em>higher</em> than <span class="math inline">\(\mu_0\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(H_1: \mu &lt; \mu_0\)</span></td>
<td>One-tailed (lower)</td>
<td>Theory predicts sample is <em>lower</em> than <span class="math inline">\(\mu_0\)</span></td>
</tr>
</tbody>
</table>
<hr>
<p><strong>Running example:</strong> Is the mean hours worked per week by U.S. adults equal to 40 hours?</p>
<ul>
<li><span class="math inline">\(H_0: \mu = 40\)</span> — the population mean is 40 hours</li>
<li><span class="math inline">\(H_1: \mu \neq 40\)</span> — the population mean is something other than 40 (two-tailed)</li>
<li>Significance level: <span class="math inline">\(\alpha = 0.05\)</span></li>
</ul>
<p>Under <span class="math inline">\(H_0\)</span>, the test statistic follows a <strong>t-distribution</strong> with <span class="math inline">\(df = n - 1\)</span>:</p>
<p><span class="math display">\[t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}\]</span></p>
</div>
<div id="tabset-3-2">
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>What to compute</th>
<th>Formula/Rule</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span></td>
<td><span class="math inline">\(H_0: \mu = \mu_0\)</span>; choose <span class="math inline">\(H_1\)</span> based on theory</td>
</tr>
<tr class="even">
<td>2</td>
<td><strong>One- or two-tailed?</strong></td>
<td>Does theory predict a direction? → one-tailed; otherwise → two-tailed (default)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Sample mean &amp; SE</td>
<td><span class="math inline">\(\bar{x}\)</span>; <span class="math inline">\(SE = s / \sqrt{n}\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td>t-statistic</td>
<td><span class="math inline">\(t = (\bar{x} - \mu_0) / SE\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td>p-value</td>
<td>See below</td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Step 2 determines the p-value formula:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Two-tailed</strong> (<span class="math inline">\(H_1: \mu \neq \mu_0\)</span>): <code>2 * pt(-abs(t), df = n - 1)</code></li>
<li><strong>One-tailed upper</strong> (<span class="math inline">\(H_1: \mu &gt; \mu_0\)</span>): <code>1 - pt(t, df = n - 1)</code></li>
<li><strong>One-tailed lower</strong> (<span class="math inline">\(H_1: \mu &lt; \mu_0\)</span>): <code>pt(t, df = n - 1)</code></li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-3-3">
<p><code>mu = 40</code> sets the null hypothesis value — R tests whether the true population mean equals 40.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>hrs_clean <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(hrs1))</span>
<span id="cb9-2"><a></a></span>
<span id="cb9-3"><a></a>t1_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(hrs_clean<span class="sc">$</span>hrs1, <span class="at">mu =</span> <span class="dv">40</span>)</span>
<span id="cb9-4"><a></a>t1_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  hrs_clean$hrs1
t = 5.0511, df = 1899, p-value = 0.0000004813
alternative hypothesis: true mean is not equal to 40
95 percent confidence interval:
 41.01450 42.30234
sample estimates:
mean of x 
 41.65842 </code></pre>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the <code>t.test()</code> output:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>t</strong> = 5.05: the sample mean is 5.05 SEs from <span class="math inline">\(\mu_0 = 40\)</span></li>
<li><strong>df</strong> = 1899: degrees of freedom (<span class="math inline">\(n - 1\)</span>)</li>
<li><strong>p-value</strong> = 0: probability of a result this extreme if <span class="math inline">\(H_0\)</span> were true</li>
<li><strong>95% CI</strong>: [41.01, 42.3] — plausible range for the true population mean</li>
<li><strong>mean of x</strong> = 41.66: sample mean <span class="math inline">\(\bar{x}\)</span></li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-3-4">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>How to write up results:</strong></p>
</div>
<div class="callout-content">
<p>State the sample mean, test statistic, p-value, and conclusion:</p>
<p><em>“The mean hours worked per week in the sample was [<code>x̄</code>] hours (SD = s). A one-sample t-test showed this was [significantly / not significantly] different from 40 hours (pvalue = p).”</em></p>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why the reject/fail-to-reject decision matters:</strong></p>
</div>
<div class="callout-content">
<p><strong>When we reject <span class="math inline">\(H_0\)</span>:</strong> the sample result is too unlikely to be explained by chance alone — we conclude there is a real difference in the population, not just sampling noise.</p>
<p><strong>When we fail to reject <span class="math inline">\(H_0\)</span>:</strong> we are <em>not</em> saying the null is true. We simply lack sufficient evidence to doubt it. The effect may be real but small, or the sample too small to detect it — this is why we say “fail to reject,” never “accept.”</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="worked-example-white-san-franciscans-income" class="slide level2 smaller scrollable">
<h2>Worked Example: White San Franciscans’ Income</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Scenario</a></li><li><a href="#tabset-4-2">Step 1 — Hypotheses</a></li><li><a href="#tabset-4-3">Step 2 — One or Two-Tailed?</a></li><li><a href="#tabset-4-4">Step 3 — Test Statistic</a></li><li><a href="#tabset-4-5">Step 4 — p-value and Decision</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p>The mean income for a sample of <span class="math inline">\(n = 100\)</span> White San Franciscans is <strong>$48,000</strong>. The average income for all San Franciscans is <strong>$55,000</strong> (the known population value). The sample standard deviation is <span class="math inline">\(s = \$35,000\)</span>.</p>
<p><strong>Research claim:</strong> We believe that the average income of the <em>population</em> of White San Franciscans is <strong>lower</strong> than the average income of all San Franciscans.</p>
<p><strong>Question:</strong> Write the hypothesis notation and specify whether this is a one- or two-tailed test.</p>
</div>
<div id="tabset-4-2">
<div class="fragment fade-up">
<p><strong>Null hypothesis:</strong> The mean income of White San Franciscans equals the city-wide average:</p>
<p><span class="math display">\[H_0: \mu = \$55{,}000\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Alternative hypothesis:</strong> The mean income of White San Franciscans is <em>lower than</em> the city-wide average:</p>
<p><span class="math display">\[H_1: \mu &lt; \$55{,}000\]</span></p>
</div>
</div>
<div id="tabset-4-3">
<p><strong>One-tailed (lower tail)</strong> — because the research hypothesis makes a specific directional prediction.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The logic:</strong></p>
</div>
<div class="callout-content">
<p>We are not asking whether White San Franciscans earn <em>differently</em> from average San Franciscans — we have a specific prediction: they earn <em>less</em>. So the entire rejection region (<span class="math inline">\(\alpha = 5\%\)</span>) goes in the <strong>lower tail</strong>.</p>
<p>If we had no directional prediction, we would use a two-tailed test.</p>
</div>
</div>
</div>
</div>
<div id="tabset-4-4">
<p><span class="math display">\[SE = \frac{s}{\sqrt{n}} = \frac{35{,}000}{\sqrt{100}} = 3{,}500\]</span></p>
<p><span class="math display">\[t = \frac{\bar{x} - \mu_0}{SE} = \frac{48{,}000 - 55{,}000}{3{,}500} = \frac{-7{,}000}{3{,}500} = -2.0 \qquad (df = n - 1 = 99)\]</span></p>
</div>
<div id="tabset-4-5">
<p>For a <strong>one-tailed lower test</strong>, compute <span class="math inline">\(P(t &lt; -2.0)\)</span> with <span class="math inline">\(df = 99\)</span>:</p>
<p><span class="math display">\[p = \text{pt}(-2.0, \, df = 99) \approx 0.024\]</span></p>
<p>Since <span class="math inline">\(p = 0.024 &lt; \alpha = 0.05\)</span>, we <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Conclusion:</strong></p>
</div>
<div class="callout-content">
<p>The mean income of White San Franciscans in our sample ($48,000) is significantly <em>lower</em> than the average income for all San Franciscans ($55,000) at the 5% significance level (<span class="math inline">\(t\)</span>(99) = −2.0, <span class="math inline">\(p\)</span> = 0.024). We have evidence that this gap is not due to sampling error alone.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="test-2-two-sample-t-test" class="slide level2 smaller scrollable">
<h2>Test 2: Two-Sample t-Test</h2>
<p><strong>Running example:</strong> Do union members work a <em>different</em> number of hours per week than non-members?</p>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Setup</a></li><li><a href="#tabset-5-2">R Code</a></li><li><a href="#tabset-5-3">Visualization</a></li><li><a href="#tabset-5-4">Writing Up Differences</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{\text{union}} = \mu_{\text{non-union}}\)</span> (equivalently: <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>)</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_{\text{union}} \neq \mu_{\text{non-union}}\)</span></li>
</ul>
<p>Under <span class="math inline">\(H_0\)</span>, the test statistic:</p>
<p><span class="math display">\[t = \frac{\bar{x}_1 - \bar{x}_2}{SE_{\text{diff}}} \quad \text{where} \quad SE_{\text{diff}} = \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\]</span></p>
<p>Degrees of freedom: <span class="math inline">\(df \approx n_1 + n_2 - 2\)</span> (R uses Welch’s correction, adjusting df when variances differ)</p>
</div>
<div id="tabset-5-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>union_hrs    <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a></a>  <span class="fu">filter</span>(union_member <span class="sc">==</span> <span class="dv">1</span>, <span class="sc">!</span><span class="fu">is.na</span>(hrs1)) <span class="sc">|&gt;</span> <span class="fu">pull</span>(hrs1)</span>
<span id="cb11-3"><a></a>nonunion_hrs <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a></a>  <span class="fu">filter</span>(union_member <span class="sc">==</span> <span class="dv">0</span>, <span class="sc">!</span><span class="fu">is.na</span>(hrs1), <span class="sc">!</span><span class="fu">is.na</span>(union)) <span class="sc">|&gt;</span> <span class="fu">pull</span>(hrs1)</span>
<span id="cb11-5"><a></a></span>
<span id="cb11-6"><a></a>t2_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(union_hrs, nonunion_hrs)</span>
<span id="cb11-7"><a></a>t2_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  union_hrs and nonunion_hrs
t = 1.8535, df = 316.26, p-value = 0.06475
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.1122722  3.7619461
sample estimates:
mean of x mean of y 
 43.52284  41.69801 </code></pre>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the <code>t.test()</code> output:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>t</strong> = 1.85: test statistic for the difference in means</li>
<li><strong>df</strong> = 316.3: Welch’s adjusted degrees of freedom</li>
<li><strong>p-value</strong> = 0.065: probability of observing a difference this large if <span class="math inline">\(H_0\)</span> is true</li>
<li><strong>95% CI</strong>: [-0.11, 3.76] — plausible range for the true <em>difference</em> in means (<span class="math inline">\(\mu_1 - \mu_2\)</span>)</li>
<li><strong>means</strong>: union = 43.52 hrs, non-union = 41.7 hrs</li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-5-3">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week9_files/figure-revealjs/unnamed-chunk-9-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-4">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Always report the group statistics — not just the test result!</strong></p>
</div>
<div class="callout-content">
<p>When reporting a two-sample test:</p>
<ol type="1">
<li><strong>State the mean of each group</strong> — the reader wants to know <em>which</em> group is higher and <em>how big</em> the gap is</li>
<li><strong>Report the test statistic and p-value</strong></li>
<li><strong>State the decision</strong> — reject or fail to reject</li>
</ol>
<p><em>“Union members worked an average of [x̄₁] hours per week (SD = s₁), compared to [x̄₂] hours for non-members (SD = [s₂]). A two-sample t-test showed this difference was [significant / not significant] (pvalue = p).”</em></p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="test-3-hypothesis-test-for-a-proportion" class="slide level2 smaller scrollable">
<h2>Test 3: Hypothesis Test for a Proportion</h2>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Setup</a></li><li><a href="#tabset-6-2">Formula</a></li><li><a href="#tabset-6-3">R Code</a></li><li><a href="#tabset-6-4">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p><strong>Running example:</strong> Is the proportion of U.S. adults who are union members equal to 20%?</p>
<ul>
<li><span class="math inline">\(H_0: \pi = 0.20\)</span></li>
<li><span class="math inline">\(H_1: \pi \neq 0.20\)</span> (two-tailed)</li>
<li>Significance level: <span class="math inline">\(\alpha = 0.05\)</span></li>
</ul>
<p>Under <span class="math inline">\(H_0\)</span>, the sampling distribution of <span class="math inline">\(\hat{p}\)</span> is approximately:</p>
<p><span class="math display">\[\hat{p} \sim N\!\left(\pi_0,\; SE_0\right) \quad \text{where} \quad SE_0 = \sqrt{\frac{\pi_0(1-\pi_0)}{n}}\]</span></p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Key distinction — testing vs.&nbsp;estimation:</strong></p>
</div>
<div class="callout-content">
<p>When <em>building a CI</em>, use <span class="math inline">\(SE = \sqrt{\hat{p}(1-\hat{p})/n}\)</span> (the sample estimate). When <em>testing a hypothesis</em>, use <span class="math inline">\(SE_0 = \sqrt{\pi_0(1-\pi_0)/n}\)</span> (the <strong>null value</strong>).</p>
</div>
</div>
</div>
</div>
<div id="tabset-6-2">
<p><strong>Step 1:</strong> Compute the standard error <strong>under <span class="math inline">\(H_0\)</span></strong>:</p>
<p><span class="math display">\[SE_0 = \sqrt{\frac{\pi_0(1-\pi_0)}{n}} = \sqrt{\frac{0.20 \times 0.80}{n}}\]</span></p>
<p><strong>Step 2:</strong> Compute the z-statistic:</p>
<p><span class="math display">\[z = \frac{\hat{p} - \pi_0}{SE_0}\]</span></p>
<p><strong>Step 3:</strong> Calculate the p-value:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Test</th>
<th>R code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two-tailed</td>
<td><code>2 * pnorm(-abs(z))</code></td>
</tr>
<tr class="even">
<td>One-tailed (upper)</td>
<td><code>pnorm(-abs(z))</code></td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-6-3">
<p><code>prop.test()</code> handles the SE and test statistic automatically — just supply the count of successes, the sample size, and the null value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>n <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(attain<span class="sc">$</span>union))</span>
<span id="cb13-2"><a></a>x <span class="ot">&lt;-</span> <span class="fu">sum</span>(attain<span class="sc">$</span>union_member, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># number of union members</span></span>
<span id="cb13-3"><a></a></span>
<span id="cb13-4"><a></a><span class="co"># prop.test(successes, n, p = null_value, correct = FALSE)</span></span>
<span id="cb13-5"><a></a>t3_result <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(x, n, <span class="at">p =</span> <span class="fl">0.20</span>, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-6"><a></a>t3_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test without continuity correction

data:  x out of n, null probability 0.2
X-squared = 62.306, df = 1, p-value = 0.000000000000002941
alternative hypothesis: true p is not equal to 0.2
95 percent confidence interval:
 0.1150532 0.1445757
sample estimates:
        p 
0.1290973 </code></pre>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the <code>prop.test()</code> output:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>X-squared</strong> = 62.31: the test statistic (<span class="math inline">\(\chi^2 = z^2\)</span>; equivalent to a z-test for proportions)</li>
<li><strong>p-value</strong> = 0: probability of a proportion this far from 0.20 if <span class="math inline">\(H_0\)</span> were true</li>
<li><strong>95% CI</strong>: [0.115, 0.145] — plausible range for the true population proportion <span class="math inline">\(\pi\)</span></li>
<li><strong>sample estimates: p</strong> = 0.129: your sample proportion <span class="math inline">\(\hat{p}\)</span></li>
</ul>
<p><em>Note: <code>correct = FALSE</code> turns off the continuity correction — appropriate when <span class="math inline">\(n\)</span> is large.</em></p>
</div>
</div>
</div>
</div>
<div id="tabset-6-4">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week9_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions-2" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-3-the-chi-squared-test" class="title-slide slide level1 center">
<h1>Part 3: The Chi-Squared Test</h1>
<p>Testing associations between two categorical variables</p>
</section>
<section id="the-family-of-hypothesis-tests" class="slide level2 smaller">
<h2>The Family of Hypothesis Tests</h2>
<p>Every test we’ve covered this week asks the same fundamental question: <strong>is there a relationship between variables?</strong> The choice of test depends entirely on the <em>types</em> of variables involved.</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>What we’re testing</th>
<th>Outcome variable</th>
<th>Grouping variable</th>
<th>Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Is a proportion = <span class="math inline">\(P\)</span>?</td>
<td>Binary</td>
<td>—</td>
<td>z-test</td>
</tr>
<tr class="even">
<td>Is a mean = <span class="math inline">\(\mu_0\)</span>?</td>
<td>Continuous</td>
<td>—</td>
<td>one-sample t-test</td>
</tr>
<tr class="odd">
<td>Do two group means differ?</td>
<td>Continuous</td>
<td>Binary/categorical</td>
<td><strong>two-sample t-test</strong></td>
</tr>
<tr class="even">
<td>Are two categorical variables independent?</td>
<td>Categorical</td>
<td>Categorical</td>
<td><strong>chi-squared test</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The key decision:</strong></p>
</div>
<div class="callout-content">
<p>Is your outcome variable <strong>continuous</strong>? → use a t-test. Is your outcome variable <strong>categorical</strong>? → use chi-squared.</p>
</div>
</div>
</div>
</section>
<section id="t-tests-vs.-chi-squared-parallel-logic" class="slide level2 smaller">
<h2>t-Tests vs.&nbsp;Chi-Squared: Parallel Logic</h2>
<p>Both tests ask “Is <span class="math inline">\(X\)</span> related to <span class="math inline">\(Y\)</span>?” — for different variable combinations:</p>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Two-Sample t-Test</a></li><li><a href="#tabset-7-2">Chi-Squared</a></li><li><a href="#tabset-7-3">Side-by-Side</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p><strong>Question:</strong> Does the <em>mean</em> of a continuous outcome differ across groups?</p>
<ul>
<li><strong>Outcome:</strong> continuous (e.g., hours worked)</li>
<li><strong>Group:</strong> binary/categorical (e.g., union membership)</li>
<li><strong><span class="math inline">\(H_0\)</span>:</strong> <span class="math inline">\(\mu_{\text{union}} = \mu_{\text{non-union}}\)</span></li>
<li><strong>Test stat:</strong> <span class="math inline">\(t = (\bar{x}_1 - \bar{x}_2) / SE_{\text{diff}}\)</span>, compared to t-distribution</li>
</ul>
<p><em>Our example:</em> Do union members work a different number of hours than non-members?</p>
</div>
<div id="tabset-7-2">
<p><strong>Question:</strong> Does the <em>distribution</em> of a categorical outcome differ across groups?</p>
<ul>
<li><strong>Outcome:</strong> categorical (e.g., union membership — yes/no)</li>
<li><strong>Group:</strong> categorical (e.g., sex)</li>
<li><strong><span class="math inline">\(H_0\)</span>:</strong> Union membership and sex are independent</li>
<li><strong>Test stat:</strong> <span class="math inline">\(\chi^2 = \sum (n_{ij} - \hat{n}_{ij})^2 / \hat{n}_{ij}\)</span>, compared to <span class="math inline">\(\chi^2\)</span> distribution</li>
</ul>
<p><em>Our example:</em> Is union membership associated with sex?</p>
</div>
<div id="tabset-7-3">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Two-sample t-test</th>
<th>Chi-squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><span class="math inline">\(H_0\)</span></strong></td>
<td><span class="math inline">\(\mu_1 = \mu_2\)</span></td>
<td><span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent</td>
</tr>
<tr class="even">
<td><strong>Outcome type</strong></td>
<td>Continuous</td>
<td>Categorical</td>
</tr>
<tr class="odd">
<td><strong>Group type</strong></td>
<td>Binary/categorical</td>
<td>Categorical</td>
</tr>
<tr class="even">
<td><strong>Test statistic</strong></td>
<td><span class="math inline">\(t\)</span></td>
<td><span class="math inline">\(\chi^2\)</span></td>
</tr>
<tr class="odd">
<td><strong>Distribution</strong></td>
<td>t (<span class="math inline">\(df = n_1+n_2-2\)</span>)</td>
<td><span class="math inline">\(\chi^2\)</span> (<span class="math inline">\(df = (I{-}1)(J{-}1)\)</span>)</td>
</tr>
<tr class="even">
<td><strong>Measure of effect</strong></td>
<td>Difference in means</td>
<td>Diff. in proportions / RRR</td>
</tr>
<tr class="odd">
<td><strong>In R</strong></td>
<td><code>t.test(x, y)</code></td>
<td><code>chisq.test(table)</code></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Choosing your test for hw8:</strong></p>
</div>
<div class="callout-content">
<p>Does your research question compare a <strong>continuous</strong> outcome across groups? → two-sample t-test. Does it compare the <strong>rates</strong> of a categorical outcome across groups? → chi-squared.</p>
</div>
</div>
</div>
</section>
<section id="connecting-to-previous-tests" class="slide level2 smaller">
<h2>Connecting to Previous Tests</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>What we’ve tested</th>
<th>Variables</th>
<th>Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Is a proportion = <span class="math inline">\(P\)</span>?</td>
<td>1 binary variable</td>
<td>z-test</td>
</tr>
<tr class="even">
<td>Is a mean = <span class="math inline">\(\mu\)</span>?</td>
<td>1 continuous variable</td>
<td>one-sample t-test</td>
</tr>
<tr class="odd">
<td>Do two groups have the same mean?</td>
<td>1 continuous + 1 binary</td>
<td>two-sample t-test</td>
</tr>
<tr class="even">
<td><strong>Are two categorical variables independent?</strong></td>
<td><strong>2 categorical variables</strong></td>
<td><strong>Chi-squared test</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Today’s question:</strong></p>
</div>
<div class="callout-content">
<p>Is gender associated with union membership? Are race and environmental attitudes related? These questions involve <strong>two categorical variables</strong> — we need a new tool.</p>
</div>
</div>
</div>
</section>
<section id="review-contingency-tables" class="slide level2 smaller scrollable">
<h2>Review: Contingency Tables</h2>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">What Is a Contingency Table?</a></li><li><a href="#tabset-8-2">Relative Frequencies</a></li><li><a href="#tabset-8-3">In R</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>A <strong>contingency table</strong> shows the joint distribution of two categorical variables — counts of observations in each combination of categories</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Non-member</th>
<th>Union member</th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Female</strong></td>
<td><span class="math inline">\(n_{11}\)</span></td>
<td><span class="math inline">\(n_{12}\)</span></td>
<td><span class="math inline">\(n_{1\bullet}\)</span></td>
</tr>
<tr class="even">
<td><strong>Male</strong></td>
<td><span class="math inline">\(n_{21}\)</span></td>
<td><span class="math inline">\(n_{22}\)</span></td>
<td><span class="math inline">\(n_{2\bullet}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><span class="math inline">\(n_{\bullet 1}\)</span></td>
<td><span class="math inline">\(n_{\bullet 2}\)</span></td>
<td><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-8-2">
<p><strong>Relative (marginal) frequency</strong>: the proportion of one variable’s categories, <em>within</em> categories of another variable</p>
<p><span class="math display">\[p_{X=i \mid Y=j} = \frac{n_{X=i,\, Y=j}}{n_{Y=j}}\]</span></p>
<p><strong>Example:</strong> Among female respondents, what proportion are union members?</p>
<p><span class="math display">\[p_{\text{union} \mid \text{female}} = \frac{n_{\text{union, female}}}{n_{\text{female}}}\]</span></p>
</div>
<div id="tabset-8-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>attain_ct <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(union), <span class="sc">!</span><span class="fu">is.na</span>(sex)) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a></a>  <span class="fu">mutate</span>(<span class="at">union_lab =</span> <span class="fu">if_else</span>(union_member <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Union"</span>, <span class="st">"Non-member"</span>))</span>
<span id="cb15-4"><a></a></span>
<span id="cb15-5"><a></a><span class="co"># Absolute frequency table</span></span>
<span id="cb15-6"><a></a>tab <span class="ot">&lt;-</span> <span class="fu">table</span>(attain_ct<span class="sc">$</span>sex, attain_ct<span class="sc">$</span>union_lab)</span>
<span id="cb15-7"><a></a><span class="fu">addmargins</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         Non-member Union  Sum
  female       1003   105 1108
  male          724   151  875
  Sum          1727   256 1983</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="co"># Row proportions: union membership rate within each sex</span></span>
<span id="cb17-2"><a></a><span class="fu">round</span>(<span class="fu">prop.table</span>(tab, <span class="at">margin =</span> <span class="dv">1</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         Non-member Union
  female      0.905 0.095
  male        0.827 0.173</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-chi-squared-logic" class="slide level2 smaller">
<h2>The Chi-Squared Logic</h2>
<div class="fragment fade-up">
<p><strong>The null hypothesis:</strong> The two categorical variables are <strong>independent</strong> — knowing someone’s category on one variable tells us nothing about their category on the other</p>
<p><span class="math display">\[H_0: \text{no association between } X \text{ and } Y\]</span></p>
</div>
<div class="fragment fade-up">
<p><strong>Under independence</strong>, the expected count in each cell:</p>
<p><span class="math display">\[\hat{n}_{ij} = \frac{(\text{row total}_i) \times (\text{column total}_j)}{n}\]</span></p>
<p>This is what the table <em>would look like</em> if the two variables had no relationship at all.</p>
</div>
<div class="fragment fade-up">
<p><strong>The test asks:</strong> Are the <em>observed</em> cell counts far enough from the <em>expected</em> cell counts that we doubt independence?</p>
</div>
</section>
<section id="the-chi-squared-test-statistic" class="slide level2 smaller">
<h2>The Chi-Squared Test Statistic</h2>
<p><span class="math display">\[\chi^2 = \sum_{i}\sum_{j} \frac{(n_{ij} - \hat{n}_{ij})^2}{\hat{n}_{ij}}\]</span></p>
<p>where <span class="math inline">\(n_{ij}\)</span> = observed and <span class="math inline">\(\hat{n}_{ij}\)</span> = expected count in cell <span class="math inline">\((i, j)\)</span></p>
<div class="fragment fade-up">
<ul>
<li><strong>Large <span class="math inline">\(\chi^2\)</span></strong>: observed counts are far from expected → evidence against independence</li>
<li><strong>Small <span class="math inline">\(\chi^2\)</span></strong>: observed counts are close to expected → consistent with independence</li>
<li><strong>Degrees of freedom</strong>: <span class="math inline">\((I-1)(J-1)\)</span>, where <span class="math inline">\(I\)</span> = number of rows, <span class="math inline">\(J\)</span> = number of columns</li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Assumptions:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Data are a random sample from the population</li>
<li>Expected count in <strong>each cell ≥ 5</strong> — if not, the chi-squared approximation may not be reliable</li>
</ol>
</div>
</div>
</div>
</div>
</section>
<section id="worked-example-1-sex-and-union-membership" class="slide level2 smaller scrollable">
<h2>Worked Example 1: Sex and Union Membership</h2>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Contingency Table</a></li><li><a href="#tabset-9-2">Expected Counts</a></li><li><a href="#tabset-9-3">Chi-Squared Test</a></li><li><a href="#tabset-9-4">Interpretation</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p><strong>Research question:</strong> Is there a significant association between sex and union membership?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>tab <span class="ot">&lt;-</span> <span class="fu">table</span>(attain_ct<span class="sc">$</span>sex, attain_ct<span class="sc">$</span>union_lab)</span>
<span id="cb19-2"><a></a><span class="fu">addmargins</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         Non-member Union  Sum
  female       1003   105 1108
  male          724   151  875
  Sum          1727   256 1983</code></pre>
</div>
</div>
</div>
<div id="tabset-9-2">
<p>Under <span class="math inline">\(H_0\)</span> (independence), expected count = (row total × column total) / <span class="math inline">\(n\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>chisq_result <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tab, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-2"><a></a><span class="fu">round</span>(chisq_result<span class="sc">$</span>expected, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         Non-member Union
  female        965   143
  male          762   113</code></pre>
</div>
</div>
<p><em>All expected counts ≥ 5? The chi-squared approximation is valid if so.</em></p>
</div>
<div id="tabset-9-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a><span class="fu">chisq.test</span>(tab, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab
X-squared = 26.325, df = 1, p-value = 0.0000002886</code></pre>
</div>
</div>
<p><em><code>correct = FALSE</code> turns off Yates’ continuity correction — standard for 2×2 tables when all expected counts ≥ 5</em></p>
</div>
<div id="tabset-9-4">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>How to interpret chi-squared:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Reject <span class="math inline">\(H_0\)</span></strong> (<span class="math inline">\(p &lt; 0.05\)</span>): significant association between sex and union membership</li>
<li><strong>Fail to reject <span class="math inline">\(H_0\)</span></strong> (<span class="math inline">\(p \geq 0.05\)</span>): data are consistent with independence</li>
</ul>
<p><strong>Important:</strong> The chi-squared test only tells you <em>whether</em> there is an association — <strong>not how strong</strong> it is or <strong>which direction</strong>. For that, you need measures of association.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="worked-example-2-sex-and-educational-attainment" class="slide level2 smaller scrollable">
<h2>Worked Example 2: Sex and Educational Attainment</h2>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Setup</a></li><li><a href="#tabset-10-2">R Code</a></li><li><a href="#tabset-10-3">Measures</a></li><li><a href="#tabset-10-4">Interpretation</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p><strong>Research question:</strong> Is there a significant association between sex and having a college degree?</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Sex and college attainment are <strong>independent</strong> — knowing someone’s sex tells us nothing about whether they have a degree</li>
<li><span class="math inline">\(H_1\)</span>: Sex and college attainment are <strong>not independent</strong> — there is an association</li>
<li>Significance level: <span class="math inline">\(\alpha = 0.05\)</span></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>No college degree</th>
<th>College degree</th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Female</strong></td>
<td>?</td>
<td>?</td>
<td>?</td>
</tr>
<tr class="even">
<td><strong>Male</strong></td>
<td>?</td>
<td>?</td>
<td>?</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-10-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="co"># Create binary college degree variable</span></span>
<span id="cb25-2"><a></a>attain_deg <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(sex), <span class="sc">!</span><span class="fu">is.na</span>(degree)) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a></a>  <span class="fu">mutate</span>(<span class="at">college =</span> <span class="fu">if_else</span>(degree <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"bachelor"</span>, <span class="st">"graduate"</span>), <span class="st">"College+"</span>, <span class="st">"No college"</span>))</span>
<span id="cb25-5"><a></a></span>
<span id="cb25-6"><a></a>tab2 <span class="ot">&lt;-</span> <span class="fu">table</span>(attain_deg<span class="sc">$</span>sex, attain_deg<span class="sc">$</span>college)</span>
<span id="cb25-7"><a></a><span class="fu">addmargins</span>(tab2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         College+ No college  Sum
  female      382       1316 1698
  male        331        953 1284
  Sum         713       2269 2982</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="co"># Verify expected counts ≥ 5</span></span>
<span id="cb27-2"><a></a><span class="fu">round</span>(<span class="fu">chisq.test</span>(tab2, <span class="at">correct =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>expected, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         College+ No college
  female      406       1292
  male        307        977</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a><span class="co"># Run the chi-squared test</span></span>
<span id="cb29-2"><a></a><span class="fu">chisq.test</span>(tab2, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab2
X-squared = 4.3281, df = 1, p-value = 0.03749</code></pre>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the output:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>X-squared</strong>: the <span class="math inline">\(\chi^2\)</span> test statistic</li>
<li><strong>df</strong>: <span class="math inline">\((I-1)(J-1) = (2-1)(2-1) = 1\)</span> for a 2×2 table</li>
<li><strong>p-value</strong>: probability of a <span class="math inline">\(\chi^2\)</span> this large if sex and degree were independent</li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-10-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>tab_rel2     <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(tab2, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb31-2"><a></a><span class="fu">round</span>(tab_rel2, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         College+ No college
  female    0.225      0.775
  male      0.258      0.742</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>diff_college <span class="ot">&lt;-</span> tab_rel2[<span class="st">"female"</span>, <span class="st">"College+"</span>] <span class="sc">-</span> tab_rel2[<span class="st">"male"</span>, <span class="st">"College+"</span>]</span>
<span id="cb33-2"><a></a>rr_college   <span class="ot">&lt;-</span> tab_rel2[<span class="st">"female"</span>, <span class="st">"College+"</span>] <span class="sc">/</span> tab_rel2[<span class="st">"male"</span>, <span class="st">"College+"</span>]</span>
<span id="cb33-3"><a></a></span>
<span id="cb33-4"><a></a><span class="fu">cat</span>(<span class="st">"College rate — female:"</span>, <span class="fu">round</span>(tab_rel2[<span class="st">"female"</span>, <span class="st">"College+"</span>], <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>College rate — female: 0.225 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a><span class="fu">cat</span>(<span class="st">"College rate — male:  "</span>, <span class="fu">round</span>(tab_rel2[<span class="st">"male"</span>,   <span class="st">"College+"</span>], <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>College rate — male:   0.258 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Difference in proportions:"</span>, <span class="fu">round</span>(diff_college, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Difference in proportions: -0.033 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a><span class="fu">cat</span>(<span class="st">"Relative risk ratio:      "</span>, <span class="fu">round</span>(rr_college,   <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Relative risk ratio:       0.873 </code></pre>
</div>
</div>
</div>
<div id="tabset-10-4">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>How to write up the result:</strong></p>
</div>
<div class="callout-content">
<p>Report the association direction, the chi-squared statistic, df, p-value, and a measure of effect:</p>
<p><em>“Women were [X] percentage points [more / less] likely than men to have a college degree (difference in proportions = [X]). A chi-squared test showed this association was [significant / not significant] (<span class="math inline">\(\chi^2\)</span>(1) = [value], <span class="math inline">\(p\)</span> = [p]).”</em></p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="writing-up-chi-squared-results" class="slide level2 smaller">
<h2>Writing Up Chi-Squared Results</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A complete chi-squared write-up includes:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Description of the table</strong>: e.g., “Table 1 shows the distribution of union membership by sex”</li>
<li><strong>Chi-squared statistic and p-value</strong>: <span class="math inline">\(\chi^2\)</span>(df) = [value], <span class="math inline">\(p\)</span> = [value]</li>
<li><strong>Decision</strong>: reject or fail to reject <span class="math inline">\(H_0\)</span></li>
<li><strong>A measure of association</strong> describing the <em>direction</em> and <em>magnitude</em> of the relationship</li>
<li><strong>Plain-language interpretation</strong> tied to the research question</li>
</ol>
<p><em>Example: “Men were [X] percentage points more likely to be union members than women (difference in proportions = [X]). A chi-squared test showed this association was [significant / not significant] (<span class="math inline">\(\chi^2\)</span>(1) = [value], <span class="math inline">\(p\)</span> = [p]).”</em></p>
</div>
</div>
</div>
</section>
<section id="questions-3" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="key-takeaways" class="slide level2 smaller">
<h2>Key Takeaways</h2>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">Part 1 — Logic</a></li><li><a href="#tabset-11-2">Part 2 — t-Tests</a></li><li><a href="#tabset-11-3">Part 3 — Chi-Squared</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<ul>
<li>A hypothesis test asks: <em>if <span class="math inline">\(H_0\)</span> were true, how likely is our data?</em></li>
<li>The <strong>p-value</strong> is P(data this extreme | <span class="math inline">\(H_0\)</span> true) — NOT the probability <span class="math inline">\(H_0\)</span> is true</li>
<li>Reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(p &lt; \alpha\)</span>; fail to reject (not “accept”) when <span class="math inline">\(p \geq \alpha\)</span></li>
<li>Default to two-tailed; one-tailed only with strong pre-specified directional theory</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Connection to Week 8:</strong></p>
</div>
<div class="callout-content">
<p>If the 95% CI <strong>does not contain</strong> <span class="math inline">\(\mu_0\)</span> → reject <span class="math inline">\(H_0\)</span> at <span class="math inline">\(\alpha = 0.05\)</span>. Tests and CIs are two sides of the same coin.</p>
</div>
</div>
</div>
</div>
<div id="tabset-11-2">
<ul>
<li><strong>One-sample t-test</strong>: <span class="math inline">\(t = (\bar{x} - \mu_0) / (s/\sqrt{n})\)</span>; use <code>t.test(x, mu = μ₀)</code></li>
<li><strong>Two-sample t-test</strong>: compare group means; use <code>t.test(x, y)</code></li>
<li><strong>Proportion test</strong>: use <code>prop.test(x, n, p = π₀)</code> — SE uses <strong>null value</strong> <span class="math inline">\(\pi_0\)</span></li>
</ul>
<p>Always report: sample statistic, t (or z), p-value, and a plain-language conclusion.</p>
</div>
<div id="tabset-11-3">
<ul>
<li>Tests independence of two <strong>categorical</strong> variables</li>
<li><span class="math inline">\(\chi^2 = \sum (n_{ij} - \hat{n}_{ij})^2 / \hat{n}_{ij}\)</span>; use <code>chisq.test(table)</code></li>
<li>All expected counts must be ≥ 5</li>
<li>Chi-squared says <em>whether</em> there’s an association — not direction or strength</li>
<li>Always supplement with <strong>difference in proportions</strong> or <strong>RRR</strong></li>
</ul>
</div>
</div>
</div>
</section>
<section id="why-this-matters-for-the-rest-of-the-course" class="slide level2 smaller">
<h2>Why This Matters for the Rest of the Course</h2>
<ul>
<li><strong>Weeks 10–13 (Regression):</strong> OLS is essentially the two-sample t-test extended to multiple variables simultaneously. Every regression coefficient comes with its own t-test and p-value — built on exactly the same logic we used today.</li>
<li><strong>Your research paper:</strong> You will almost certainly use regression. But the interpretation of <span class="math inline">\(p\)</span>-values, test statistics, and significance thresholds is <em>identical</em> to what we covered today.</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Key takeaway:</strong></p>
</div>
<div class="callout-content">
<p>Hypothesis testing is not just a tool for this week — it is the core inferential logic running through all of statistics. Every result in your paper will be evaluated with the same p-value framework we built today.</p>
</div>
</div>
</div>
</section>
<section id="questions-4" class="slide level2">
<h2>Questions?</h2>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://www.kaseyzapatka.com/soc106">GitHub course repo</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>