<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-04-14">
  <title>Sociology 106 – Week 13</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="slides.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 13</h1>
  <p class="subtitle">Sociology 106: Quantitative Sociological Methods</p>

<div class="quarto-title-authors">
</div>

  <p class="date">April 14, 2026</p>
</section>
<section id="agenda" class="slide level2 smaller">
<h2>Agenda</h2>
<p><strong>Housekeeping:</strong></p>
<ul>
<li>HW #10, HW #11, Revised Proposal with Outline</li>
</ul>
<p><strong>Statistical content — two parts:</strong></p>
<ul>
<li><strong>Part 1</strong>: Controlling for confounders — closing back doors in regression</li>
<li><strong>Part 2</strong>: Interaction effects — when the relationship depends on context</li>
</ul>
<p><strong>Reading discussion:</strong></p>
<ul>
<li>Thompson &amp; Keith (2001) — interactions in a classic race &amp; gender study</li>
</ul>
<p><strong>In-class lab:</strong></p>
<ul>
<li>Running interactions on your research data</li>
</ul>
</section>
<section id="housekeeping" class="slide level2 smaller">
<h2>Housekeeping</h2>
<p><strong>Weekly Assignment #10</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 23</span></li>
<li>Logistic regression on a binary outcome — covered last week</li>
</ul>
<p><strong>Weekly Assignment #11</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 23</span></li>
<li>Run an interaction analysis on your research data (see Assignments slide)</li>
</ul>
<p><strong>Revised Proposal with Outline</strong></p>
<ul>
<li><span class="highlight">Due Thursday, April 16</span> — two days away!</li>
<li>Describe whether your analysis will include any controls or interaction terms</li>
</ul>
<p><strong>In-class presentations</strong></p>
<ul>
<li><span class="highlight">April 28</span> — 7–10 minutes per student will give you slide template</li>
</ul>
</section>
<section id="where-we-are-in-the-course" class="slide level2 smaller">
<h2>Where We Are in the Course</h2>
<ul>
<li><strong>Week 11:</strong> OLS regression — how <em>strong</em> is the linear relationship between X and Y?</li>
<li><strong>Week 12:</strong> Logistic regression — predicting <em>binary</em> outcomes</li>
<li><strong>This week (Week 13):</strong> Extensions — controlling for confounders and interaction effects</li>
<li><strong>Next week (Week 14):</strong> More extensions — mediation and wrap-up</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The big picture: from association to causal story</strong></p>
</div>
<div class="callout-content">
<p>Weeks 11–12 asked: <em>“Is there a relationship between X and Y?”</em> This week asks: <em>“Is that relationship spurious? And does it work the same way for everyone — or does it depend on who you are?”</em> These questions bring us closer to <strong>causal inference</strong> and to understanding the social <strong>mechanisms</strong> behind the patterns we observe.</p>
</div>
</div>
</div>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
</section>
<section>
<section id="part-1-controls-and-confounding" class="title-slide slide level1 center">
<h1>Part 1: Controls and Confounding</h1>
<p>Closing the back door</p>
</section>
<section id="why-we-add-control-variables" class="slide level2 smaller">
<h2>Why We Add Control Variables</h2>
<p>We want to estimate the <strong>“causal” effect</strong> of X on Y. Three conditions for causality:</p>
<div class="fragment fade-up">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>What it means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. Correlation</strong></td>
<td>X and Y are statistically associated</td>
</tr>
<tr class="even">
<td><strong>2. Temporal priority</strong></td>
<td>X comes before Y in time</td>
</tr>
<tr class="odd">
<td><strong>3. Non-spuriousness</strong></td>
<td>No third variable Z is creating a false association between X and Y</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment fade-up">
<p>A <strong>confounding variable</strong> Z:</p>
<ul>
<li>Has a causal effect on X (Z → X)</li>
<li>Has a causal effect on Y (Z → Y)</li>
<li>Comes <em>before</em> both X and Y in time</li>
<li>Creates a spurious statistical association between X and Y</li>
</ul>
<p>We remove the confound by <strong>controlling for Z</strong> in the regression: <code>lm(Y ~ X + Z)</code></p>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What “controlling for Z” actually means</strong></p>
</div>
<div class="callout-content">
<p>Adding Z to the regression asks: <em>“Among people with the same value of Z, what is the relationship between X and Y?”</em> We are comparing like to like.</p>
</div>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>This is the foundation — but causal inference is harder</strong></p>
</div>
<div class="callout-content">
<p>What we’re doing here is the workhorse strategy for observational causal inference. But it has real limits: we can only control for variables we <strong>actually observe and measure</strong>. Unmeasured confounders still bias our estimates — and we can never fully rule them out with regression alone.</p>
<p>Modern methods designed for this problem include: <strong>difference-in-differences</strong> (exploiting before/after comparisons), <strong>regression discontinuity</strong> (exploiting thresholds), and <strong>instrumental variables</strong> (finding exogenous variation in X). This course builds the logic; methods courses go deeper. For now: controlling for observed confounders is good practice, but <em>“I controlled for everything”</em> is always a theoretical claim, not a statistical guarantee.</p>
</div>
</div>
</div>
</div>
</section>
<section id="confounding-the-path-model" class="slide level2 smaller">
<h2>Confounding: The Path Model</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Without controlling for Z, we observe a statistical association between X and Y. But that association is <strong>partly due to Z’s effects on both</strong> — not just the direct X → Y path.</p>
<div class="fragment fade-up">
<p><strong>Our running example:</strong></p>
<ul>
<li><strong>X</strong> = Years of education</li>
<li><strong>Y</strong> = Income (1991)</li>
<li><strong>Z</strong> = Sex (a potential confounder)</li>
</ul>
<p>Men and women may differ in both education level (Z → X) and in income (Z → Y). If we don’t control for sex, part of what looks like an “education effect” is really a “sex effect.”</p>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week13_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="a-classic-example-computers-and-test-scores" class="slide level2 smaller scrollable">
<h2>A Classic Example: Computers and Test Scores</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">The Setup</a></li><li><a href="#tabset-1-2">The Resolution</a></li><li><a href="#tabset-1-3">What to Control For</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>In the early 1990s, researchers found: households with home computers had children with higher math test scores.</p>
<p>Does <strong>computer ownership cause</strong> better academic performance?</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week13_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2">
<p><strong>Social class</strong> caused both computer ownership <em>and</em> math achievement — it was the confound:</p>
<ul>
<li>Higher-class families could afford computers (Z → X)</li>
<li>Higher-class families also provided better academic resources (Z → Y)</li>
</ul>
<p>When researchers controlled for social class — comparing families at the same class level — the computer–test score correlation <strong>vanished</strong>.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The general lesson:</strong></p>
</div>
<div class="callout-content">
<p>A variable Z is a <strong>confounder</strong> if: (1) Z → X, (2) Z → Y, and (3) Z precedes both X and Y in time. To remove its influence, we add Z to the regression: <code>lm(Y ~ X + Z)</code>. Once we do this, we estimate the effect of X <em>within levels of Z</em> — comparing like with like.</p>
</div>
</div>
</div>
</div>
<div id="tabset-1-3">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A critical warning: not everything should be controlled</strong></p>
</div>
<div class="callout-content">
<p>Only control for variables that: 1. Come <em>before</em> X and Y in time (prior common causes) 2. Are not themselves caused by X (otherwise you create new bias)</p>
<p><strong>Do NOT control for:</strong></p>
<ul>
<li><strong>Mediators</strong> (variables on the X → Y causal path) — this would <em>underestimate</em> X’s total effect</li>
<li><strong>Colliders</strong> (variables caused by <em>both</em> X and Y) — this actually introduces new bias</li>
</ul>
<p>For now: include controls that have a plausible prior causal connection to both your X and Y. We’ll cover mediation — and why you shouldn’t control for it — in Week 14.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="controlling-for-confounders-in-r" class="slide level2 smaller scrollable">
<h2>Controlling for Confounders in R</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">The Code</a></li><li><a href="#tabset-2-2">Model Comparison</a></li><li><a href="#tabset-2-3">Interpretation</a></li><li><a href="#tabset-2-4">Partial Regression Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># Bivariate: education → income</span></span>
<span id="cb1-2"><a></a>model_biv     <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> educ,               <span class="at">data =</span> attain_sub)</span>
<span id="cb1-3"><a></a></span>
<span id="cb1-4"><a></a><span class="co"># Control for sex</span></span>
<span id="cb1-5"><a></a>model_control <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> educ <span class="sc">+</span> sex_f,       <span class="at">data =</span> attain_sub)</span>
<span id="cb1-6"><a></a></span>
<span id="cb1-7"><a></a><span class="co"># Control for sex + age</span></span>
<span id="cb1-8"><a></a>model_multi   <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> educ <span class="sc">+</span> sex_f <span class="sc">+</span> age, <span class="at">data =</span> attain_sub)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Adding variables with <code>+</code> holds each one <strong>constant</strong> while estimating the others.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpreting the education coefficient across models:</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Bivariate model:</strong> effect of education, ignoring sex and age</li>
<li><strong>+Sex model:</strong> effect of education <em>among people of the same sex</em></li>
<li><strong>+Sex+Age model:</strong> effect of education <em>among people of the same sex and age</em></li>
</ul>
<p>Each model answers a slightly different question.</p>
</div>
</div>
</div>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">modelsummary</span>(</span>
<span id="cb2-2"><a></a>  <span class="fu">list</span>(<span class="st">"Bivariate"</span>    <span class="ot">=</span> model_biv,</span>
<span id="cb2-3"><a></a>       <span class="st">"+ Sex"</span>        <span class="ot">=</span> model_control,</span>
<span id="cb2-4"><a></a>       <span class="st">"+ Sex + Age"</span>  <span class="ot">=</span> model_multi),</span>
<span id="cb2-5"><a></a>  <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>  <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb2-6"><a></a>                  <span class="st">"educ"</span>         <span class="ot">=</span> <span class="st">"Years of Education"</span>,</span>
<span id="cb2-7"><a></a>                  <span class="st">"sex_ffemale"</span>  <span class="ot">=</span> <span class="st">"Female"</span>,</span>
<span id="cb2-8"><a></a>                  <span class="st">"age"</span>          <span class="ot">=</span> <span class="st">"Age"</span>),</span>
<span id="cb2-9"><a></a>  <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb2-10"><a></a>  <span class="at">fmt     =</span> <span class="dv">0</span>,</span>
<span id="cb2-11"><a></a>  <span class="at">title   =</span> <span class="st">"OLS: Income by Education (with Controls)"</span>,</span>
<span id="cb2-12"><a></a>  <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>, <span class="st">"adj.r.squared"</span>)</span>
<span id="cb2-13"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>OLS: Income by Education (with Controls)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Bivariate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">+ Sex</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">+ Sex + Age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">−9830**</td>
<td style="text-align: center;">−7092*</td>
<td style="text-align: center;">−13468**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(3468)</td>
<td style="text-align: center;">(3557)</td>
<td style="text-align: center;">(4562)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Years of Education</td>
<td style="text-align: center;">3881***</td>
<td style="text-align: center;">3877***</td>
<td style="text-align: center;">4006***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(254)</td>
<td style="text-align: center;">(254)</td>
<td style="text-align: center;">(260)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−4919***</td>
<td style="text-align: center;">−4984***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(1472)</td>
<td style="text-align: center;">(1471)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">104*</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(47)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2517</td>
<td style="text-align: center;">2517</td>
<td style="text-align: center;">2517</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.085</td>
<td style="text-align: center;">0.089</td>
<td style="text-align: center;">0.091</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.084</td>
<td style="text-align: center;">0.088</td>
<td style="text-align: center;">0.090</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<div id="tabset-2-3">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the controls table:</strong></p>
</div>
<div class="callout-content">
<p><strong>Education coefficient:</strong> In the bivariate model, each additional year of education is associated with a <strong>$3,881</strong> increase in income. After controlling for sex, the coefficient is <strong>$3,877</strong>, and after controlling for both sex and age, it is <strong>$4,006</strong>.</p>
<p><strong>Female coefficient:</strong> After controlling for education, women earn approximately <strong>$4,919</strong> less than men. This is the <strong>direct effect</strong> of sex on income, <em>holding education constant</em> — evidence of a gender wage gap that is not explained by differences in educational attainment.</p>
<p><strong>R² increases</strong> as we add controls. But more controls ≠ always better. Only include theoretically motivated confounders.</p>
</div>
</div>
</div>
</div>
<div id="tabset-2-4">
<p>The added variable (partial regression) plot shows the education–income relationship <em>after</em> removing the variation explained by sex:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Residualize both income and education on sex</span></span>
<span id="cb3-2"><a></a>resid_inc  <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(income91 <span class="sc">~</span> sex_f, <span class="at">data =</span> attain_sub))</span>
<span id="cb3-3"><a></a>resid_educ <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(educ    <span class="sc">~</span> sex_f, <span class="at">data =</span> attain_sub))</span>
<span id="cb3-4"><a></a></span>
<span id="cb3-5"><a></a><span class="fu">tibble</span>(<span class="at">educ_net_sex =</span> resid_educ, <span class="at">income_net_sex =</span> resid_inc) <span class="sc">|&gt;</span></span>
<span id="cb3-6"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> educ_net_sex, <span class="at">y =</span> income_net_sex)) <span class="sc">+</span></span>
<span id="cb3-7"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.25</span>, <span class="at">color =</span> <span class="st">"gray50"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"#4E79A7"</span>, <span class="at">linewidth =</span> <span class="fl">1.4</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb3-10"><a></a>    <span class="at">title   =</span> <span class="st">"Partial regression plot: education → income, net of sex"</span>,</span>
<span id="cb3-11"><a></a>    <span class="at">subtitle =</span> <span class="st">"Each axis is residualized — sex's influence removed from both variables"</span>,</span>
<span id="cb3-12"><a></a>    <span class="at">x =</span> <span class="st">"Education (residualized on sex)"</span>,</span>
<span id="cb3-13"><a></a>    <span class="at">y =</span> <span class="st">"Income (residualized on sex)"</span></span>
<span id="cb3-14"><a></a>  ) <span class="sc">+</span></span>
<span id="cb3-15"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week13_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions-1" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="part-2-interaction-effects" class="title-slide slide level1 center">
<h1>Part 2: Interaction Effects</h1>
<p>When the relationship depends on who you are</p>
</section>
<section id="what-is-moderation" class="slide level2 smaller">
<h2>What is Moderation?</h2>
<p>Sometimes, the <strong>effect of X on Y is not the same for everyone</strong> — it varies depending on a third variable Z.</p>
<div class="fragment fade-up">
<p>We call this <strong>moderation</strong> (or an <strong>interaction effect</strong>): - Z <strong>moderates</strong> the relationship between X and Y - The effect of X on Y <strong>depends on the value of Z</strong></p>
<p><strong>Sociological examples:</strong></p>
<ul>
<li>Does education pay off the same for men and women? <em>(education × sex → income)</em></li>
<li>Does income affect health the same across racial groups? <em>(income × race → health)</em></li>
<li>Does job training help during recessions or only during expansions? <em>(training × economy → employment)</em></li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Moderation vs.&nbsp;Confounding — critical distinction</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Confounding</th>
<th>Moderation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>What Z does</strong></td>
<td>Creates spurious X–Y association</td>
<td>Changes the <em>size</em> of the X → Y effect</td>
</tr>
<tr class="even">
<td><strong>Goal</strong></td>
<td>Remove Z’s bias by controlling</td>
<td>Model the <em>heterogeneity</em> across Z</td>
</tr>
<tr class="odd">
<td><strong>Model</strong></td>
<td><code>Y ~ X + Z</code></td>
<td><code>Y ~ X + Z + X:Z</code></td>
</tr>
<tr class="even">
<td><strong>Question</strong></td>
<td>“What is X’s effect, net of Z?”</td>
<td>“Is X’s effect different for different values of Z?”</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</section>
<section id="parallel-vs.-non-parallel-slopes" class="slide level2 smaller">
<h2>Parallel vs.&nbsp;Non-Parallel Slopes</h2>
<p>The key visual difference between a model <strong>without</strong> an interaction and one <strong>with</strong> an interaction:</p>

<img data-src="week13_files/figure-revealjs/unnamed-chunk-7-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The key visual test for an interaction:</strong></p>
</div>
<div class="callout-content">
<p>In the <strong>no-interaction model</strong> (<code>Y ~ X + Z</code>), the lines are parallel — the same slope for every group. In the <strong>interaction model</strong> (<code>Y ~ X * Z</code>), the slopes differ. <strong>The lines don’t need to cross — they just need to be non-parallel.</strong> Even a slight divergence (one slope steeper than the other) constitutes an interaction. The interaction term’s statistical significance tells us whether that difference in slopes is real or due to sampling noise.</p>
</div>
</div>
</div>
</section>
<section id="the-interaction-model" class="slide level2 smaller">
<h2>The Interaction Model</h2>
<p>To model an interaction, we add the <strong>product</strong> of the two predictors:</p>
<p><span class="math display">\[\hat{Y} = \alpha + \beta_1 X_1 + \beta_2 X_2 + \beta_3 (X_1 \times X_2)\]</span></p>
<div class="fragment fade-up">
<p><strong>What each coefficient means when <span class="math inline">\(X_2\)</span> is binary (0 = reference, 1 = other):</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta_1\)</span></td>
<td>Effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span> <strong>for the reference group</strong> (<span class="math inline">\(X_2 = 0\)</span>)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_2\)</span></td>
<td>Difference in baseline <span class="math inline">\(Y\)</span> for <span class="math inline">\(X_2 = 1\)</span> vs.&nbsp;<span class="math inline">\(X_2 = 0\)</span> (when <span class="math inline">\(X_1 = 0\)</span>)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_3\)</span></td>
<td><strong>The interaction:</strong> how much the effect of <span class="math inline">\(X_1\)</span> <em>changes</em> when <span class="math inline">\(X_2 = 1\)</span> instead of 0</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Computing the effect for each group:</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[\text{Effect of } X_1 \text{ for reference group: } \hat\beta_1\]</span> <span class="math display">\[\text{Effect of } X_1 \text{ for other group: } \hat\beta_1 + \hat\beta_3\]</span></p>
<p><span class="math inline">\(\hat\beta_3\)</span> is the <strong>difference in slopes</strong> between the two groups. If <span class="math inline">\(\hat\beta_3 = 0\)</span>, the slopes are identical — no interaction.</p>
</div>
</div>
</div>
</div>
<div class="fragment fade-up">
<p><strong>In R:</strong> use <code>*</code> to include both main effects and the interaction term:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">*</span> X2, <span class="at">data =</span> my_data)    <span class="co"># = Y ~ X1 + X2 + X1:X2</span></span>
<span id="cb4-2"><a></a><span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X1<span class="sc">:</span>X2, <span class="at">data =</span> my_data)  <span class="co"># same thing, written out</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment fade-up">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Always include lower-order (main effect) terms</strong></p>
</div>
<div class="callout-content">
<p><strong>A critical rule:</strong> whenever you include an interaction term <span class="math inline">\(X_1 \times X_2\)</span>, you must <em>also</em> include the main effects <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> as separate terms in the same model. This is called the <strong>hierarchy principle</strong>.</p>
<p>Using <code>Y ~ X1 * X2</code> in R enforces this automatically — it expands to <code>Y ~ X1 + X2 + X1:X2</code>. Never use <code>Y ~ X1:X2</code> alone without the main effects — the model would be misspecified and the coefficients uninterpretable (the “effect of X₁ for the reference group” would lose its meaning without <span class="math inline">\(\beta_1\)</span> in the model).</p>
</div>
</div>
</div>
</div>
</section>
<section id="interpreting-interaction-terms" class="slide level2 smaller scrollable">
<h2>Interpreting Interaction Terms</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Continuous × Continuous</a></li><li><a href="#tabset-3-2">Continuous × Binary</a></li><li><a href="#tabset-3-3">Binary × Binary</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>Both X₁ and X₂ are continuous (e.g., age × education → income).</p>
<p><span class="math display">\[\hat{Y} = \alpha + \beta_1 X_1 + \beta_2 X_2 + \beta_3 (X_1 \times X_2)\]</span></p>
<ul>
<li>Effect of X₁ = <span class="math inline">\(\beta_1 + \beta_3 X_2\)</span> — the slope for X₁ <strong>depends on the value of X₂</strong></li>
<li>Effect of X₂ = <span class="math inline">\(\beta_2 + \beta_3 X_1\)</span> — the slope for X₂ <strong>depends on the value of X₁</strong></li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Evaluating at meaningful values</strong></p>
</div>
<div class="callout-content">
<p>In a continuous × continuous interaction, <span class="math inline">\(\beta_1\)</span> is the effect of <span class="math inline">\(X_1\)</span> <strong>only when <span class="math inline">\(X_2 = 0\)</span></strong> — which is often outside the range of your data and substantively meaningless. Instead, compute <strong>simple slopes</strong>: the effect of <span class="math inline">\(X_1\)</span> at low, average, and high values of <span class="math inline">\(X_2\)</span> (conventionally mean − 1 SD, mean, mean + 1 SD). Use <code>ggpredict(model, terms = c("X1", "X2 [meansd]"))</code> to compute and plot these automatically.</p>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Evaluating direction:</strong></p>
</div>
<div class="callout-content">
<p>More common but less precise is to just describe the direction. For example, “As <span class="math inline">\(X_2\)</span> increases, the impact of <span class="math inline">\(X_1\)</span> increases/decreases (depending on +/- of <span class="math inline">\(X_3\)</span>)”.</p>
</div>
</div>
</div>
</div>
<div id="tabset-3-2">
<p>Most common in sociology: continuous X₁, binary X₂ (e.g., sex, race indicator, treatment/control).</p>
<p><span class="math display">\[\hat{Y} = \alpha + \beta_1 X_1 + \beta_2 X_2 + \beta_3 (X_1 \times X_2)\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Slope for X₁</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X_2 = 0\)</span> (reference)</td>
<td><span class="math inline">\(\beta_1\)</span></td>
<td>Slope for reference group</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X_2 = 1\)</span> (other group)</td>
<td><span class="math inline">\(\beta_1 + \beta_3\)</span></td>
<td>Reference slope + interaction</td>
</tr>
<tr class="odd">
<td><strong>Difference in slopes</strong></td>
<td><span class="math inline">\(\beta_3\)</span></td>
<td>The interaction term itself</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Our example: education × sex → income</strong></p>
</div>
<div class="callout-content">
<ul>
<li><span class="math inline">\(\beta_1\)</span> = income return to education <strong>for men</strong> (reference)</li>
<li><span class="math inline">\(\beta_3\)</span> = how much women’s return differs from men’s — a positive <span class="math inline">\(\beta_3\)</span> means women benefit <em>more</em> per year; negative means women benefit <em>less</em></li>
<li><strong>Test of moderation:</strong> is <span class="math inline">\(\beta_3\)</span> statistically significantly different from zero?</li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-3-3">
<p>Both X₁ and X₂ are binary (e.g., race × sex → income).</p>
<p><span class="math display">\[\hat{Y} = \alpha + \beta_1 X_1 + \beta_2 X_2 + \beta_3 (X_1 \times X_2)\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>X₁</th>
<th>X₂</th>
<th>Predicted Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td><span class="math inline">\(\alpha\)</span> (double reference)</td>
</tr>
<tr class="even">
<td>1</td>
<td>0</td>
<td><span class="math inline">\(\alpha + \beta_1\)</span></td>
</tr>
<tr class="odd">
<td>0</td>
<td>1</td>
<td><span class="math inline">\(\alpha + \beta_2\)</span></td>
</tr>
<tr class="even">
<td>1</td>
<td>1</td>
<td><span class="math inline">\(\alpha + \beta_1 + \beta_2 + \beta_3\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><span class="math inline">\(\beta_3\)</span> measures <strong>non-additivity</strong>: the effect of X₁ is different when X₂ = 1 vs.&nbsp;X₂ = 0</li>
<li>This is sometimes called a <strong>multiplicative interaction</strong> or a <strong>synergistic / suppressive effect</strong></li>
</ul>
</div>
</div>
</div>
</section>
<section id="worked-examples-interaction-terms" class="slide level2 smaller scrollable">
<h2>Worked Examples: Interaction Terms</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Continuous × Continuous</a></li><li><a href="#tabset-4-2">Continuous × Binary</a></li><li><a href="#tabset-4-3">Binary × Binary</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p><strong>Model:</strong> <code>lm(self_esteem ~ skin_tone * income_z)</code> — does income moderate the impact of skin-tone on self-esteem?</p>
<p><span class="math display">\[\hat{Y} = 4.5 + 0.30\,(\text{skin_tone}) + 0.08\,(\text{income}) - 0.04\,(\text{skin_tone} \times \text{income})\]</span></p>
<p>On effective way to visualize this effect is to calculate effect size at <strong>low, average, and high values</strong> of income (e.g., low = −1 SD, mean = 0, high = +1 SD) (assuming income is standardized):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Income level</th>
<th>Calculation</th>
<th>Skin-tone slope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low (−1 SD)</td>
<td><span class="math inline">\(0.30 + (-0.04)(-1)\)</span></td>
<td><strong>+0.34</strong></td>
</tr>
<tr class="even">
<td>Mean (0)</td>
<td><span class="math inline">\(0.30 + (-0.04)(0)\)</span></td>
<td><strong>+0.30</strong></td>
</tr>
<tr class="odd">
<td>High (+1 SD)</td>
<td><span class="math inline">\(0.30 + (-0.04)(+1)\)</span></td>
<td><strong>+0.26</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpretation at meaningful values</strong></p>
</div>
<div class="callout-content">
<p>The simple slopes show that the positive effect of skin tone on self-esteem is strongest at <strong>low income</strong> (+0.34) and attenuates as income rises (+0.26 at high income). In other words, income <strong>moderates</strong> the impact of skin-tone on self-esteem: higher income weakens the relationship. <span class="math inline">\(\beta_3 = -0.04\)</span> tells us the skin-tone slope decreases by 0.04 for each 1-SD increase in income.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpretation using direction</strong></p>
</div>
<div class="callout-content">
<ul>
<li>“As income increases, the effect of skin tone descreases.”</li>
<li>Or something a bit more precise: “At lower values of income, skin tone has a stronger positive association with self-esteem (+0.34), but as income increases the impact of skin tone on self-esteem weakens (+0.26).”</li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-4-2">
<p><strong>Model:</strong> <code>lm(income ~ educ * female)</code> — does the income return to education differ by sex?</p>
<p><span class="math display">\[\hat{Y} = 10{,}000 + 3{,}200\,(\text{educ}) - 8{,}000\,(\text{female}) - 600\,(\text{educ} \times \text{female})\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Slope for educ</th>
<th>Calculation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Men (<span class="math inline">\(\text{female}=0\)</span>)</td>
<td><strong>$3,200/year</strong></td>
<td><span class="math inline">\(\beta_1 = 3{,}200\)</span></td>
</tr>
<tr class="even">
<td>Women (<span class="math inline">\(\text{female}=1\)</span>)</td>
<td><strong>$2,600/year</strong></td>
<td><span class="math inline">\(\beta_1 + \beta_3 = 3{,}200 + (-600)\)</span></td>
</tr>
<tr class="odd">
<td>Difference</td>
<td><strong>−$600/year</strong></td>
<td><span class="math inline">\(\beta_3 = -600\)</span></td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpretation</strong></p>
</div>
<div class="callout-content">
<p>Each additional year of education is associated with <strong>$3,200 more income for men</strong> but only <strong>$2,600 more for women</strong> — a gap of $600 per year. If <span class="math inline">\(\beta_3\)</span> is statistically significant (p &lt; .05), we conclude the returns to education differ by sex. Note: <span class="math inline">\(\beta_2 = -8{,}000\)</span> is the gap at <strong>zero years of education</strong> (rarely meaningful on its own).</p>
</div>
</div>
</div>
</div>
<div id="tabset-4-3">
<p><strong>Model:</strong> <code>lm(income ~ Black * female)</code> — does the racial income gap differ by sex?</p>
<p><span class="math display">\[\hat{Y} = 65{,}000 - 12{,}000\,(\text{Black}) - 18{,}000\,(\text{female}) + 5{,}000\,(\text{Black} \times \text{female})\]</span></p>
<p><strong>Predicted incomes (2×2 table):</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>White (<span class="math inline">\(X_1=0\)</span>)</th>
<th>Black (<span class="math inline">\(X_1=1\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Men</strong> (<span class="math inline">\(X_2=0\)</span>)</td>
<td><span class="math inline">\(\$65K\)</span></td>
<td><span class="math inline">\(\$65K-\$12K = \$53K\)</span></td>
</tr>
<tr class="even">
<td><strong>Women</strong> (<span class="math inline">\(X_2=1\)</span>)</td>
<td><span class="math inline">\(\$65K -\$12K  = \$47K\)</span></td>
<td><span class="math inline">\(\$65K -\$12K -\$18K +\$5K= \$40K\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Race gap within sex:</strong></p>
<ul>
<li>Among men: $65,000 − $53,000 = <strong>−$12,000</strong> (<span class="math inline">\(\beta_1\)</span>)</li>
<li>Among women: $47,000 − $40,000 = <strong>−$7,000</strong> (<span class="math inline">\(\beta_1 + \beta_3\)</span>)</li>
</ul>
<p><strong>Gender gap within race:</strong></p>
<ul>
<li>Among white workers: $65,000 − $47,000 = <strong>−$18,000</strong> (<span class="math inline">\(\beta_2\)</span>)</li>
<li>Among Black workers: $53,000 − $40,000 = <strong>−$13,000</strong> (<span class="math inline">\(\beta_2 + \beta_3\)</span>)</li>
</ul>
<p><strong>Race + gender gap (white men vs.&nbsp;Black women):</strong></p>
<ul>
<li>$65,000 − $40,000 = <strong>−$25,000</strong> (<span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = -12{,}000 + (-18{,}000) + 5{,}000\)</span>)</li>
</ul>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpretation</strong></p>
</div>
<div class="callout-content">
<p>The racial income gap is smaller for women (−$7k) than for men (−$12k), and the gender gap is smaller among Black workers (−$13k) than among white workers (−$18k). Both patterns are driven by the same thing: <span class="math inline">\(\beta_3 = +5{,}000\)</span>. Black women face the largest combined disadvantage at −$25,000 relative to white men.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="running-example-does-education-pay-off-equally" class="slide level2 smaller">
<h2>Running Example: Does Education Pay Off Equally?</h2>
<p><strong>Research question:</strong> Does each additional year of education translate into the same income gain for men and women?</p>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why this matters sociologically:</strong></p>
</div>
<div class="callout-content">
<p>A central debate in stratification research: Do women earn less simply because they have <em>less</em> education? Or does the <strong>return to education</strong> itself differ by gender — meaning each year of education is worth more in the labor market for men than for women?</p>
<p>If <span class="math inline">\(\beta_3 &lt; 0\)</span> (education × female), this is evidence of structural inequality: even with identical credentials, women receive a lower wage premium per year of schooling.</p>
</div>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="co"># Without interaction: assumes same education slope for men and women</span></span>
<span id="cb5-2"><a></a>model_main <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> educ <span class="sc">+</span> sex_f, <span class="at">data =</span> attain_sub)</span>
<span id="cb5-3"><a></a></span>
<span id="cb5-4"><a></a><span class="co"># With interaction: allows slopes to differ by sex</span></span>
<span id="cb5-5"><a></a>model_interact <span class="ot">&lt;-</span> <span class="fu">lm</span>(income91 <span class="sc">~</span> educ <span class="sc">*</span> sex_f, <span class="at">data =</span> attain_sub)</span>
<span id="cb5-6"><a></a></span>
<span id="cb5-7"><a></a><span class="co"># Extract key coefficients</span></span>
<span id="cb5-8"><a></a><span class="fu">coef</span>(model_interact)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept)             educ      sex_ffemale educ:sex_ffemale 
     -6547.43864       3836.33531      -6037.51913         83.89174 </code></pre>
</div>
</div>
</div>
</section>
<section id="interaction-model-results" class="slide level2 smaller scrollable">
<h2>Interaction Model Results</h2>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Model Table</a></li><li><a href="#tabset-5-2">Reading the Coefficients</a></li><li><a href="#tabset-5-3">Predicted Incomes</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">modelsummary</span>(</span>
<span id="cb7-2"><a></a>  <span class="fu">list</span>(<span class="st">"No Interaction"</span>   <span class="ot">=</span> model_main,</span>
<span id="cb7-3"><a></a>       <span class="st">"With Interaction"</span> <span class="ot">=</span> model_interact),</span>
<span id="cb7-4"><a></a>  <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>      <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb7-5"><a></a>                  <span class="st">"educ"</span>             <span class="ot">=</span> <span class="st">"Years of Education"</span>,</span>
<span id="cb7-6"><a></a>                  <span class="st">"sex_ffemale"</span>      <span class="ot">=</span> <span class="st">"Female"</span>,</span>
<span id="cb7-7"><a></a>                  <span class="st">"educ:sex_ffemale"</span> <span class="ot">=</span> <span class="st">"Education × Female"</span>),</span>
<span id="cb7-8"><a></a>  <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-9"><a></a>  <span class="at">fmt     =</span> <span class="dv">0</span>,</span>
<span id="cb7-10"><a></a>  <span class="at">title   =</span> <span class="st">"OLS: Income ~ Education × Sex"</span>,</span>
<span id="cb7-11"><a></a>  <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>, <span class="st">"adj.r.squared"</span>)</span>
<span id="cb7-12"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>OLS: Income ~ Education × Sex</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;No Interaction</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;With Interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">−7092*</td>
<td style="text-align: center;">−6547</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(3557)</td>
<td style="text-align: center;">(4848)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Years of Education</td>
<td style="text-align: center;">3877***</td>
<td style="text-align: center;">3836***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(254)</td>
<td style="text-align: center;">(354)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: center;">−4919***</td>
<td style="text-align: center;">−6038</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1472)</td>
<td style="text-align: center;">(6928)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education × Female</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">84</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(508)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2517</td>
<td style="text-align: center;">2517</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.089</td>
<td style="text-align: center;">0.089</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.088</td>
<td style="text-align: center;">0.088</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<div id="tabset-5-2">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpreting the interaction model:</strong></p>
</div>
<div class="callout-content">
<p>From the regression output:</p>
<ul>
<li><strong>Education (3836):</strong> Effect of each year of education <em>for men</em> (the reference group)</li>
<li><strong>Female (-$6,038):</strong> Difference in baseline income for women vs.&nbsp;men at education = 0 — not substantively meaningful on its own</li>
<li><strong>Education × Female (84):</strong> Women receive <strong>$84 more per additional year of education</strong> compared to men — this is the interaction</li>
</ul>
<p><strong>Slopes by group:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th>Income return per year of education</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Men</td>
<td>$3,836</td>
</tr>
<tr class="even">
<td>Women</td>
<td>$3,836 + (84) = <strong>$3,920</strong></td>
</tr>
<tr class="odd">
<td>Difference</td>
<td>84 (p = 0.869)</td>
</tr>
</tbody>
</table>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note: this interaction is not statistically significant</strong></p>
</div>
<div class="callout-content">
<p>In this example, p = 0.869 — we <strong>fail to reject H₀</strong> that the education slope is the same for men and women. Even if both lower-order terms (education, female) were significant (only education is here), it’s irrelevant: <strong>significance of main effects tells you nothing about whether the interaction is real.</strong> The only test that matters for moderation is the p-value on the interaction term itself (<code>educ:sex_ffemale</code>). A non-significant result means the data are consistent with parallel slopes — not that an interaction definitely doesn’t exist (see the power note later).</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-5-3">
<p>We can also calculate predicted incomes for specific profiles:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>profiles <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb8-2"><a></a>  <span class="at">educ  =</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">16</span>),</span>
<span id="cb8-3"><a></a>  <span class="at">sex_f =</span> <span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>, <span class="st">"male"</span>, <span class="st">"female"</span>)</span>
<span id="cb8-4"><a></a>)</span>
<span id="cb8-5"><a></a></span>
<span id="cb8-6"><a></a>profiles <span class="sc">|&gt;</span></span>
<span id="cb8-7"><a></a>  <span class="fu">mutate</span>(<span class="at">predicted_income =</span> <span class="fu">predict</span>(model_interact, <span class="at">newdata =</span> profiles)) <span class="sc">|&gt;</span></span>
<span id="cb8-8"><a></a>  <span class="fu">mutate</span>(<span class="at">predicted_income =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">round</span>(predicted_income)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
   educ sex_f  predicted_income
  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;           
1    12 male   $39,489         
2    12 female $34,458         
3    16 male   $54,834         
4    16 female $50,139         </code></pre>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The income gap by education level:</strong></p>
</div>
<div class="callout-content">
<ul>
<li>At high school education (12 years): men earn $39,489 vs.&nbsp;women $34,458 — a gap of $5,031</li>
<li>At college education (16 years): men earn $54,834 vs.&nbsp;women $50,139 — a gap of $4,695</li>
</ul>
<p>If the interaction term is negative, <strong>the gender wage gap widens with education</strong> — more education amplifies inequality, not diminishes it.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="visualizing-the-interaction" class="slide level2 smaller scrollable">
<h2>Visualizing the Interaction</h2>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Parallel vs.&nbsp;Non-Parallel Slopes</a></li><li><a href="#tabset-6-2">Reading the Plot</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week13_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-2">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What to look for in an interaction plot:</strong></p>
</div>
<div class="callout-content">
<p><strong>Line slope:</strong> A steeper line = higher income return per year of education for that group.</p>
<p><strong>Line gap at each X value:</strong> The vertical distance between men’s and women’s predicted incomes. If the lines are parallel (same slope), the gap is constant. If men’s line is steeper, the gap <strong>widens</strong> with more education.</p>
<p><strong>Confidence ribbons:</strong> Overlapping ribbons suggest uncertainty about whether the two slopes are truly different. The formal test is the interaction term’s p-value — not visual ribbon comparison.</p>
<p><strong>For your data:</strong> Run the same visualization replacing <code>sex_f</code> with your moderating variable. Does the X → Y relationship look different across levels of Z?</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="testing-and-reporting-the-interaction" class="slide level2 smaller scrollable">
<h2>Testing and Reporting the Interaction</h2>
<div class="fragment fade-up">
<p><strong>Is the interaction statistically significant?</strong></p>
<p>The interaction term <span class="math inline">\(\hat\beta_3\)</span> has its own standard error, t-statistic, and p-value in the regression output. This tests:</p>
<p><span class="math display">\[H_0: \beta_3 = 0 \quad \text{(no interaction — slopes are the same for both groups)}\]</span> <span class="math display">\[H_A: \beta_3 \neq 0 \quad \text{(slopes differ between groups)}\]</span></p>
<p>In our example: p = 0.869 for the education × female interaction term.</p>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reporting checklist for an interaction result:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>State the substantive question:</strong> Does the effect of X on Y vary by Z?</li>
<li><strong>Report the interaction coefficient:</strong> <span class="math inline">\(\hat\beta_3\)</span> = 84 (<span class="math inline">\(p = 0.869\)</span>)</li>
<li><strong>State the group-specific slopes:</strong> men = $3,836/year; women = $3,920/year</li>
<li><strong>Show the visualization:</strong> margins plot with two lines, CIs</li>
<li><strong>Interpret substantively:</strong> <em>what does it mean</em> that the slopes differ? Connect to theory.</li>
</ol>
</div>
</div>
</div>
</div>
<div class="fragment fade-up">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A note on statistical power</strong></p>
</div>
<div class="callout-content">
<p>Interaction terms are often <strong>hard to detect</strong> — you need a large sample and a reasonably strong moderating effect. A non-significant interaction term does not necessarily mean “no interaction exists in the population.” It may mean the study is underpowered. Be cautious about drawing strong null conclusions from a single insignificant <span class="math inline">\(\hat\beta_3\)</span>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="interactions-in-logistic-regression" class="slide level2 smaller scrollable">
<h2>Interactions in Logistic Regression</h2>
<p>Interaction terms work the same way in logistic regression — same syntax, same logic:</p>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Model Table</a></li><li><a href="#tabset-7-2">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>attain_logit <span class="ot">&lt;-</span> attain <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(union_member), <span class="sc">!</span><span class="fu">is.na</span>(educ), <span class="sc">!</span><span class="fu">is.na</span>(sex_f))</span>
<span id="cb10-3"><a></a></span>
<span id="cb10-4"><a></a><span class="co"># Logistic regression with interaction</span></span>
<span id="cb10-5"><a></a>model_logit_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(union_member <span class="sc">~</span> educ <span class="sc">*</span> sex_f,</span>
<span id="cb10-6"><a></a>                       <span class="at">family =</span> binomial,</span>
<span id="cb10-7"><a></a>                       <span class="at">data   =</span> attain_logit)</span>
<span id="cb10-8"><a></a></span>
<span id="cb10-9"><a></a><span class="fu">modelsummary</span>(model_logit_int,</span>
<span id="cb10-10"><a></a>             <span class="at">exponentiate =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-11"><a></a>             <span class="at">coef_rename  =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>      <span class="ot">=</span> <span class="st">"Intercept"</span>,</span>
<span id="cb10-12"><a></a>                              <span class="st">"educ"</span>             <span class="ot">=</span> <span class="st">"Years of Education"</span>,</span>
<span id="cb10-13"><a></a>                              <span class="st">"sex_ffemale"</span>      <span class="ot">=</span> <span class="st">"Female"</span>,</span>
<span id="cb10-14"><a></a>                              <span class="st">"educ:sex_ffemale"</span> <span class="ot">=</span> <span class="st">"Education × Female"</span>),</span>
<span id="cb10-15"><a></a>             <span class="at">stars   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-16"><a></a>             <span class="at">title   =</span> <span class="st">"Logistic Regression with Interaction (Odds Ratios)"</span>,</span>
<span id="cb10-17"><a></a>             <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"AIC"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Logistic Regression with Interaction (Odds Ratios)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">0.337**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.120)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Years of Education</td>
<td style="text-align: center;">0.931**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.025)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: center;">0.018***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.012)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education × Female</td>
<td style="text-align: center;">1.278***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.058)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2985</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Interpreting the logistic interaction OR:</strong></p>
</div>
<div class="callout-content">
<p>The interaction OR (Education × Female) tells you how the <strong>per-year education effect on the odds of union membership</strong> differs between women and men. An OR &lt; 1 for the interaction means women’s odds multiply by <em>less</em> per year of education than men’s. As with OLS, use <code>ggpredict()</code> to translate this into predicted probabilities — the visualization (next tab) makes the pattern much clearer.</p>
</div>
</div>
</div>
</div>
<div id="tabset-7-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">ggpredict</span>(model_logit_int, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"educ [6:20 by=0.5]"</span>, <span class="st">"sex_f"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a></a>  (\(pred) {</span>
<span id="cb11-3"><a></a>    <span class="fu">ggplot</span>(pred, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> predicted, <span class="at">color =</span> group, <span class="at">fill =</span> group)) <span class="sc">+</span></span>
<span id="cb11-4"><a></a>      <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), <span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a></a>      <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.4</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a></a>      <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"male"</span> <span class="ot">=</span> <span class="st">"#4E79A7"</span>, <span class="st">"female"</span> <span class="ot">=</span> <span class="st">"#E15759"</span>),</span>
<span id="cb11-7"><a></a>                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Men"</span>, <span class="st">"Women"</span>), <span class="at">name =</span> <span class="st">"Sex"</span>) <span class="sc">+</span></span>
<span id="cb11-8"><a></a>      <span class="fu">scale_fill_manual</span>(<span class="at">values  =</span> <span class="fu">c</span>(<span class="st">"male"</span> <span class="ot">=</span> <span class="st">"#4E79A7"</span>, <span class="st">"female"</span> <span class="ot">=</span> <span class="st">"#E15759"</span>),</span>
<span id="cb11-9"><a></a>                        <span class="at">labels  =</span> <span class="fu">c</span>(<span class="st">"Men"</span>, <span class="st">"Women"</span>), <span class="at">name =</span> <span class="st">"Sex"</span>) <span class="sc">+</span></span>
<span id="cb11-10"><a></a>      <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>),</span>
<span id="cb11-11"><a></a>                         <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb11-12"><a></a>      <span class="fu">labs</span>(</span>
<span id="cb11-13"><a></a>        <span class="at">title    =</span> <span class="st">"Predicted P(Union Member) by Education and Sex"</span>,</span>
<span id="cb11-14"><a></a>        <span class="at">subtitle =</span> <span class="st">"Logistic regression with education × sex interaction"</span>,</span>
<span id="cb11-15"><a></a>        <span class="at">x =</span> <span class="st">"Years of Education"</span>,</span>
<span id="cb11-16"><a></a>        <span class="at">y =</span> <span class="st">"Predicted Probability"</span></span>
<span id="cb11-17"><a></a>      ) <span class="sc">+</span></span>
<span id="cb11-18"><a></a>      <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>)</span>
<span id="cb11-19"><a></a>  })()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="week13_files/figure-revealjs/unnamed-chunk-13-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why are the curves S-shaped — and what do they mean?</strong></p>
</div>
<div class="callout-content">
<p><strong>The S-curve is not from a quadratic term.</strong> It comes from logistic regression itself: the model predicts <em>log-odds</em> as a linear function of education, but <code>ggpredict()</code> converts those to <em>probabilities</em> (which must stay between 0 and 1). That conversion — the logistic function — always produces an S-shaped (sigmoid) curve. No squared term needed.</p>
<p><strong>Reading the interaction:</strong></p>
<ul>
<li>At low education levels, men and women have similar (low) predicted probabilities of union membership</li>
<li>As education increases, men’s probability rises more steeply — the lines <strong>diverge</strong></li>
<li>This means the effect of education on union membership is <strong>stronger for men</strong> than for women</li>
<li>The interaction term in the model tests whether this divergence is statistically distinguishable from zero</li>
</ul>
<p><strong>Compared to OLS:</strong> In a linear regression, diverging lines imply a constant <em>dollar</em> gap that grows linearly. In logistic regression, the divergence in probability space is non-linear — even if the underlying log-odds interaction is a fixed constant, the <em>probability</em> gap widens most rapidly in the middle of the distribution and compresses near 0 and 1. Always show the probability plot so readers can see the actual gap at relevant education levels.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="questions-2" class="slide level2">
<h2>Questions?</h2>
</section></section>
<section>
<section id="reading-thompson-keith-2001" class="title-slide slide level1 center">
<h1>Reading: Thompson &amp; Keith (2001)</h1>
<p>Interactions in a classic race &amp; gender study</p>
</section>
<section id="the-blacker-the-berry-overview" class="slide level2 smaller">
<h2>“The Blacker the Berry” — Overview</h2>
<p><strong>Thompson, M.S. &amp; Keith, V.M. (2001).</strong> <em>The Blacker the Berry: Gender, Skin Tone, Self-Esteem, and Self-Efficacy.</em> <strong>Gender &amp; Society, 15</strong>(3), 336–357.</p>
<div class="fragment fade-up">
<p><strong>Research question:</strong> How does skin tone affect self-esteem and self-efficacy among Black Americans — and does this effect <em>depend on gender</em>?</p>
<ul>
<li>Studies <strong>colorism</strong>: the privileging of lighter skin tones within racial groups — a legacy of slavery, segregation, and Eurocentric beauty standards</li>
<li>Uses OLS regression with <strong>continuous × continuous interaction terms</strong> — skin tone × income, attractiveness, and weight</li>
<li>Key finding: the effect of skin tone on well-being is <strong>conditional</strong> on social resources — and the relevant resources differ for Black women vs.&nbsp;Black men</li>
</ul>
</div>
<div class="fragment fade-up">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why this paper for interactions week?</strong></p>
</div>
<div class="callout-content">
<p>Thompson &amp; Keith use <strong>continuous × continuous interactions</strong> to show that skin tone’s effect on self-esteem is not fixed — it depends on what social resources you have (income, attractiveness for women; weight for men). This is exactly the moderation logic we covered in Part 2: the X → Y relationship changes depending on Z. The paper also models how to justify an interaction theoretically before testing it empirically.</p>
</div>
</div>
</div>
</div>
</section>
<section id="research-design" class="slide level2 smaller scrollable">
<h2>Research Design</h2>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Data &amp; Sample</a></li><li><a href="#tabset-8-2">Variables</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<ul>
<li><strong>Data:</strong> National Survey of Black Americans (NSBA), a nationally representative survey of Black adults</li>
<li><strong>Sample:</strong> Black Americans aged 18+ — Wave I (1979–80) and Wave IV (1992)</li>
<li><strong>Context:</strong> 1970s–80s US — ongoing de facto racial stratification and deeply gendered standards of beauty</li>
</ul>
</div>
<div id="tabset-8-2">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Variable</th>
<th>Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Outcome 1</strong></td>
<td>Self-esteem</td>
<td>Multi-item scale (Rosenberg items)</td>
</tr>
<tr class="even">
<td><strong>Outcome 2</strong></td>
<td>Self-efficacy</td>
<td>Multi-item scale (locus of control items)</td>
</tr>
<tr class="odd">
<td><strong>Key predictor (X₁)</strong></td>
<td>Skin tone</td>
<td>Interviewer-rated, 5-point scale (1 = very light, 5 = very dark)</td>
</tr>
<tr class="even">
<td><strong>Moderator (X₂)</strong></td>
<td>Gender</td>
<td>Binary: female / male</td>
</tr>
<tr class="odd">
<td><strong>Interaction</strong></td>
<td>Skin tone × Gender</td>
<td>Tests whether the skin tone effect differs by gender</td>
</tr>
<tr class="even">
<td><strong>Controls</strong></td>
<td>Education, income, age, marital status, region</td>
<td>Individual characteristics</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Connecting to today’s framework:</strong></p>
</div>
<div class="callout-content">
<p>Their regression is equivalent to:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">lm</span>(self_esteem <span class="sc">~</span> skin_tone <span class="sc">*</span> gender <span class="sc">+</span> education <span class="sc">+</span> income <span class="sc">+</span> age <span class="sc">+</span> ...,</span>
<span id="cb12-2"><a></a>   <span class="at">data =</span> nsba)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The interaction term tests: is the effect of <code>skin_tone</code> on <code>self_esteem</code> different for women vs.&nbsp;men?</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="key-results-the-skin-tone-gender-interaction" class="slide level2 smaller scrollable">
<h2>Key Results: The Skin Tone × Gender Interaction</h2>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">What They Found</a></li><li><a href="#tabset-9-2">Simplified Results Table</a></li><li><a href="#tabset-9-3">The Path Model</a></li><li><a href="#tabset-9-4">Discussion &amp; Interpretation (pp.&nbsp;351–354)</a></li><li><a href="#tabset-9-5">Lessons for Your Research</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The core finding (Results pp.&nbsp;349–351):</strong></p>
</div>
<div class="callout-content">
<p>Thompson &amp; Keith run <strong>separate OLS models for women and men</strong>. Rather than one skin-tone × gender term, they find <strong>continuous × continuous interactions</strong> within each gender’s model — the effect of skin tone depends on other social resources:</p>
<p><strong>Women’s self-esteem</strong> (Table 4):</p>
<ul>
<li>Skin tone × <strong>Income</strong>: b¹ = −.035* — darker skin lowers self-esteem most for low-income women; the effect disappears at high income</li>
<li>Skin tone × <strong>Attractiveness</strong>: b¹ = −.113* — darker skin lowers self-esteem most for women rated low in attractiveness</li>
</ul>
<p><strong>Men’s self-esteem and self-efficacy</strong> (Table 4):</p>
<ul>
<li>Skin tone × <strong>Weight</strong> → self-esteem: b¹ = +.274* — darker skin <em>hurts</em> self-esteem for low-weight men but <em>helps</em> for high-weight men</li>
<li>Skin tone × <strong>Weight</strong> → self-efficacy: b¹ = +.188† — same moderator, same direction: weight conditions how skin tone relates to self-efficacy</li>
</ul>
<p><strong>The bigger picture:</strong> skin tone’s relationship with well-being is highly conditional — it depends on what social resources you have. And those resources differ by gender, which is why the pattern looks so different for women vs.&nbsp;men.</p>
</div>
</div>
</div>
</div>
<div id="tabset-9-2">
<p>Thompson &amp; Keith (2001), <strong>Table 4</strong> — significant interaction effects with simple slopes at low, average, and high values of the moderator. Models run <strong>separately by gender</strong>.</p>
<table style="font-size:0.80em; width:100%; border-collapse:collapse;">
<thead>
<tr>
<th style="border-bottom:2px solid #888; text-align:left; padding:4px 7px; width:14%;">
Model
</th>
<th style="border-bottom:2px solid #888; text-align:left; padding:4px 7px; width:28%;">
Interaction
</th>
<th style="background-color:#4E79A7; color:white; text-align:center; padding:4px 7px; width:10%;">
b¹ (int.)
</th>
<th style="border-bottom:2px solid #888; text-align:left; padding:4px 7px; width:22%;">
Moderator level
</th>
<th style="background-color:#4E79A7; color:white; text-align:center; padding:4px 7px; width:10%;">
b² (skin tone slope)
</th>
</tr>
</thead>
<tbody>
<tr style="background-color:#f8f0fb;">
<td rowspan="6" style="padding:4px 7px; font-weight:bold; vertical-align:top;">
Women<br><em>Self-Esteem</em>
</td>
<td rowspan="3" style="padding:4px 7px; vertical-align:top;">
Skin Tone × Income
</td>
<td rowspan="3" style="background-color:#e8d5f5; text-align:center; font-weight:bold; vertical-align:middle;">
−.035*
</td>
<td style="padding:4px 7px;">
Low income
</td>
<td style="text-align:center; font-weight:bold;">
+.376*
</td>
</tr>
<tr style="background-color:#f8f0fb;">
<td style="padding:4px 7px;">
Average income
</td>
<td style="text-align:center;">
+.185*
</td>
</tr>
<tr style="background-color:#f8f0fb;">
<td style="padding:4px 7px;">
High income
</td>
<td style="text-align:center; color:#888;">
−.005
</td>
</tr>
<tr style="background-color:#f8f0fb;">
<td rowspan="3" style="padding:4px 7px; vertical-align:top;">
Skin Tone × Attractiveness
</td>
<td rowspan="3" style="background-color:#e8d5f5; text-align:center; font-weight:bold; vertical-align:middle;">
−.113*
</td>
<td style="padding:4px 7px;">
Low attractiveness
</td>
<td style="text-align:center; font-weight:bold;">
+.350**
</td>
</tr>
<tr style="background-color:#f8f0fb;">
<td style="padding:4px 7px;">
Average attractiveness
</td>
<td style="text-align:center;">
+.184*
</td>
</tr>
<tr style="background-color:#f8f0fb;">
<td style="padding:4px 7px;">
High attractiveness
</td>
<td style="text-align:center; color:#888;">
+.018
</td>
</tr>
<tr style="border-top:2px solid #ccc; background-color:#e8f5e9;">
<td rowspan="3" style="padding:4px 7px; font-weight:bold; vertical-align:top;">
Men<br><em>Self-Esteem</em>
</td>
<td rowspan="3" style="padding:4px 7px; vertical-align:top;">
Skin Tone × Weight
</td>
<td rowspan="3" style="background-color:#c8e6c9; text-align:center; font-weight:bold; vertical-align:middle;">
+.274*
</td>
<td style="padding:4px 7px;">
Low weight
</td>
<td style="text-align:center; font-weight:bold;">
−1.009*
</td>
</tr>
<tr style="background-color:#e8f5e9;">
<td style="padding:4px 7px;">
Average weight
</td>
<td style="text-align:center; color:#888;">
+.092
</td>
</tr>
<tr style="background-color:#e8f5e9;">
<td style="padding:4px 7px;">
High weight
</td>
<td style="text-align:center; font-weight:bold;">
+1.192**
</td>
</tr>
<tr style="border-top:2px solid #ccc; background-color:#fff3e0;">
<td rowspan="3" style="padding:4px 7px; font-weight:bold; vertical-align:top;">
Men<br><em>Self-Efficacy</em>
</td>
<td rowspan="3" style="padding:4px 7px; vertical-align:top;">
Skin Tone × Weight
</td>
<td rowspan="3" style="background-color:#ffe0b2; text-align:center; font-weight:bold; vertical-align:middle;">
+.188†
</td>
<td style="padding:4px 7px;">
Low weight
</td>
<td style="text-align:center; color:#888;">
−.545
</td>
</tr>
<tr style="background-color:#fff3e0;">
<td style="padding:4px 7px;">
Average weight
</td>
<td style="text-align:center;">
+.210†
</td>
</tr>
<tr style="background-color:#fff3e0;">
<td style="padding:4px 7px;">
High weight
</td>
<td style="text-align:center; font-weight:bold;">
+.965*
</td>
</tr>
</tbody>
</table>
<p><small>*p ≤ .05; **p ≤ .01; †p ≤ .10. b¹ = interaction term coefficient. b² = simple slope of skin tone at each moderator level. From Thompson &amp; Keith (2001), Table 4.</small></p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>How to read this table:</strong></p>
</div>
<div class="callout-content">
<p><strong>b¹</strong> is the interaction coefficient — it tests whether the skin tone slope <em>changes</em> as the moderator increases (negative b¹ = the effect weakens as the moderator rises). <strong>b²</strong> gives the simple slope at specific moderator values: the effect of skin tone on self-esteem <em>for women at low income</em>, etc. The skin tone slope is significant at low and average income/attractiveness, but vanishes at high levels — darker skin penalizes women’s self-esteem only when they lack other social resources.</p>
</div>
</div>
</div>
</div>
<div id="tabset-9-3">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week13_files/figure-revealjs/unnamed-chunk-14-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-9-4">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why does gender moderate the skin tone effect?</strong></p>
</div>
<div class="callout-content">
<p>Thompson &amp; Keith argue that American society applies <strong>gendered standards of beauty</strong> that tie women’s (but not men’s) social worth to physical appearance. Darker-skinned Black women are evaluated against a Eurocentric beauty ideal they are structurally excluded from. For Black men, self-concept is more tied to occupational achievement and social status — which are less directly linked to skin tone.</p>
<p>This is a <strong>structural interpretation</strong> of a statistical interaction. The interaction term is not just a number; it reflects deep patterns of racial and gender inequality in how society evaluates worth and confers status.</p>
</div>
</div>
</div>
</div>
<div id="tabset-9-5">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What Thompson &amp; Keith model for writing up interactions:</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Justify the interaction theoretically first</strong> — they explain <em>why</em> they expect gender to moderate the skin tone effect before showing the numbers</li>
<li><strong>Report group-specific slopes</strong> — not just “the interaction is significant” but “for women, the slope is X; for men, it is Y”</li>
<li><strong>Interpret substantively in the Discussion</strong> — what does the interaction <em>mean</em> about social structure?</li>
<li><strong>Use the interaction to test structural arguments</strong> — the point is not just statistics, it’s theory</li>
</ol>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="connecting-the-reading-to-today" class="slide level2 smaller">
<h2>Connecting the Reading to Today</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Thompson &amp; Keith concept</th>
<th>Our framework</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Run separate models for women and men</td>
<td>Stratified analysis — or a single model with gender interactions</td>
</tr>
<tr class="even">
<td>Skin tone × Income interaction (b¹ = −.035*)</td>
<td>Continuous × continuous: <span class="math inline">\(\beta_3\)</span> in <code>lm(Y ~ X1 * X2)</code></td>
</tr>
<tr class="odd">
<td>Simple slope at low income (+.376*)</td>
<td><span class="math inline">\(\hat\beta_1 + \hat\beta_3 \cdot X_2\)</span> evaluated at a specific value of <span class="math inline">\(X_2\)</span></td>
</tr>
<tr class="even">
<td>Simple slope vanishes at high income (−.005)</td>
<td>Effect of skin tone on self-esteem is <strong>conditional</strong> on income</td>
</tr>
<tr class="odd">
<td>Different moderators for women vs.&nbsp;men</td>
<td>Theory first: income/attractiveness matter for women’s status; weight for men’s</td>
</tr>
<tr class="even">
<td>Connects to colorism + gender theory</td>
<td>Substantive interpretation of <span class="math inline">\(\beta_3\)</span> — not just a number</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>For your research paper:</strong></p>
</div>
<div class="callout-content">
<p>T&amp;K’s approach models what good interaction research looks like: they specify a <strong>theoretically justified moderator</strong> (not just “does sex moderate everything?”), run the interaction, report simple slopes at meaningful moderator values, and interpret the result in terms of social structure. The same logic applies to your interaction hypothesis.</p>
</div>
</div>
</div>
</section>
<section id="questions-3" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="key-takeaways" class="slide level2 smaller">
<h2>Key Takeaways</h2>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Part 1 — Controls</a></li><li><a href="#tabset-10-2">Part 2 — Interactions</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<ul>
<li><strong>Confounders</strong> are variables that affect both X and Y, creating a spurious association between them</li>
<li>Controlling for Z (<code>Y ~ X + Z</code>) asks: <em>“Among people with the same Z, what is the relationship between X and Y?”</em></li>
<li>The education coefficient can change when we add controls — that change tells us how much the confounder was biasing the original estimate</li>
<li><strong>Only control for true confounders:</strong> variables prior to X and Y that have causal paths to both</li>
<li>Do NOT control for mediators (variables caused by X that cause Y) — we’ll cover mediation next week</li>
</ul>
</div>
<div id="tabset-10-2">
<ul>
<li><p>An <strong>interaction</strong> occurs when Z moderates the effect of X on Y: the X → Y relationship differs across levels of Z</p></li>
<li><p>Add an interaction with <code>lm(Y ~ X * Z)</code> — R automatically includes X, Z, and X:Z</p></li>
<li><p><strong>Continuous × binary interaction:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Effect of X for reference group</td>
<td><span class="math inline">\(\hat\beta_1\)</span></td>
</tr>
<tr class="even">
<td>Effect of X for other group</td>
<td><span class="math inline">\(\hat\beta_1 + \hat\beta_3\)</span></td>
</tr>
<tr class="odd">
<td>Test of moderation</td>
<td>Is <span class="math inline">\(\hat\beta_3\)</span> significantly ≠ 0?</td>
</tr>
</tbody>
</table></li>
<li><p>Always <strong>visualize</strong> with <code>ggpredict(model, terms = c("X", "Z"))</code> — parallel vs.&nbsp;crossing slopes</p></li>
<li><p>Same logic applies to <strong>logistic regression</strong> with <code>glm(..., family = binomial)</code></p></li>
<li><p>Interpret interactions <strong>substantively</strong> — connect to theory, not just p-values</p></li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Without interaction</th>
<th>With interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Y ~ X + Z</code> → parallel slopes</td>
<td><code>Y ~ X * Z</code> → different slopes</td>
</tr>
<tr class="even">
<td>Effect of X same for all Z</td>
<td>Effect of X varies by Z</td>
</tr>
<tr class="odd">
<td>Use when no moderation expected</td>
<td>Use when theory predicts heterogeneity</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="why-this-matters-for-your-research-paper" class="slide level2 smaller">
<h2>Why This Matters for Your Research Paper</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Should you include an interaction in your final paper?</strong></p>
</div>
<div class="callout-content">
<p><strong>Add a control variable if:</strong> There is a theoretically justified confounding variable you want to rule out as an alternative explanation for your X → Y relationship.</p>
<p><strong>Add an interaction if:</strong> You have a specific theoretical argument that the X → Y relationship <em>varies</em> across groups or contexts. The interaction is the test of that argument.</p>
<p><strong>Don’t add either just because you can.</strong> Every model extension should be motivated by theory and research question, not by fishing for significant coefficients.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Thompson &amp; Keith as a model:</strong></p>
</div>
<div class="callout-content">
<p>Their paper shows how to: (1) justify the interaction based on theory, (2) run the regression with the interaction term, (3) report and interpret group-specific slopes, and (4) connect the result back to the theoretical argument. The same four steps apply to your paper.</p>
</div>
</div>
</div>
</section>
<section id="questions-4" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="assignments" class="slide level2 smaller scrollable">
<h2>Assignments</h2>
<p><strong>Weekly Assignment #11</strong> — <span class="highlight">Due Thursday, April 23</span> <em>(optional — counts as extra credit)</em></p>
<p>Using your research dataset, run an <strong>interaction analysis</strong>:</p>
<ol type="1">
<li>Identify a theoretical reason why Z might moderate your X → Y relationship — state your interaction hypothesis clearly</li>
<li>Check for visual evidence: plot <code>ggplot(data, aes(x=X, y=Y, color=Z)) + geom_smooth(method="lm")</code></li>
<li>Run two models: <code>lm(Y ~ X + Z)</code> (no interaction) and <code>lm(Y ~ X * Z)</code> (with interaction) and compare with <code>modelsummary()</code></li>
<li>Interpret the interaction coefficient: which group has a larger slope? By how much?</li>
<li>Report whether the interaction is statistically significant, and interpret what this means substantively</li>
<li>Produce a <code>ggpredict(model, terms = c("X", "Z"))</code> visualization and describe the pattern</li>
</ol>
<p><strong>Also upcoming:</strong></p>
<ul>
<li><strong>Revised Proposal with Outline</strong> — <span class="highlight">Due Thursday, April 16</span>
<ul>
<li>Describe whether your final analysis includes any control variables or interaction hypotheses</li>
</ul></li>
<li><strong>In-class presentations</strong> — <span class="highlight">April 28</span></li>
<li><strong>Final paper</strong> — <span class="highlight">Due Thursday, May 7</span></li>
</ul>
</section>
<section id="in-class-lab-today" class="slide level2 smaller">
<h2>In-class lab today</h2>
<ul>
<li>Practice interaction analysis using <code>attain</code> dataset</li>
<li>see lab #8 on bCourses</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://www.kaseyzapatka.com/soc106">GitHub course repo</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>