<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-03-03">
  <title>Sociology 106 – Week 7</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="slides.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 7</h1>
  <p class="subtitle">Sociology 106: Quantitative Sociological Methods</p>

<div class="quarto-title-authors">
</div>

  <p class="date">March 3, 2026</p>
</section>
<section id="housekeeping" class="slide level2 smaller">
<h2>Housekeeping</h2>
<p>[[<strong>ADD IT IN LATER</strong>]]</p>
</section>
<section id="where-we-are-in-the-course" class="slide level2 smaller">
<h2>Where We Are in the Course</h2>
<ul>
<li><strong>Weeks 5–6:</strong> rules of probability + probability models (Bernoulli, Binomial, Normal)</li>
<li><strong>This week (Week 7):</strong> sampling distributions and the Central Limit Theorem</li>
<li><strong>Next week (Week 8):</strong> confidence intervals</li>
<li><strong>Then (Week 9):</strong> hypothesis testing</li>
</ul>
<p><strong>Main idea:</strong> We’ve been building probability models of <em>populations</em>. Today we ask: what happens when we draw a <em>sample</em>—and then another, and another? The answer is what makes all of statistical inference possible.</p>
</section>
<section id="agenda" class="slide level2 smaller">
<h2>Agenda</h2>
<p><strong>Admin discussion:</strong></p>
<ul>
<li>Research paper proposals and annotated bibliography</li>
</ul>
<p><strong>Statistical content — three parts:</strong></p>
<ul>
<li><strong>Part 1</strong>: Sampling — from populations to data</li>
<li><strong>Part 2</strong>: Sampling distributions — statistics vary from sample to sample</li>
<li><strong>Part 3</strong>: The Central Limit Theorem — the key that unlocks inference</li>
</ul>
</section>
<section id="research-paper-proposals" class="slide level2 smaller">
<h2>Research Paper Proposals</h2>
<p><strong>Overall, great job—super interesting topics!</strong></p>
<p>I tried to give feedback in two areas:</p>
<ol type="1">
<li><p><strong>Research design</strong>: How to construct variables of interest, what units of analysis may be most appropriate, other issues you may want to think about going forward</p></li>
<li><p><strong>What has been written in the academic literature</strong> on your topic — some topics have been studied a lot, which is a <strong>good sign</strong> that your question is important!</p></li>
</ol>
<p><strong>If your question seems already answered</strong>: try a different data source, or look for related unanswered questions in paper conclusions. Happy to discuss in office hours!</p>
</section>
<section id="annotated-bibliography" class="slide level2 smaller">
<h2>Annotated Bibliography</h2>
<p><span class="highlight">Due March 19</span></p>
<p>Identify <strong>ten scholarly sources</strong> related to your research question</p>
<p>For each source: in <strong>two short paragraphs</strong>:</p>
<ol type="1">
<li>summarize what the source is arguing</li>
<li>explain how it relates to your research question</li>
</ol>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Good sources:</a></li><li><a href="#tabset-1-2">Bad sources:</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<ul>
<li>Articles in academic journals</li>
<li>Academic books</li>
<li>Book chapters from edited volumes</li>
<li>Non-political reports from research centers / government agencies</li>
</ul>
</div>
<div id="tabset-1-2">
<ul>
<li>Blogs, internet / newspaper articles</li>
<li>Wikipedia pages</li>
<li>Political reports from research centers / govt</li>
</ul>
</div>
</div>
</div>
</section>
<section id="how-to-find-academic-articles" class="slide level2 smaller">
<h2>How to Find Academic Articles</h2>
<p><strong>Search on Google Scholar or JSTOR</strong></p>
<p>You’ll usually get somewhere by taking your independent and dependent variables and searching for:</p>
<blockquote>
<p>“effect of <em>independent variable</em> on <em>dependent variable</em>”</p>
</blockquote>
<p>You may need to use a <a href="https://search.library.berkeley.edu/discovery/search?vid=01UCS_BER:UCB">UC Berkeley Library proxy</a> to access some academic articles</p>
<p>This is a <a href="https://guides.lib.berkeley.edu/ezproxy/home">helpful webpage</a> for using the proxy server and here is a <a href="https://ucberkeley.libanswers.com/faq/302000">link to make a virtual appointment</a> for research help</p>
<p><span class="highlight">NOTE: AI will hallucinate citations, so don’t use</span></p>
</section>
<section id="how-to-read-academic-articles" class="slide level2 smaller">
<h2>How to Read Academic Articles</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>What to look for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Abstract</strong></td>
<td>Overview: research question, data, main result — read first</td>
</tr>
<tr class="even">
<td><strong>Introduction</strong></td>
<td>Slightly more detailed than abstract; same format</td>
</tr>
<tr class="odd">
<td><strong>Conclusion</strong></td>
<td>Results, alternative explanations, limitations — and <strong>future research topics</strong></td>
</tr>
<tr class="even">
<td><strong>Background / Lit review</strong></td>
<td>Previous research; a <strong>good source of additional citations</strong></td>
</tr>
<tr class="odd">
<td><strong>Data section</strong></td>
<td>How the sample was constructed; what data sources researchers use</td>
</tr>
<tr class="even">
<td><strong>Methods</strong></td>
<td>Don’t worry about this too much yet!</td>
</tr>
</tbody>
</table>

<aside><div>
<p><strong>Tip</strong>: Start with abstract → conclusion → introduction. Only go deeper if the paper is clearly relevant.</p>
</div></aside></section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
</section>
<section>
<section id="part-1-from-populations-to-samples" class="title-slide slide level1 center">
<h1>Part 1: From Populations to Samples</h1>
<p>How do we go from an abstract population to real data we can analyze?</p>
</section>
<section id="sampling-basic-concepts" class="slide level2 smaller">
<h2>Sampling: Basic Concepts</h2>
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Population</strong></th>
<th><strong>Sample</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Concept</strong></td>
<td>The whole universe a study aspires to generalize to</td>
<td>The subset of the population we actually observe</td>
</tr>
<tr class="even">
<td><strong>Quantity</strong></td>
<td><strong>Parameter</strong> — a number describing the population (usually unknown)</td>
<td><strong>Statistic</strong> — a number computed from the data</td>
</tr>
<tr class="odd">
<td><strong>Example</strong></td>
<td>True proportion of Philadelphia residents who are African American: <span class="math inline">\(\pi = 0.422\)</span></td>
<td>Proportion of stopped drivers who were African American: <span class="math inline">\(\hat{p} = 0.79\)</span></td>
</tr>
</tbody>
</table>
<p><br> <span class="highlight"><strong>The goal of statistical inference</strong></span>: use a sample <em>statistic</em> to learn about a population <em>parameter</em> — we’ve been building toward this all semester</p>
</section>
<section id="sampling-from-a-population" class="slide level2 smaller">
<h2>Sampling from a Population</h2>
<p>We start with a <strong>population</strong> — every individual we want to study. In our running example, this is all 1.45 million residents of Philadelphia in 1997.</p>

<img data-src="images/week7/pop_vs_sample0.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"></section>
<section id="sampling-from-a-population-1" class="slide level2 smaller">
<h2>Sampling from a Population</h2>
<p>A <strong>sample</strong> is drawn from the population — the individuals we actually observe. The 262 drivers stopped by police are our sample, far smaller than the full population.</p>

<img data-src="images/week7/pop_vs_sample1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"></section>
<section id="sampling-from-a-population-2" class="slide level2 smaller">
<h2>Sampling from a Population</h2>
<p><strong>Key question</strong>: is our sample <em>representative</em>? Does it reflect the composition of the population? This depends entirely on the sampling design — random samples are representative; convenience samples often are not.</p>

<img data-src="images/week7/pop_vs_sample2.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"></section>
<section id="sample-design" class="slide level2 smaller">
<h2>Sample Design</h2>
<p>To do inferential statistics, we need a <strong>representative sample</strong> — ideally, each unit of the population has an equal chance of being included</p>
<p>We also want samples that are <strong>large enough for precision</strong>, which increases with sample size</p>
<p><br></p>
<p><span class="highlight"><strong>Important note</strong>:</span> Precision is inversely proportional to the diversity of values — larger samples are needed to draw inferences about small subgroups (by race, education, sexual orientation, etc.)</p>
</section>
<section id="types-of-sampling-designs" class="slide level2 smaller">
<h2>Types of Sampling Designs</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Simple random</a></li><li><a href="#tabset-2-2">Stratified random</a></li><li><a href="#tabset-2-3">Cluster</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p><strong>Simple random sample:</strong> Use a random number generator to select from a population list</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week7/sampling_simple.png" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</figure>
</div>
</div>
<div id="tabset-2-2">
<p><strong>Stratified random sample</strong>: Divide population into homogenous groups (strata), then randomly sample within each stratum</p>
<ul>
<li>Generally improves precision</li>
<li>Can over-sample smaller strata (e.g., minority groups) to make inferences <em>within</em> those groups</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week7/sampling_stratified.png" class="quarto-figure quarto-figure-center" style="width:65.0%"></p>
</figure>
</div>
</div>
<div id="tabset-2-3">
<p><strong>Cluster sampling</strong>:</p>
<ol type="1">
<li>Create subpopulations (clusters)</li>
<li>Randomly select a sample of clusters</li>
<li>Randomly select units within sampled clusters</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week7/sampling_cluster.png" class="quarto-figure quarto-figure-center" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="stratified-vs.-cluster-sampling" class="slide level2 smaller">
<h2>Stratified vs.&nbsp;Cluster Sampling</h2>
<p>These sound similar — the <strong>key difference</strong>: cluster sampling selects only <em>some</em> groups; stratified sampling samples from <em>all</em> strata.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week7/sampling_stratified.png" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week7/sampling_cluster.png" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
</section>
<section id="representative-samples-sample-weights" class="slide level2 smaller">
<h2>Representative Samples &amp; Sample Weights</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">The Problem</a></li><li><a href="#tabset-3-2">Sample Weights</a></li><li><a href="#tabset-3-3">GSS Example</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>True random samples are almost never feasible — we rarely have a complete population list</p>
<p><strong>But</strong> we often know the <em>probability</em> that each individual would be selected, based on demographics, geography, or other characteristics</p>
</div>
<div id="tabset-3-2">
<p><strong>Weights</strong> are set inversely proportional to the probability of selection:</p>
<ul>
<li>Individuals <em>less likely</em> to be sampled → <em>higher</em> weight</li>
<li>Individuals <em>more likely</em> to be sampled → <em>lower</em> weight</li>
<li>Result: a weighted sample that mirrors the full population</li>
</ul>
</div>
<div id="tabset-3-3">
<p>The GSS uses cluster sampling. Within each selected household, only one adult is chosen:</p>
<ul>
<li>Individuals in <em>larger</em> households are <em>less</em> likely to be selected → <em>higher</em> weights</li>
<li>Additional weights for oversampled Black respondents</li>
<li>Additional weights for non-responders on the first contact</li>
</ul>
<p><span class="highlight">Always check whether your dataset uses weights, and apply them in R</span></p>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-2-sampling-distributions" class="title-slide slide level1 center">
<h1>Part 2: Sampling Distributions</h1>
<p>Statistics vary from sample to sample — they have their own distributions</p>
</section>
<section id="what-is-a-sampling-distribution" class="slide level2 smaller scrollable">
<h2>What is a Sampling Distribution?</h2>
<p>A <strong>sampling distribution</strong> is the probability distribution of a sample statistic computed across many independent samples from the same population</p>
<p><strong>Three distributions you must keep straight:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Distribution</th>
<th>What it describes</th>
<th>Philadelphia example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Population</strong></td>
<td>All individuals in the population</td>
<td>1.45M Philadelphia residents, 42.2% African American</td>
</tr>
<tr class="even">
<td><strong>Sample (data)</strong></td>
<td>The individuals in <em>our</em> sample</td>
<td>262 police stops in 1997</td>
</tr>
<tr class="odd">
<td><strong>Sampling</strong></td>
<td>How our statistic would vary across <em>repeated</em> samples</td>
<td>Distribution of <span class="math inline">\(\hat{p}\)</span> across many random samples of 262</td>
</tr>
</tbody>
</table>
<p><span class="highlight"><strong>Key insights:</strong></span></p>
<ul>
<li>Sampling distributions describe <strong>variability from study to study</strong></li>
<li>They tell us <strong>how close a statistic is likely to fall</strong> to the true population parameter</li>
<li>They are <strong>not what we observe</strong> — they represent what we <em>would</em> observe across many hypothetical repetitions</li>
<li>They are the foundation for confidence intervals (Week 8) and hypothesis tests (Week 9)</li>
</ul>
</section>
<section id="sampling-distribution-of-a-proportion" class="slide level2 smaller">
<h2>Sampling Distribution of a Proportion</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">The bridge from Week 6</a></li><li><a href="#tabset-4-2">What it tells us</a></li><li><a href="#tabset-4-3">Connection to inference</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p>Recall: <span class="math inline">\(X \sim B(n, \pi)\)</span> has mean <span class="math inline">\(n\pi\)</span> and SD <span class="math inline">\(\sqrt{n\pi(1-\pi)}\)</span></p>
<p>The <strong>sample proportion</strong> <span class="math inline">\(\hat{p} = X/n\)</span> divides that count by <span class="math inline">\(n\)</span>. Its sampling distribution:</p>
<p><span class="math display">\[\mu_{\hat{p}} = \frac{n\pi}{n} = \pi \qquad SE(\hat{p}) = \frac{\sqrt{n\pi(1-\pi)}}{n} = \sqrt{\frac{\pi(1-\pi)}{n}}\]</span></p>
<p><strong>Same formula as last week’s Binomial SD — divided by <span class="math inline">\(n\)</span>.</strong></p>
</div>
<div id="tabset-4-2">
<p><span class="math display">\[\mu_{\hat{p}} = \pi \qquad \text{(unbiased — centered on the true proportion)}\]</span></p>
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{\pi(1-\pi)}{n}} \qquad \text{(shrinks as } n \text{ grows)}\]</span></p>
<p>We use <em>standard error</em> (SE) rather than <em>standard deviation</em> to signal that this is the spread of a <strong>sampling distribution</strong>, not of raw data.</p>
</div>
<div id="tabset-4-3">
<p>The SE answers: on average, how far will our <span class="math inline">\(\hat{p}\)</span> fall from the true <span class="math inline">\(\pi\)</span>?</p>
<ul>
<li>Small <span class="math inline">\(n\)</span> → large SE → estimates can be far from the truth</li>
<li>Large <span class="math inline">\(n\)</span> → small SE → estimates are reliably close to the truth</li>
</ul>
<p>This is the mechanism that makes large surveys more trustworthy — and why the GSS (≈3,000 respondents) gives more reliable estimates than a sample of 20.</p>
</div>
</div>
</div>
</section>
<section id="racial-profiling-a-worked-example" class="slide level2 smaller">
<h2>Racial Profiling: A Worked Example</h2>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">The Setup</a></li><li><a href="#tabset-5-2">The Math</a></li><li><a href="#tabset-5-3">The Verdict</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<p><strong>Data from Philadelphia, 1997:</strong></p>
<ul>
<li><strong>262</strong> police car stops were recorded</li>
<li><strong>207</strong> of the stopped drivers were African American (<span class="math inline">\(\hat{p} = 207/262 = 0.79\)</span>)</li>
<li>Philadelphia’s population at the time was <strong>42.2% African American</strong> (<span class="math inline">\(\pi = 0.422\)</span>)</li>
</ul>
<p><strong>Question</strong>: If drivers were stopped at random, how likely is it that 79% of stopped drivers would be African American?</p>
</div>
<div id="tabset-5-2">
<p>Assume random stopping: <span class="math inline">\(X \sim B(262, 0.422)\)</span></p>
<p>The <strong>sampling distribution</strong> of <span class="math inline">\(\hat{p}\)</span> under random stopping:</p>
<p><span class="math display">\[\mu_{\hat{p}} = 0.422\]</span></p>
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{0.422 \times 0.578}{262}} \approx 0.030\]</span></p>
</div>
<div id="tabset-5-3">
<p><strong>Observed</strong>: <span class="math inline">\(\hat{p} = 0.79\)</span></p>
<p><strong>Distance from expected</strong>:</p>
<p><span class="math display">\[z = \frac{0.79 - 0.422}{0.030} \approx 12 \text{ standard errors above the mean}\]</span></p>
<p>Under random stopping, <span class="math inline">\(\hat{p} = 0.79\)</span> is essentially impossible — it lies 12 SEs above what we’d expect. The sampling distribution reveals that this pattern cannot be explained by chance, but some other bias.</p>
</div>
</div>
</div>
</section>
<section id="visualizing-the-sampling-distribution" class="slide level2 smaller">
<h2>Visualizing the Sampling Distribution</h2>
<p>As <span class="math inline">\(N\)</span> increases, <span class="math inline">\(\hat{p}\)</span> becomes <strong>tighter and more bell-shaped</strong> — the Central Limit Theorem in action:</p>

<img data-src="week7_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="sampling-distribution-of-the-mean" class="slide level2 smaller">
<h2>Sampling Distribution of the Mean</h2>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">The Formula</a></li><li><a href="#tabset-6-2">Worked Example</a></li><li><a href="#tabset-6-3">The Visual</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>For a random sample of size <span class="math inline">\(n\)</span> from a population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>:</p>
<p><span class="math display">\[\mu_{\bar{x}} = \mu \qquad \text{(sample mean is unbiased)}\]</span></p>
<p><span class="math display">\[SE(\bar{x}) = \frac{\sigma}{\sqrt{n}} \qquad \text{(precision increases with sample size)}\]</span></p>
<p>Doubling <span class="math inline">\(n\)</span> cuts the SE by a factor of <span class="math inline">\(\sqrt{2}\)</span> — not 2. Precision is expensive!</p>
</div>
<div id="tabset-6-2">
<p><strong>Pizza sales</strong>: <span class="math inline">\(\mu = \$900/\text{day}\)</span>, <span class="math inline">\(\sigma = \$300\)</span>, <span class="math inline">\(n = 7\)</span> days</p>
<p><span class="math display">\[SE(\bar{x}) = \frac{\$300}{\sqrt{7}} \approx \$113\]</span></p>
<p>A 7-day average will typically be within <span class="math inline">\(\pm\$226\)</span> (2 SEs) of the true mean. Sampling 28 days instead cuts the SE in half: <span class="math inline">\(\frac{\$300}{\sqrt{28}} \approx \$57\)</span>.</p>
</div>
<div id="tabset-6-3">
<p>As <span class="math inline">\(n\)</span> grows, the sampling distribution narrows around the true mean <span class="math inline">\(\mu\)</span>:</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/week7/sampling_overlay.png" class="quarto-figure quarto-figure-center" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-3-the-central-limit-theorem" class="title-slide slide level1 center">
<h1>Part 3: The Central Limit Theorem</h1>
<p>The theorem that makes all of statistical inference possible</p>
</section>
<section id="the-central-limit-theorem" class="slide level2 smaller">
<h2>The Central Limit Theorem</h2>
<p><strong>This is one of the most powerful theorems in all of statistics.</strong></p>
<blockquote>
<p>If repeated independent samples of size <span class="math inline">\(N\)</span> are drawn from <strong>any population</strong> (regardless of its shape) having mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>, then — as <span class="math inline">\(N\)</span> becomes large — the sampling distribution of the sample mean approaches a Normal distribution:</p>
<p><span class="math display">\[\bar{x} \;\sim\; N\!\left(\mu,\; \frac{\sigma}{\sqrt{N}}\right)\]</span></p>
</blockquote>
<p><strong>Why is this remarkable?</strong> The <em>population</em> can be skewed, bimodal, uniform — it doesn’t matter. As long as <span class="math inline">\(N\)</span> is large enough, <span class="math inline">\(\bar{x}\)</span> is approximately Normal.</p>
<p>This is why the Normal distribution appears everywhere in statistics — and why the tools we build next all work.</p>
</section>
<section id="clt-interactive-demo" class="slide level2" data-background-iframe="https://seeing-theory.brown.edu/probability-distributions/index.html#section3" data-background-interactive="true">
<h2>CLT: Interactive Demo</h2>
</section>
<section id="how-large-a-sample" class="slide level2 smaller">
<h2>How Large a Sample?</h2>
<p>The sampling distribution approaches normality faster for more symmetric populations:</p>
<ul>
<li>If the <strong>population distribution is Normal</strong>, the sampling distribution is Normal for <em>any</em> <span class="math inline">\(n\)</span></li>
<li>The more <strong>skewed</strong> the population, the larger <span class="math inline">\(n\)</span> must be</li>
<li><strong>In practice</strong>: <span class="math inline">\(n &gt; 30\)</span> is usually sufficient for most real-world distributions</li>
</ul>
<div class="fragment fade-up">
<p><strong>Why this matters for your research</strong>: Most survey samples (GSS, IPUMS, etc.) have <span class="math inline">\(n\)</span> in the hundreds or thousands — well above the threshold where CLT guarantees apply. This is what lets us do inference from survey data without knowing the full population distribution.</p>
</div>
</section>
<section id="rolling-dice-a-worked-example" class="slide level2 smaller">
<h2>Rolling Dice: A Worked Example</h2>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Setup</a></li><li><a href="#tabset-7-2">Applying the CLT</a></li><li><a href="#tabset-7-3">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p><strong>Question</strong>: What is the probability that the mean of 35 dice rolls is less than 3?</p>
<p><strong>Step 1: Parameters of a single die roll</strong></p>
<p>A fair die has outcomes 1–6, each with probability 1/6:</p>
<ul>
<li>Mean: <span class="math inline">\(\mu = \frac{1+2+3+4+5+6}{6} = 3.5\)</span></li>
<li>Variance: <span class="math inline">\(\sigma^2 = \frac{(1-3.5)^2 + (2-3.5)^2 + \cdots + (6-3.5)^2}{6} = \frac{35}{12}\)</span>, so <span class="math inline">\(\sigma = \sqrt{35/12}\)</span></li>
</ul>
</div>
<div id="tabset-7-2">
<p><strong>Step 2: Sampling distribution of <span class="math inline">\(\bar{x}\)</span></strong> for <span class="math inline">\(n = 35\)</span> rolls</p>
<p>By the CLT — same <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span> formula as the Binomial SE from Week 6, now applied to any population:</p>
<p><span class="math display">\[SE(\bar{x}) = \frac{\sigma}{\sqrt{n}} = \frac{\sqrt{35/12}}{\sqrt{35}} = \frac{\sqrt{35}}{\sqrt{12} \cdot \sqrt{35}} = \frac{1}{\sqrt{12}} \approx 0.289\]</span></p>
<p>So <span class="math inline">\(\bar{x} \sim N(3.5,\; 0.289)\)</span></p>
</div>
<div id="tabset-7-3">
<p><strong>Step 3: Compute the probability in R</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">pnorm</span>(<span class="dv">3</span>, <span class="at">mean =</span> <span class="fl">3.5</span>, <span class="at">sd =</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">12</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04163226</code></pre>
</div>
</div>
<p>The probability is approximately <strong>4.2%</strong> — rolling a mean below 3 across 35 dice is unusual but not impossible.</p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2 smaller">
<h2>Key Takeaways</h2>
<ul>
<li><strong>Populations</strong> have parameters; <strong>samples</strong> have statistics — and they’re different things</li>
<li>A <strong>sampling distribution</strong> describes how a statistic varies across many hypothetical samples</li>
<li>The <strong>standard error</strong> (SE) measures this variability — it shrinks as <span class="math inline">\(\sqrt{n}\)</span> grows</li>
<li>The <strong>Central Limit Theorem</strong> guarantees that sample means are approximately Normal for large <span class="math inline">\(n\)</span>, regardless of the population shape</li>
</ul>
<blockquote>
<p>Sample → statistic → sampling distribution → inference. This is the chain that runs through the rest of the course.</p>
</blockquote>
</section>
<section id="why-this-matters-for-the-rest-of-the-course" class="slide level2 smaller">
<h2>Why This Matters for the Rest of the Course</h2>
<ul>
<li><strong>Next week (Week 8):</strong> Confidence intervals use the SE and the Normal approximation to build a range of plausible parameter values</li>
<li><strong>Week 9:</strong> Hypothesis tests ask “how far is our statistic from what we’d expect?” — measured in standard errors</li>
<li><strong>Weeks 11–13 (Regression):</strong> Every regression coefficient comes with a standard error and a significance test — all built on exactly the CLT logic we developed today</li>
</ul>
<blockquote>
<p>The CLT is not just this week’s topic. It is the engine of all classical statistical inference. Once you understand it, you understand <em>why</em> every test we’ll do actually works.</p>
</blockquote>
</section>
<section id="questions-1" class="slide level2">
<h2>Questions?</h2>
</section>
<section id="assignments" class="slide level2 smaller">
<h2>Assignments</h2>
<p><strong>Weekly Assignment #6</strong></p>
<ul>
<li><span class="highlight">Due Thursday, March 12</span> by 11:59 PM</li>
<li>Format: mix of word problems and R (similar to previous weeks)</li>
</ul>
<p><strong>Annotated Bibliography</strong></p>
<ul>
<li><span class="highlight">Due Thursday, March 19</span></li>
<li>Finding 10 relevant papers takes time — start early!</li>
<li>Don’t expect the first papers you find to be relevant to your project</li>
<li>Happy to help during office hours</li>
</ul>
</section>
<section id="in-class-lab-4" class="slide level2 smaller">
<h2>In-class Lab #4</h2>
<ol type="1">
<li>Download <code>lab4.qmd</code> from bCourses under “assignments” &gt; “Lab #4”</li>
<li>Place <code>lab4.qmd</code> in your <code>labs</code> folder</li>
<li>Use the <code>Explorer</code> button on the left to find and open <code>lab4.qmd</code></li>
<li>Let’s work through it together!</li>
</ol>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://www.kaseyzapatka.com/soc106">GitHub course repo</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>